package org.slavicmyths.registry;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.*;
import net.minecraft.core.registries.Registries;
import org.slavicmyths.item.ModGear;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

import org.slavicmyths.SlavicMyths;

/** Content registration only; future player mechanics belong to separate systems. */
public final class ModItems {
    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(Registries.ITEM, SlavicMyths.MOD_ID);

    public static final DeferredHolder<Item, Item> RYE_SEEDS = ITEMS.register("rye_seeds", () -> new ItemNameBlockItem(ModBlocks.RYE_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> BARLEY_SEEDS = ITEMS.register("barley_seeds", () -> new ItemNameBlockItem(ModBlocks.BARLEY_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> OAT_SEEDS = ITEMS.register("oat_seeds", () -> new ItemNameBlockItem(ModBlocks.OAT_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> TURNIP_SEEDS = ITEMS.register("turnip_seeds", () -> new ItemNameBlockItem(ModBlocks.TURNIP_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> CABBAGE_SEEDS = ITEMS.register("cabbage_seeds", () -> new ItemNameBlockItem(ModBlocks.CABBAGE_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> PEA_SEEDS = ITEMS.register("pea_seeds", () -> new ItemNameBlockItem(ModBlocks.PEA_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> FLAX_SEEDS = ITEMS.register("flax_seeds", () -> new ItemNameBlockItem(ModBlocks.FLAX_CROP.get(), properties()));
    public static final DeferredHolder<Item, Item> RYE_GRAIN = ITEMS.register("rye_grain", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> BARLEY_GRAIN = ITEMS.register("barley_grain", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> OAT_GRAIN = ITEMS.register("oat_grain", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> TURNIP = ITEMS.register("turnip", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(2).saturationModifier(.4F).build())));
    public static final DeferredHolder<Item, Item> CABBAGE = ITEMS.register("cabbage", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(2).saturationModifier(.3F).build())));
    public static final DeferredHolder<Item, Item> PEA_POD = ITEMS.register("pea_pod", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(2).saturationModifier(.3F).build())));
    public static final DeferredHolder<Item, Item> FLAX_STALK = ITEMS.register("flax_stalk", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> SICKLE = ITEMS.register("sickle", () -> new org.slavicmyths.farming.SickleItem(properties()));
    public static final DeferredHolder<Item, Item> FIELD_HOE = ITEMS.register("field_hoe", () -> new org.slavicmyths.farming.FieldHoeItem(properties()));
    public static final DeferredHolder<Item, Item> WATERING_CAN = ITEMS.register("watering_can", () -> new org.slavicmyths.farming.WateringCanItem(properties()));
    public static final DeferredHolder<Item, Item> ORGANIC_FERTILIZER = ITEMS.register("organic_fertilizer", () -> new org.slavicmyths.farming.FertilizerItem(properties()));

    public static final DeferredHolder<Item, Item> BIRCH_BARK_SCROLL = ITEMS.register(
            "birch_bark_scroll", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> THUNDER_STONE = ITEMS.register(
            "thunder_stone", () -> new Item(properties()
                    .rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> WARDING_CHARM = ITEMS.register(
            "warding_charm", () -> new Item(properties()));

    public static final DeferredHolder<Item, Item> BIRCH_BARK = ITEMS.register("birch_bark", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> LINEN_THREAD = ITEMS.register("linen_thread", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> PERUNITE = ITEMS.register("perunite", () -> new Item(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> FERN_FLOWER = ITEMS.register("fern_flower", () -> new Item(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> FLAX = ITEMS.register("flax", () -> new BlockItem(ModBlocks.FLAX.get(), properties()));
    public static final DeferredHolder<Item, Item> WORMWOOD = ITEMS.register("wormwood", () -> new BlockItem(ModBlocks.WORMWOOD.get(), properties()));
    public static final DeferredHolder<Item, Item> PERUNITE_ORE = ITEMS.register("perunite_ore", () -> new BlockItem(ModBlocks.PERUNITE_ORE.get(), properties()));
    public static final DeferredHolder<Item, Item> LESHY_HEART = ITEMS.register("leshy_heart", () -> new Item(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> DOMOVOY_SPAWN_EGG = ITEMS.register("domovoy_spawn_egg",
            () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.DOMOVOY, 0x77563D, 0xD2C0A2, properties()));
    public static final DeferredHolder<Item, Item> LESHY_SPAWN_EGG = ITEMS.register("leshy_spawn_egg",
            () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.LESHY, 0x343F2B, 0xC5DC76, properties()));

    private static Item.Properties properties() {
        return new Item.Properties();
    }

    public static final DeferredHolder<Item, Item> HEARTH = ITEMS.register("hearth", () -> new BlockItem(ModBlocks.HEARTH.get(), properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_IDOL = ITEMS.register("ancient_idol", () -> new BlockItem(ModBlocks.ANCIENT_IDOL.get(), properties()));
    public static final DeferredHolder<Item, Item> ALTAR = ITEMS.register("altar", () -> new BlockItem(ModBlocks.ALTAR.get(), properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_COIN = ITEMS.register("ancient_coin", () -> new org.slavicmyths.item.AncientCoinItem(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> IDOL_FRAGMENT = ITEMS.register("idol_fragment", () -> new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> ANCIENT_SIGN = ITEMS.register("ancient_sign", () -> new org.slavicmyths.item.AncientSignItem(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> LORE_BOOK = ITEMS.register("lore_book", () -> new org.slavicmyths.item.LoreBookItem(properties().stacksTo(1)));

    public static final DeferredHolder<Item, Item> SILVER_ORE = ITEMS.register("silver_ore", () -> new BlockItem(ModBlocks.SILVER_ORE.get(), properties()));
    public static final DeferredHolder<Item, Item> SILVER_INGOT = ITEMS.register("silver_ingot", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> SILVER_NUGGET = ITEMS.register("silver_nugget", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> PERUNITE_SWORD = ITEMS.register("perunite_sword", () -> new SwordItem(ModGear.PERUNITE, properties().attributes(SwordItem.createAttributes(ModGear.PERUNITE, 3, -2.4F))));
    public static final DeferredHolder<Item, Item> PERUNITE_AXE = ITEMS.register("perunite_axe", () -> new AxeItem(ModGear.PERUNITE, properties().attributes(AxeItem.createAttributes(ModGear.PERUNITE, 5.0F, -3.1F))));
    public static final DeferredHolder<Item, Item> PERUNITE_PICKAXE = ITEMS.register("perunite_pickaxe", () -> new PickaxeItem(ModGear.PERUNITE, properties().attributes(PickaxeItem.createAttributes(ModGear.PERUNITE, 1, -2.8F))));
    public static final DeferredHolder<Item, Item> PERUNITE_SHOVEL = ITEMS.register("perunite_shovel", () -> new ShovelItem(ModGear.PERUNITE, properties().attributes(ShovelItem.createAttributes(ModGear.PERUNITE, 1.5F, -3.0F))));
    public static final DeferredHolder<Item, Item> PERUNITE_HOE = ITEMS.register("perunite_hoe", () -> new HoeItem(ModGear.PERUNITE, properties().attributes(HoeItem.createAttributes(ModGear.PERUNITE, -2, -1.0F))));
    public static final DeferredHolder<Item, Item> PERUNITE_HELMET = ITEMS.register("perunite_helmet", () -> new ArmorItem(ModGear.PERUNITE_ARMOR, ArmorItem.Type.HELMET, properties().durability(ArmorItem.Type.HELMET.getDurability(23))));
    public static final DeferredHolder<Item, Item> PERUNITE_CHESTPLATE = ITEMS.register("perunite_chestplate", () -> new ArmorItem(ModGear.PERUNITE_ARMOR, ArmorItem.Type.CHESTPLATE, properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(23))));
    public static final DeferredHolder<Item, Item> PERUNITE_LEGGINGS = ITEMS.register("perunite_leggings", () -> new ArmorItem(ModGear.PERUNITE_ARMOR, ArmorItem.Type.LEGGINGS, properties().durability(ArmorItem.Type.LEGGINGS.getDurability(23))));
    public static final DeferredHolder<Item, Item> PERUNITE_BOOTS = ITEMS.register("perunite_boots", () -> new ArmorItem(ModGear.PERUNITE_ARMOR, ArmorItem.Type.BOOTS, properties().durability(ArmorItem.Type.BOOTS.getDurability(23))));
    public static final DeferredHolder<Item, Item> SILVER_SWORD = ITEMS.register("silver_sword", () -> new SwordItem(ModGear.SILVER, properties().attributes(SwordItem.createAttributes(ModGear.SILVER, 3, -2.4F))));
    public static final DeferredHolder<Item, Item> SILVER_DAGGER = ITEMS.register("silver_dagger", () -> new SwordItem(ModGear.SILVER, properties().attributes(SwordItem.createAttributes(ModGear.SILVER, 1, -1.5F))));
    public static final DeferredHolder<Item, Item> BONE_KNIFE = ITEMS.register("bone_knife", () -> new SwordItem(ModGear.BONE, properties().attributes(SwordItem.createAttributes(ModGear.BONE, 2, -1.5F))));
    public static final DeferredHolder<Item, Item> RITUAL_KNIFE = ITEMS.register("ritual_knife", () -> new SwordItem(ModGear.SILVER, properties().attributes(SwordItem.createAttributes(ModGear.SILVER, 1, -1.7F))));
    public static final DeferredHolder<Item, Item> LINEN_CLOTH = ITEMS.register("linen_cloth", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> HERB_POUCH = ITEMS.register("herb_pouch", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> ST_JOHNS_WORT = ITEMS.register("st_johns_wort", () -> new BlockItem(ModBlocks.ST_JOHNS_WORT.get(), properties()));
    public static final DeferredHolder<Item, Item> NETTLE = ITEMS.register("nettle", () -> new BlockItem(ModBlocks.NETTLE.get(), properties()));
    public static final DeferredHolder<Item, Item> FIREWEED = ITEMS.register("fireweed", () -> new BlockItem(ModBlocks.FIREWEED.get(), properties()));
    public static final DeferredHolder<Item, Item> JUNIPER_BERRIES = ITEMS.register("juniper_berries", () -> new BlockItem(ModBlocks.JUNIPER_BERRIES.get(), properties()));
    public static final DeferredHolder<Item, Item> GROUND_WORMWOOD = ITEMS.register("ground_wormwood", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> GROUND_ST_JOHNS_WORT = ITEMS.register("ground_st_johns_wort", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> JUNIPER_BLEND = ITEMS.register("juniper_blend", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> HONEY_BREAD = ITEMS.register("honey_bread", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(7).saturationModifier(0.6F).build())));
    public static final DeferredHolder<Item, Item> HONEY_BAKED_APPLE = ITEMS.register("honey_baked_apple", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(6).saturationModifier(0.5F).build())));
    public static final DeferredHolder<Item, Item> RITUAL_BOWL = ITEMS.register("ritual_bowl", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> THUNDER_AXE = ITEMS.register("thunder_axe", () -> new org.slavicmyths.item.ThunderAxeItem(ModGear.PERUNITE, properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> PERUN_CHARM = ITEMS.register("perun_charm", () -> new org.slavicmyths.item.PerunCharmItem(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> CARVED_OAK_PILLAR = ITEMS.register("carved_oak_pillar", () -> new BlockItem(ModBlocks.CARVED_OAK_PILLAR.get(), properties()));
    public static final DeferredHolder<Item, Item> CARVED_BIRCH_PLANKS = ITEMS.register("carved_birch_planks", () -> new BlockItem(ModBlocks.CARVED_BIRCH_PLANKS.get(), properties()));
    public static final DeferredHolder<Item, Item> CARVED_OAK_BLOCK = ITEMS.register("carved_oak_block", () -> new BlockItem(ModBlocks.CARVED_OAK_BLOCK.get(), properties()));
    public static final DeferredHolder<Item, Item> STRAW_BLOCK = ITEMS.register("straw_block", () -> new BlockItem(ModBlocks.STRAW_BLOCK.get(), properties()));
    public static final DeferredHolder<Item, Item> AMBER = ITEMS.register("amber", () -> new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> AMBER_BLOCK = ITEMS.register("amber_block", () -> new BlockItem(ModBlocks.AMBER_BLOCK.get(), properties()));
    public static final DeferredHolder<Item, Item> AMBER_CHARM = ITEMS.register("amber_charm", () -> new org.slavicmyths.item.AmberCharmItem(properties()));
    public static final DeferredHolder<Item, Item> CARVED_STAFF = ITEMS.register("carved_staff", () -> new SwordItem(Tiers.WOOD, properties().attributes(SwordItem.createAttributes(Tiers.WOOD, 2, -2.8F))));
    public static final DeferredHolder<Item, Item> STORM_STAFF = ITEMS.register("storm_staff", () -> new org.slavicmyths.item.StormStaffItem(properties().stacksTo(1).durability(240).rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> CLUB = ITEMS.register("club", () -> new org.slavicmyths.item.ClubItem(properties()));
    public static final DeferredHolder<Item, Item> BATTLE_AXE = ITEMS.register("battle_axe", () -> new AxeItem(Tiers.IRON, properties().attributes(AxeItem.createAttributes(Tiers.IRON, 7.0F, -3.3F))));
    public static final DeferredHolder<Item, Item> SPEAR = ITEMS.register("spear", () -> new org.slavicmyths.item.SpearItem(Tiers.STONE, properties()));
    public static final DeferredHolder<Item, Item> SILVER_SPEAR = ITEMS.register("silver_spear", () -> new org.slavicmyths.item.SpearItem(ModGear.SILVER, properties()));
    public static final DeferredHolder<Item, Item> RITUAL_CHARCOAL = ITEMS.register("ritual_charcoal", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> RITUAL_CANDLE = ITEMS.register("ritual_candle", () -> new BlockItem(ModBlocks.RITUAL_CANDLE.get(), properties()));
    public static final DeferredHolder<Item, Item> HONEY_FLATBREAD = ITEMS.register("honey_flatbread", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(6).saturationModifier(0.7F).build())));
    public static final DeferredHolder<Item, Item> BERRY_MORS = ITEMS.register("berry_mors", () -> new org.slavicmyths.item.BerryMorsItem(properties().stacksTo(1).food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(3).saturationModifier(0.3F).alwaysEdible().build())));
    public static final DeferredHolder<Item, Item> FOREST_MIX = ITEMS.register("forest_mix", () -> new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(4).saturationModifier(0.3F).build())));
    public static final DeferredHolder<Item, Item> WALL_CARVING = ITEMS.register("wall_carving", () -> new BlockItem(ModBlocks.WALL_CARVING.get(), properties()));
    public static final DeferredHolder<Item, Item> FOREST_CHARM = ITEMS.register("forest_charm", () -> new org.slavicmyths.item.SimpleCharmItem("forest_charm", properties()));
    public static final DeferredHolder<Item, Item> HUNTER_CHARM = ITEMS.register("hunter_charm", () -> new org.slavicmyths.item.SimpleCharmItem("hunter_charm", properties()));
    public static final DeferredHolder<Item, Item> TRAVELER_CHARM = ITEMS.register("traveler_charm", () -> new org.slavicmyths.item.SimpleCharmItem("traveler_charm", properties()));
    public static final DeferredHolder<Item, Item> RETAINER_SHIELD = ITEMS.register("retainer_shield", () -> new org.slavicmyths.item.MythShieldItem(properties().durability(280)));
    public static final DeferredHolder<Item, Item> PERUNITE_SHIELD = ITEMS.register("perunite_shield", () -> new org.slavicmyths.item.MythShieldItem(properties().durability(420).rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> THUNDER_SPEAR = ITEMS.register("thunder_spear", () -> new org.slavicmyths.item.HeavyWeaponItem(ModGear.PERUNITE, 4, -2.9F, 0.18, properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> MACE = ITEMS.register("mace", () -> new org.slavicmyths.combat.MaceItem(Tiers.IRON, 8, .9F, .35F, .45F, properties()));
    public static final DeferredHolder<Item, Item> PERUNITE_MACE = ITEMS.register("perunite_mace", () -> new org.slavicmyths.combat.MaceItem(ModGear.PERUNITE, 9.5F, .6F, .4F, .4F, properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> BERDYSH = ITEMS.register("berdysh", () -> new org.slavicmyths.item.HeavyWeaponItem(Tiers.IRON, 6, -3.3F, 0, properties()));
    public static final DeferredHolder<Item, Item> WEAPON_WRAP = ITEMS.register("weapon_wrap", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> SILVER_FITTING = ITEMS.register("silver_fitting", () -> new Item(properties()));

    public static final DeferredHolder<Item, Item> KIKIMORA_LOCK = ITEMS.register("kikimora_lock", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> NOON_EAR = ITEMS.register("noon_ear", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> FIELD_BUNDLE = ITEMS.register("field_bundle", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> BATH_BROOM = ITEMS.register("bath_broom", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> BATH_STONE = ITEMS.register("bath_stone", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> OLD_BUTTON = ITEMS.register("old_button", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> OVINNIK_CLAW = ITEMS.register("ovinnik_claw", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> EMBER_HEART = ITEMS.register("ember_heart", () -> new Item(properties()));
    public static final DeferredHolder<Item, Item> NOON_SICKLE = ITEMS.register("noon_sickle", () -> new SwordItem(ModGear.SILVER, properties().rarity(Rarity.UNCOMMON).attributes(SwordItem.createAttributes(ModGear.SILVER, 3, -2.5F))));
    public static final DeferredHolder<Item, Item> KIKIMORA_SPAWN_EGG = ITEMS.register("kikimora_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.KIKIMORA, 0x494137, 0xbca981, properties()));
    public static final DeferredHolder<Item, Item> POLUDNITSA_SPAWN_EGG = ITEMS.register("poludnitsa_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.POLUDNITSA, 0x494137, 0xbca981, properties()));
    public static final DeferredHolder<Item, Item> POLEVIK_SPAWN_EGG = ITEMS.register("polevik_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.POLEVIK, 0x494137, 0xbca981, properties()));
    public static final DeferredHolder<Item, Item> BANNIK_SPAWN_EGG = ITEMS.register("bannik_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.BANNIK, 0x494137, 0xbca981, properties()));
    public static final DeferredHolder<Item, Item> IGOSHA_SPAWN_EGG = ITEMS.register("igosha_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.IGOSHA, 0x494137, 0xbca981, properties()));
    public static final DeferredHolder<Item, Item> OVINNIK_SPAWN_EGG = ITEMS.register("ovinnik_spawn_egg", () -> new net.neoforged.neoforge.common.DeferredSpawnEggItem(ModEntities.OVINNIK, 0x2C2722, 0xE34A18, properties()));
    public static final DeferredHolder<Item, Item> BATH_STOVE = ITEMS.register("bath_stove", () -> new BlockItem(ModBlocks.BATH_STOVE.get(), properties()));
    public static final DeferredHolder<Item, Item> WOODEN_TUB = ITEMS.register("wooden_tub", () -> new BlockItem(ModBlocks.WOODEN_TUB.get(), properties()));

    public static final DeferredHolder<Item, Item> PATH_STONE=ITEMS.register("path_stone",()->new BlockItem(ModBlocks.PATH_STONE.get(),properties()));
    public static final DeferredHolder<Item, Item> RUNIC_ANVIL=ITEMS.register("runic_anvil",()->new BlockItem(ModBlocks.RUNIC_ANVIL.get(),properties()));
    public static final DeferredHolder<Item, Item> RUNE_THUNDER=ITEMS.register("rune_thunder",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_HEAT=ITEMS.register("rune_heat",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_FOREST=ITEMS.register("rune_forest",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_MIDDAY=ITEMS.register("rune_midday",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_SHADOW=ITEMS.register("rune_shadow",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_PROTECTION=ITEMS.register("rune_protection",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_LIFE=ITEMS.register("rune_life",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RUNE_WIND=ITEMS.register("rune_wind",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> RAW_BEAR_MEAT=food("raw_bear_meat",4,.25F);
    public static final DeferredHolder<Item, Item> COOKED_BEAR_MEAT=food("cooked_bear_meat",9,.8F);
    public static final DeferredHolder<Item, Item> RAW_VENISON=food("raw_venison",3,.25F);
    public static final DeferredHolder<Item, Item> COOKED_VENISON=food("cooked_venison",8,.75F);
    public static final DeferredHolder<Item, Item> RAW_BOAR_MEAT=food("raw_boar_meat",3,.3F);
    public static final DeferredHolder<Item, Item> COOKED_BOAR_MEAT=food("cooked_boar_meat",8,.8F);
    public static final DeferredHolder<Item, Item> LARGE_ANIMAL_BONE=ITEMS.register("large_animal_bone",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> BONE_ARROW=ITEMS.register("bone_arrow",()->new ArrowItem(properties()));
    public static final DeferredHolder<Item, Item> FLOUR=ITEMS.register("flour",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> RASPBERRY=ITEMS.register("raspberry",()->new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(2).saturationModifier(.20F).build())));
    public static final DeferredHolder<Item, Item> BLUEBERRY=ITEMS.register("blueberry",()->new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(2).saturationModifier(.20F).build())));
    public static final DeferredHolder<Item, Item> PANCAKES=food("pancakes",5,.5F);
    public static final DeferredHolder<Item, Item> RASPBERRY_PANCAKES=food("raspberry_pancakes",7,.65F);
    public static final DeferredHolder<Item, Item> BLUEBERRY_PANCAKES=food("blueberry_pancakes",7,.65F);
    public static final DeferredHolder<Item, Item> MEAT_PANCAKES=food("meat_pancakes",9,.8F);
    public static final DeferredHolder<Item, Item> KARAVAI=food("karavai",10,.9F);
    public static final DeferredHolder<Item, Item> BERRY_PIE=food("berry_pie",8,.7F);
    public static final DeferredHolder<Item, Item> BAKED_APPLE=food("baked_apple",6,.55F);
    public static final DeferredHolder<Item, Item> MUSHROOM_STEW=stew("mushroom_stew",7,.6F);
    public static final DeferredHolder<Item, Item> BEEF_STEW=stew("beef_stew",10,.9F);
    public static final DeferredHolder<Item, Item> PORK_STEW=stew("pork_stew",10,.9F);
    public static final DeferredHolder<Item, Item> VENISON_STEW=stew("venison_stew",10,.9F);
    public static final DeferredHolder<Item, Item> BEAR_STEW=stew("bear_stew",11,1F);
    public static final DeferredHolder<Item, Item> BROWN_BEAR_SPAWN_EGG=ITEMS.register("brown_bear_spawn_egg",()->new org.slavicmyths.item.WildlifeFamilyEgg(true,0x4b3427,0xb28a62,properties()));
    public static final DeferredHolder<Item, Item> BEAR_CUB_SPAWN_EGG=egg("bear_cub_spawn_egg",ModEntities.BEAR_CUB,0x6b4a35,0xcda578);
    public static final DeferredHolder<Item, Item> FOREST_WOLF_SPAWN_EGG=egg("forest_wolf_spawn_egg",ModEntities.FOREST_WOLF,0x292b2e,0xb2a98f);
    public static final DeferredHolder<Item, Item> BOAR_SPAWN_EGG=egg("boar_spawn_egg",ModEntities.BOAR,0x493a32,0xd5c09c);
    public static final DeferredHolder<Item, Item> STAG_SPAWN_EGG=ITEMS.register("stag_spawn_egg",()->new org.slavicmyths.item.WildlifeFamilyEgg(false,0x76533b,0xd1ad7b,properties()));
    public static final DeferredHolder<Item, Item> DOE_SPAWN_EGG=egg("doe_spawn_egg",ModEntities.DOE,0x9a7653,0xe0c29c);
    private static DeferredHolder<Item, Item> food(String id,int nutrition,float saturation){return ITEMS.register(id,()->new Item(properties().food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(nutrition).saturationModifier(saturation).build())));}
    private static DeferredHolder<Item, Item> stew(String id,int nutrition,float saturation){return ITEMS.register(id,()->new Item(properties().stacksTo(1).food(new net.minecraft.world.food.FoodProperties.Builder().nutrition(nutrition).saturationModifier(saturation).usingConvertsTo(Items.BOWL).build())));}
    private static DeferredHolder<Item, Item> egg(String id,java.util.function.Supplier<? extends net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.Mob>> type,int primary,int secondary){return ITEMS.register(id,()->new net.neoforged.neoforge.common.DeferredSpawnEggItem(type,primary,secondary,properties()));}
    public static final DeferredHolder<Item, Item> INVISIBILITY_CAP=ITEMS.register("invisibility_cap",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"head"));
    public static final DeferredHolder<Item, Item> RETRIBUTION_CHARM=ITEMS.register("retribution_charm",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"charm"));
    public static final DeferredHolder<Item, Item> PERUN_RING=ITEMS.register("perun_ring",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"ring"));
    public static final DeferredHolder<Item, Item> VELES_AMULET=ITEMS.register("veles_amulet",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"necklace"));
    public static final DeferredHolder<Item, Item> HUNTER_BELT=ITEMS.register("hunter_belt",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"belt"));
    public static final DeferredHolder<Item, Item> RESIN_RING=ITEMS.register("resin_ring",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"ring"));
    public static final DeferredHolder<Item, Item> SEVEN_LEAGUE_BOOTS=ITEMS.register("seven_league_boots",()->new org.slavicmyths.item.SevenLeagueBoots(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> KITCHEN_TABLE=ITEMS.register("kitchen_table",()->new BlockItem(ModBlocks.KITCHEN_TABLE.get(),properties()));
    public static final DeferredHolder<Item, Item> ROLLING_PIN=ITEMS.register("rolling_pin",()->new Item(properties().durability(128)));
    public static final DeferredHolder<Item, Item> METAL_POT=ITEMS.register("metal_pot",()->new Item(properties().durability(256)));
    public static final DeferredHolder<Item, Item> FLYING_BROOM=ITEMS.register("flying_broom",()->new org.slavicmyths.flight.FlightItem(properties().rarity(Rarity.RARE),false));
    public static final DeferredHolder<Item, Item> FLYING_MORTAR=ITEMS.register("flying_mortar",()->new org.slavicmyths.flight.FlightItem(properties().rarity(Rarity.RARE),true));
    public static final DeferredHolder<Item, Item> PESTLE=ITEMS.register("pestle",()->new Item(properties().stacksTo(1)));
    public static final DeferredHolder<Item, Item> GUSLI=ITEMS.register("gusli",()->new org.slavicmyths.artifact.GusliItem(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> SKATERT=ITEMS.register("skatert",()->new org.slavicmyths.artifact.SkatertItem(properties().rarity(Rarity.EPIC)));
    public static final DeferredHolder<Item, Item> BADNYAK=ITEMS.register("badnyak",()->new org.slavicmyths.artifact.BadnyakItem(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> VELES_STAFF=ITEMS.register("veles_staff",()->new org.slavicmyths.artifact.VelesStaffItem(properties().rarity(Rarity.EPIC)));
    public static final DeferredHolder<Item, Item> RAW_PIKE=food("raw_pike",3,.2F),COOKED_PIKE=food("cooked_pike",7,.7F),RAW_CARP=food("raw_carp",3,.2F),COOKED_CARP=food("cooked_carp",6,.65F),SMOKED_CARP=food("smoked_carp",8,.8F),RAW_CRAYFISH=food("raw_crayfish",2,.1F),COOKED_CRAYFISH=food("cooked_crayfish",5,.6F),UKHA=stew("ukha",10,.8F);
    public static final DeferredHolder<Item, Item> OLD_HOOK=ITEMS.register("old_hook",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> PEARL_FRAGMENT=ITEMS.register("pearl_fragment",()->new Item(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> PIKE_SPAWN_EGG=egg("pike_spawn_egg",ModEntities.PIKE,0x53623b,0xbaad78),CARP_SPAWN_EGG=egg("carp_spawn_egg",ModEntities.CARP,0x9b753a,0xd0ae64),CRAYFISH_SPAWN_EGG=egg("crayfish_spawn_egg",ModEntities.CRAYFISH,0x414333,0x777750);
    public static final DeferredHolder<Item, Item> FISHING_NET=ITEMS.register("fishing_net",()->new BlockItem(ModBlocks.FISHING_NET.get(),properties().durability(32)));
    public static final DeferredHolder<Item, Item> REED=ITEMS.register("reed",()->new BlockItem(ModBlocks.REED.get(),properties()));
    public static final DeferredHolder<Item, Item> WATER_GRASS=ITEMS.register("water_grass",()->new BlockItem(ModBlocks.WATER_GRASS.get(),properties()));
    public static final DeferredHolder<Item, Item> WHITE_LILY=ITEMS.register("white_lily",()->new net.minecraft.world.item.PlaceOnWaterBlockItem(ModBlocks.WHITE_LILY.get(),properties()));
    public static final DeferredHolder<Item,Item> BOLOTNIK_SPAWN_EGG=egg("bolotnik_spawn_egg",ModEntities.BOLOTNIK,0x343529,0x657144);
    public static final DeferredHolder<Item, Item> VODYANOY_SPAWN_EGG=egg("vodyanoy_spawn_egg",ModEntities.VODYANOY,0x59695d,0x8f9364),RUSALKA_SPAWN_EGG=egg("rusalka_spawn_egg",ModEntities.RUSALKA,0xc3d1c7,0x3e5749);
    public static final DeferredHolder<Item, Item> POOL_PEARL=ITEMS.register("pool_pearl",()->new Item(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> ANCIENT_WATER_SIGN=ITEMS.register("ancient_water_sign",()->new org.slavicmyths.depth.WaterSignItem(properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredHolder<Item, Item> POOL_SPEAR=ITEMS.register("pool_spear",()->new org.slavicmyths.depth.PoolSpear(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> DEPTH_AMULET=ITEMS.register("depth_amulet",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"necklace"));
    public static final DeferredHolder<Item, Item> VODYANOY_NET=ITEMS.register("vodyanoy_net",()->new org.slavicmyths.depth.VodyanoyNetItem(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> POOL_STONE=ITEMS.register("pool_stone",()->new BlockItem(ModBlocks.POOL_STONE.get(),properties()));
    public static final DeferredHolder<Item, Item> ELDER_VODYANOY_SPAWN_EGG=egg("elder_vodyanoy_spawn_egg",ModEntities.ELDER_VODYANOY,0x3f5149,0x889273);
    public static final DeferredHolder<Item, Item> ARMORER_TABLE=ITEMS.register("armorer_table",()->new BlockItem(ModBlocks.ARMORER_TABLE.get(),properties()));
    public static final DeferredHolder<Item, Item> IRON_RINGS=ITEMS.register("iron_rings",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> WOODEN_MACE=ITEMS.register("wooden_mace",()->new org.slavicmyths.combat.MaceItem(Tiers.WOOD,5,1.05F,.2F,.3F,properties()));
    public static final DeferredHolder<Item, Item> STONE_MACE=ITEMS.register("stone_mace",()->new org.slavicmyths.combat.MaceItem(Tiers.STONE,7,.85F,.3F,.4F,properties()));
    public static final DeferredHolder<Item, Item> SILVER_MACE=ITEMS.register("silver_mace",()->new org.slavicmyths.combat.MaceItem(ModGear.SILVER,7,1F,.3F,.4F,properties()));
    public static final DeferredHolder<Item, Item> FLAIL=ITEMS.register("flail",()->new org.slavicmyths.combat.FlailItem(properties()));
    public static final DeferredHolder<Item, Item> GAMBESON=ITEMS.register("gambeson",()->new ArmorItem(ModGear.GAMBESON,ArmorItem.Type.CHESTPLATE,properties().durability(192)));
    public static final DeferredHolder<Item, Item> PLATE_CUIRASS=ITEMS.register("plate_cuirass",()->new org.slavicmyths.combat.CombatEquipment.PlateArmor(properties()));
    public static final DeferredHolder<Item, Item> BANDIT_FIGHTER_EGG=egg("bandit_fighter_spawn_egg",ModEntities.BANDIT_FIGHTER,0x574434,0xb39978);
    public static final DeferredHolder<Item, Item> BANDIT_ARCHER_EGG=egg("bandit_archer_spawn_egg",ModEntities.BANDIT_ARCHER,0x485343,0xb39978);
    public static final DeferredHolder<Item, Item> BANDIT_HEAVY_EGG=egg("bandit_heavy_spawn_egg",ModEntities.BANDIT_HEAVY,0x474a49,0xb39978);
    public static final DeferredHolder<Item, Item> BANDIT_SENIOR_EGG=egg("bandit_senior_spawn_egg",ModEntities.BANDIT_SENIOR,0x66503b,0xb39978);
    public static final DeferredHolder<Item, Item> ATAMAN_EGG=egg("ataman_spawn_egg",ModEntities.ATAMAN,0x653d36,0xa5a199);
    public static final DeferredHolder<Item, Item> NIGHTINGALE_MARK=ITEMS.register("nightingale_mark",()->new Item(properties().stacksTo(1).rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> NIGHTINGALE_LOCK=ITEMS.register("nightingale_lock",()->new Item(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> NIGHTINGALE_DAGGER=ITEMS.register("nightingale_dagger",()->new org.slavicmyths.bandit.NightingaleDagger(properties().rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> NIGHTINGALE_WHISTLE=ITEMS.register("nightingale_whistle",()->new org.slavicmyths.bandit.NightingaleWhistle(properties().stacksTo(1).rarity(Rarity.RARE),false));
    public static final DeferredHolder<Item, Item> BANDIT_HORN=ITEMS.register("bandit_horn",()->new org.slavicmyths.bandit.NightingaleWhistle(properties().stacksTo(1),true));
    public static final DeferredHolder<Item, Item> BURIAL_LOG_COFFIN=ITEMS.register("burial_log_coffin",()->new BlockItem(ModBlocks.BURIAL_COFFIN.get(),properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_CAROLINGIAN_SWORD=ITEMS.register("ancient_carolingian_sword",()->new org.slavicmyths.kurgan.BurialWeapon(false,true,properties()));
    public static final DeferredHolder<Item, Item> RESTORED_CAROLINGIAN_SWORD=ITEMS.register("restored_carolingian_sword",()->new org.slavicmyths.kurgan.BurialWeapon(false,false,properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_SPEAR=ITEMS.register("ancient_spear",()->new org.slavicmyths.kurgan.BurialWeapon(true,true,properties()));
    public static final DeferredHolder<Item, Item> RESTORED_SPEAR=ITEMS.register("restored_spear",()->new org.slavicmyths.kurgan.BurialWeapon(true,false,properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_CHEKAN=ITEMS.register("ancient_chekan",()->new org.slavicmyths.combat.MaceItem(Tiers.STONE,5,1.2F,.22F,.12F,properties().durability(90)));
    public static final DeferredHolder<Item, Item> CHEKAN=ITEMS.register("chekan",()->new org.slavicmyths.combat.MaceItem(Tiers.IRON,6,1.3F,.3F,.15F,properties().durability(400)));
    public static final DeferredHolder<Item, Item> LUNULA=ITEMS.register("lunula",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"necklace"));
    public static final DeferredHolder<Item, Item> GRIVNA=ITEMS.register("grivna",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"necklace"));
    public static final DeferredHolder<Item, Item> GRAVE_WARD=ITEMS.register("grave_ward",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.UNCOMMON),"charm"));
    public static final DeferredHolder<Item, Item> ANCIENT_FIBULA=ITEMS.register("ancient_fibula",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_COMB=ITEMS.register("ancient_comb",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_BEADS=ITEMS.register("ancient_beads",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> OLD_BUCKLE=ITEMS.register("old_buckle",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> POTTERY_FRAGMENT=ITEMS.register("pottery_fragment",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> OLD_ARROWHEAD=ITEMS.register("old_arrowhead",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> UPYR_SPAWN_EGG=egg("upyr_spawn_egg",ModEntities.UPYR,0xE4D8CE,0x8D1717);
    public static final DeferredHolder<Item, Item> NAV_SPAWN_EGG=egg("nav_spawn_egg",ModEntities.NAV,0xCDE7FF,0x5FA7FF);
    public static final DeferredHolder<Item, Item> DRUZHINNIK_SPAWN_EGG=egg("kurgan_druzhinnik_spawn_egg",ModEntities.DRUZHINNIK,0x7B7A80,0xB22E2E);
    public static final DeferredHolder<Item, Item> VOEVODA_SPAWN_EGG=egg("kurgan_voevoda_spawn_egg",ModEntities.VOEVODA,0x8A2327,0xD6A451);
    public static final DeferredHolder<Item, Item> VOLKHV_SPAWN_EGG=egg("buried_volkhv_spawn_egg",ModEntities.VOLKHV,0x2F2D38,0xB39A63);
    public static final DeferredHolder<Item, Item> PRINCE_SPAWN_EGG=egg("unresting_prince_spawn_egg",ModEntities.PRINCE,0x9F1E28,0xD9B14E);
    public static final DeferredHolder<Item, Item> UPYR_FANG=ITEMS.register("upyr_fang",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> GRAVE_CLOTH_SCRAP=ITEMS.register("grave_cloth_scrap",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> NAV_ESSENCE=ITEMS.register("nav_essence",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> TORN_BURIAL_RIBBON=ITEMS.register("torn_burial_ribbon",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> SHIELD_BOSS_FRAGMENT=ITEMS.register("shield_boss_fragment",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> DRUZHINNIK_BLADE_FRAGMENT=ITEMS.register("druzhinnik_blade_fragment",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> VOEVODA_INSIGNIA=ITEMS.register("voevoda_insignia",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> VOLKHV_AMULET=ITEMS.register("volkhv_amulet",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> PRINCELY_SEAL=ITEMS.register("princely_seal",()->new Item(properties()));
    public static final DeferredHolder<Item, Item> OVINNAYA_ZOLA=ITEMS.register("ovinnaya_zola",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(64),org.slavicmyths.hunt.HuntItems.Role.ASH));
    public static final DeferredHolder<Item, Item> ISKRA_OVINNIKA=ITEMS.register("iskra_ovinnika",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.SPARK));
    public static final DeferredHolder<Item, Item> KLYK_VOLKOLAKA=ITEMS.register("klyk_volkolaka",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> NOCHNOY_KOGOT=ITEMS.register("nochnoy_kogot",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.CLAW));
    public static final DeferredHolder<Item, Item> OBEREG_OHOTNIKA=ITEMS.register("obereg_ohotnika",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(1).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.DETECTOR));
    public static final DeferredHolder<Item, Item> OHOTNICHIY_ROG=ITEMS.register("ohotnichiy_rog",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(1),org.slavicmyths.hunt.HuntItems.Role.HORN));
    public static final DeferredHolder<Item, Item> MESHOCHEK_TROFEEV=ITEMS.register("meshochek_trofeev",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(1),org.slavicmyths.hunt.HuntItems.Role.POUCH));
    public static final DeferredHolder<Item, Item> PUSTOY_RITUALNY_SOSUD=ITEMS.register("pustoy_ritualny_sosud",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.VESSEL));
    public static final DeferredHolder<Item, Item> ZOLNY_OBEREG=ITEMS.register("zolny_obereg",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"necklace"));
    public static final DeferredHolder<Item, Item> VOLCHIY_POYAS=ITEMS.register("volchiy_poyas",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"belt"));
    public static final DeferredHolder<Item, Item> PYLAYUSCHAYA_CHESHUYA=ITEMS.register("pylayuschaya_cheshuya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32),org.slavicmyths.hunt.HuntItems.Role.ASH));
    public static final DeferredHolder<Item, Item> OGNENNOE_PERO=ITEMS.register("ognennoe_pero",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.SPARK));
    public static final DeferredHolder<Item, Item> OBEREG_PADAYUSCHEY_ZVEZDY=ITEMS.register("obereg_padayuschey_zvezdy",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"necklace"));
    public static final DeferredHolder<Item, Item> UZEL_PODVEYA=ITEMS.register("uzel_podveya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> VIHREVAYA_NIT=ITEMS.register("vihrevaya_nit",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32),org.slavicmyths.hunt.HuntItems.Role.CLAW));
    public static final DeferredHolder<Item, Item> VETROVOY_UZEL=ITEMS.register("vetrovoy_uzel",()->new org.slavicmyths.hunt.WindKnotItem(properties().stacksTo(1).rarity(Rarity.RARE)));
    public static final DeferredHolder<Item, Item> SOSUD_OGNENNOGO_DYHANIYA=ITEMS.register("sosud_ognennogo_dyhaniya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.VESSEL));
    public static final DeferredHolder<Item, Item> SOSUD_PODVEYA=ITEMS.register("sosud_podveya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.VESSEL));
    public static final DeferredHolder<Item, Item> FIRE_SERPENT_SPAWN_EGG=egg("fire_serpent_spawn_egg",ModEntities.FIRE_SERPENT,0x29191A,0xF04B16);
    public static final DeferredHolder<Item, Item> PODVEY_SPAWN_EGG=egg("podvey_spawn_egg",ModEntities.PODVEY,0x56626F,0xC5E4F1);
    public static final DeferredHolder<Item, Item> VOLKOLAK_SPAWN_EGG=egg("volkolak_spawn_egg",ModEntities.VOLKOLAK,0x3D3A38,0x9A1F27);
    public static final DeferredHolder<Item, Item> OKO_LIKHA=ITEMS.register("oko_likha",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(1).rarity(Rarity.EPIC),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> NIT_DURNOY_DOLI=ITEMS.register("nit_durnoy_doli",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> KOST_LIKHA=ITEMS.register("kost_likha",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> US_TUGARINA=ITEMS.register("us_tugarina",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(1).rarity(Rarity.EPIC),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> TUGARINOVA_KOZHA=ITEMS.register("tugarinova_kozha",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> ZMEINAYA_PRYAZHKA=ITEMS.register("zmeinaya_pryazhka",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> NABOYKA_TUGARINA=ITEMS.register("naboyka_tugarina",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final DeferredHolder<Item, Item> UZEL_DURNOY_DOLI=ITEMS.register("uzel_durnoy_doli",()->new org.slavicmyths.hunt.BossRitualItem(properties().stacksTo(1).rarity(Rarity.EPIC),org.slavicmyths.hunt.BossKind.LIKHO));
    public static final DeferredHolder<Item, Item> STEPNOY_SHTANDART=ITEMS.register("stepnoy_shtandart",()->new org.slavicmyths.hunt.BossRitualItem(properties().stacksTo(1).rarity(Rarity.EPIC),org.slavicmyths.hunt.BossKind.TUGARIN));
    public static final DeferredHolder<Item, Item> ODNOGLAZYY_OBEREG=ITEMS.register("odnoglazyy_obereg",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.EPIC),"necklace"));
    public static final DeferredHolder<Item, Item> POYAS_TUGARINA=ITEMS.register("poyas_tugarina",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.EPIC),"belt"));
    public static final DeferredHolder<Item, Item> LIKHO_ONE_EYED_SPAWN_EGG=egg("likho_one_eyed_spawn_egg",ModEntities.LIKHO_ONE_EYED,0x1E1B1D,0xC7A77A);
    public static final DeferredHolder<Item, Item> TUGARIN_ZMEY_SPAWN_EGG=egg("tugarin_zmey_spawn_egg",ModEntities.TUGARIN_ZMEY,0x8F3D2F,0xC99B45);
    private ModItems() { }
 public static final DeferredHolder<Item, Item> PUTEVODNY_KLUBOK=ITEMS.register("putevodny_klubok",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(1).rarity(Rarity.RARE),org.slavicmyths.yaga.YagaUtilityItem.Kind.THREAD));
 public static final DeferredHolder<Item, Item> SVYAZKA_TRAV_YAGI=ITEMS.register("svyazka_trav_yagi",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(32),org.slavicmyths.yaga.YagaUtilityItem.Kind.HERBS));
 public static final DeferredHolder<Item, Item> OTVAR_OCHISHCHENIYA=ITEMS.register("otvar_ochishcheniya",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.CLEANSE));
 public static final DeferredHolder<Item, Item> LETUCHAYA_MAZ=ITEMS.register("letuchaya_maz",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.SALVE));
 public static final DeferredHolder<Item, Item> OTVAR_LESNOY_ZORKOSTI=ITEMS.register("otvar_lesnoy_zorkosti",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.SIGHT));
 public static final DeferredHolder<Item, Item> YAGIN_NASTOY_STOYKOSTI=ITEMS.register("yagin_nastoy_stoykosti",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.RESIST));
 public static final DeferredHolder<Item, Item> OTVAR_BODROSTI=ITEMS.register("otvar_bodrosti",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.VIGOR));
 public static final DeferredHolder<Item, Item> LESNOY_NASTOY_VOSSTANOVLENIYA=ITEMS.register("lesnoy_nastoy_vosstanovleniya",()->new org.slavicmyths.yaga.YagaUtilityItem(properties().stacksTo(16),org.slavicmyths.yaga.YagaUtilityItem.Kind.RESTORE));
 public static final DeferredHolder<Item, Item> BABA_YAGA_SPAWN_EGG=ITEMS.register("baba_yaga_spawn_egg",()->new org.slavicmyths.yaga.YagaSpawnEgg(properties()));
}
