package org.slavicmyths.registry;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import org.slavicmyths.SlavicMyths;

public final class ModSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, SlavicMyths.MOD_ID);
    public static final RegistryObject<SoundEvent> BANDIT_IDLE=sound("bandit_idle");
    public static final RegistryObject<SoundEvent> BANDIT_ALERT=sound("bandit_alert");
    public static final RegistryObject<SoundEvent> BANDIT_ATTACK=sound("bandit_attack");
    public static final RegistryObject<SoundEvent> BANDIT_HURT=sound("bandit_hurt");
    public static final RegistryObject<SoundEvent> BANDIT_DEATH=sound("bandit_death");
    public static final RegistryObject<SoundEvent> BANDIT_COMMAND=sound("bandit_command");
    public static final RegistryObject<SoundEvent> BANDIT_HEAVY=sound("bandit_heavy");
    public static final RegistryObject<SoundEvent> DOMOVOY_AMBIENT = sound("domovoy_ambient");
    public static final RegistryObject<SoundEvent> DOMOVOY_HURT = sound("domovoy_hurt");
    public static final RegistryObject<SoundEvent> DOMOVOY_DEATH = sound("domovoy_death");
    public static final RegistryObject<SoundEvent> LESHY_AMBIENT = sound("leshy_ambient");
    public static final RegistryObject<SoundEvent> LESHY_HURT = sound("leshy_hurt");
    public static final RegistryObject<SoundEvent> LESHY_DEATH = sound("leshy_death");
    public static final RegistryObject<SoundEvent> LESHY_ANGRY = sound("leshy_angry");
    public static final RegistryObject<SoundEvent> KIKIMORA_AMBIENT = sound("kikimora_ambient");
    public static final RegistryObject<SoundEvent> KIKIMORA_HURT = sound("kikimora_hurt");
    public static final RegistryObject<SoundEvent> KIKIMORA_DEATH = sound("kikimora_death");
    public static final RegistryObject<SoundEvent> KIKIMORA_ANGRY = sound("kikimora_angry");
    public static final RegistryObject<SoundEvent> KIKIMORA_POWER = sound("kikimora_power");
    public static final RegistryObject<SoundEvent> POLUDNITSA_AMBIENT = sound("poludnitsa_ambient");
    public static final RegistryObject<SoundEvent> POLUDNITSA_HURT = sound("poludnitsa_hurt");
    public static final RegistryObject<SoundEvent> POLUDNITSA_DEATH = sound("poludnitsa_death");
    public static final RegistryObject<SoundEvent> POLUDNITSA_ANGRY = sound("poludnitsa_angry");
    public static final RegistryObject<SoundEvent> POLUDNITSA_POWER = sound("poludnitsa_power");
    public static final RegistryObject<SoundEvent> POLEVIK_AMBIENT = sound("polevik_ambient");
    public static final RegistryObject<SoundEvent> POLEVIK_HURT = sound("polevik_hurt");
    public static final RegistryObject<SoundEvent> POLEVIK_DEATH = sound("polevik_death");
    public static final RegistryObject<SoundEvent> POLEVIK_ANGRY = sound("polevik_angry");
    public static final RegistryObject<SoundEvent> POLEVIK_POWER = sound("polevik_power");
    public static final RegistryObject<SoundEvent> BANNIK_AMBIENT = sound("bannik_ambient");
    public static final RegistryObject<SoundEvent> BANNIK_HURT = sound("bannik_hurt");
    public static final RegistryObject<SoundEvent> BANNIK_DEATH = sound("bannik_death");
    public static final RegistryObject<SoundEvent> BANNIK_ANGRY = sound("bannik_angry");
    public static final RegistryObject<SoundEvent> BANNIK_POWER = sound("bannik_power");
    public static final RegistryObject<SoundEvent> IGOSHA_AMBIENT = sound("igosha_ambient");
    public static final RegistryObject<SoundEvent> IGOSHA_HURT = sound("igosha_hurt");
    public static final RegistryObject<SoundEvent> IGOSHA_DEATH = sound("igosha_death");
    public static final RegistryObject<SoundEvent> IGOSHA_ANGRY = sound("igosha_angry");
    public static final RegistryObject<SoundEvent> IGOSHA_POWER = sound("igosha_power");
    public static final RegistryObject<SoundEvent> OVINNIK_AMBIENT = sound("ovinnik_ambient");
    public static final RegistryObject<SoundEvent> OVINNIK_HURT = sound("ovinnik_hurt");
    public static final RegistryObject<SoundEvent> OVINNIK_DEATH = sound("ovinnik_death");
    public static final RegistryObject<SoundEvent> OVINNIK_ANGRY = sound("ovinnik_angry");
    public static final RegistryObject<SoundEvent> OVINNIK_POWER = sound("ovinnik_power");
    public static final RegistryObject<SoundEvent> POLUDNITSA_NOTICE = sound("poludnitsa_notice");
    public static final RegistryObject<SoundEvent> POLUDNITSA_TRANSFORM = sound("poludnitsa_transform");
    public static final RegistryObject<SoundEvent> POLUDNITSA_ATTACK = sound("poludnitsa_attack");
    public static final RegistryObject<SoundEvent> POLEVIK_STEP = sound("polevik_step");
    public static final RegistryObject<SoundEvent> BANNIK_STEP = sound("bannik_step");
    public static final RegistryObject<SoundEvent> BANNIK_ATTACK = sound("bannik_attack");
    public static final RegistryObject<SoundEvent> BANNIK_STEAM = sound("bannik_steam");
    public static final RegistryObject<SoundEvent> KIKIMORA_NOTICE = sound("kikimora_notice");
    public static final RegistryObject<SoundEvent> KIKIMORA_LAUGH = sound("kikimora_laugh");
    public static final RegistryObject<SoundEvent> KIKIMORA_ATTACK = sound("kikimora_attack");
    public static final RegistryObject<SoundEvent> KIKIMORA_STEP = sound("kikimora_step");
    static {
        for(String animal:new String[]{"bear","cub","wolf","boar","stag","doe"})
            for(String event:new String[]{"ambient","hurt","death","alert","roar","attack","impact"}) sound(animal+"_"+event);
    }
    public static final RegistryObject<SoundEvent> UPYR_AMBIENT=sound("upyr_ambient");
    public static final RegistryObject<SoundEvent> UPYR_HURT=sound("upyr_hurt");
    public static final RegistryObject<SoundEvent> UPYR_DEATH=sound("upyr_death");
    public static final RegistryObject<SoundEvent> UPYR_ATTACK=sound("upyr_attack");
    public static final RegistryObject<SoundEvent> UPYR_LEAP=sound("upyr_leap");
    public static final RegistryObject<SoundEvent> UPYR_BITE=sound("upyr_bite");
    public static final RegistryObject<SoundEvent> UPYR_STEP=sound("upyr_step");
    public static final RegistryObject<SoundEvent> NAV_AMBIENT=sound("nav_ambient");
    public static final RegistryObject<SoundEvent> NAV_HURT=sound("nav_hurt");
    public static final RegistryObject<SoundEvent> NAV_DEATH=sound("nav_death");
    public static final RegistryObject<SoundEvent> NAV_ATTACK=sound("nav_attack");
    public static final RegistryObject<SoundEvent> NAV_SHIFT=sound("nav_shift");
    public static final RegistryObject<SoundEvent> NAV_SPECTRAL_APPEAR=sound("nav_spectral_appear");
    public static final RegistryObject<SoundEvent> NAV_STEP=sound("nav_step");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_AMBIENT=sound("kurgan_druzhinnik_ambient");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_HURT=sound("kurgan_druzhinnik_hurt");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_DEATH=sound("kurgan_druzhinnik_death");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_SWORD_ATTACK=sound("kurgan_druzhinnik_sword_attack");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_SHIELD_BLOCK=sound("kurgan_druzhinnik_shield_block");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_SHIELD_BASH=sound("kurgan_druzhinnik_shield_bash");
    public static final RegistryObject<SoundEvent> KURGAN_DRUZHINNIK_STEP=sound("kurgan_druzhinnik_step");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_AMBIENT=sound("kurgan_voevoda_ambient");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_HURT=sound("kurgan_voevoda_hurt");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_DEATH=sound("kurgan_voevoda_death");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_AXE_ATTACK=sound("kurgan_voevoda_axe_attack");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_SHIELD_CHARGE=sound("kurgan_voevoda_shield_charge");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_SHIELD_IMPACT=sound("kurgan_voevoda_shield_impact");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_PHASE_SHIFT=sound("kurgan_voevoda_phase_shift");
    public static final RegistryObject<SoundEvent> KURGAN_VOEVODA_STEP=sound("kurgan_voevoda_step");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_AMBIENT=sound("buried_volkhv_ambient");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_HURT=sound("buried_volkhv_hurt");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_DEATH=sound("buried_volkhv_death");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_CAST_BASIC=sound("buried_volkhv_cast_basic");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_CAST_CLONES=sound("buried_volkhv_cast_clones");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_CAST_GROUND_SEAL=sound("buried_volkhv_cast_ground_seal");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_SUMMON=sound("buried_volkhv_summon");
    public static final RegistryObject<SoundEvent> BURIED_VOLKHV_STEP=sound("buried_volkhv_step");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_AMBIENT=sound("unresting_prince_ambient");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_HURT=sound("unresting_prince_hurt");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_DEATH=sound("unresting_prince_death");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_COMBO=sound("unresting_prince_combo");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_SUMMON=sound("unresting_prince_summon");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_PHASE_SHIFT=sound("unresting_prince_phase_shift");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_HEAVY_STRIKE=sound("unresting_prince_heavy_strike");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_GRAB=sound("unresting_prince_grab");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_SHIELD_BLOCK=sound("unresting_prince_shield_block");
    public static final RegistryObject<SoundEvent> UNRESTING_PRINCE_STEP=sound("unresting_prince_step");
    private static RegistryObject<SoundEvent> sound(String id) {
        return SOUNDS.register(id, () -> new SoundEvent(new ResourceLocation(SlavicMyths.MOD_ID, id)));
    }
    public static final RegistryObject<SoundEvent> GUSLI_LOOP = sound("gusli_loop");
    public static final RegistryObject<SoundEvent> VODYANOY_AMBIENT=sound("vodyanoy_ambient"),VODYANOY_ANGRY=sound("vodyanoy_angry"),VODYANOY_HURT=sound("vodyanoy_hurt"),VODYANOY_DEATH=sound("vodyanoy_death"),RUSALKA_AMBIENT=sound("rusalka_ambient"),RUSALKA_ANGRY=sound("rusalka_angry"),RUSALKA_HURT=sound("rusalka_hurt"),RUSALKA_DEATH=sound("rusalka_death"),RUSALKA_SONG=sound("rusalka_song");
    public static final RegistryObject<SoundEvent> ELDER_IDLE=sound("elder_idle"),ELDER_HURT=sound("elder_hurt"),ELDER_ATTACK=sound("elder_attack"),ELDER_HEAVY=sound("elder_heavy"),ELDER_DASH=sound("elder_dash"),ELDER_WAVE=sound("elder_wave"),ELDER_PULL=sound("elder_pull"),ELDER_PHASE=sound("elder_phase"),ELDER_DEATH=sound("elder_death");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_IDLE=sound("nightingale_idle");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_NOTICE=sound("nightingale_notice");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_HURT=sound("nightingale_hurt");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_BREATH=sound("nightingale_breath");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_INHALE=sound("nightingale_inhale");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_DEEP_INHALE=sound("nightingale_deep_inhale");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_WHISTLE=sound("nightingale_whistle");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_DESTRUCTIVE=sound("nightingale_destructive");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_WAVE=sound("nightingale_wave");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_MELEE=sound("nightingale_melee");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_VOICE=sound("nightingale_voice");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_DEATH=sound("nightingale_death");
    public static final RegistryObject<SoundEvent> NIGHTINGALE_HORN=sound("nightingale_horn");
    public static final RegistryObject<SoundEvent> COFFIN_OPEN=sound("coffin_open"),COFFIN_CLOSE=sound("coffin_close");
    public static final RegistryObject<SoundEvent> HUNT_HORN=sound("hunt_horn");
    private ModSounds() { }
 public static final RegistryObject<SoundEvent> YAGA_AMBIENT=sound("yaga_ambient");
 public static final RegistryObject<SoundEvent> YAGA_TALK=sound("yaga_talk");
 public static final RegistryObject<SoundEvent> YAGA_WARN=sound("yaga_warn");
 public static final RegistryObject<SoundEvent> YAGA_STIR=sound("yaga_stir");
 public static final RegistryObject<SoundEvent> YAGA_OPEN=sound("yaga_open");
 public static final RegistryObject<SoundEvent> YAGA_CLOSE=sound("yaga_close");
 public static final RegistryObject<SoundEvent> YAGA_HURT=sound("yaga_hurt");
 public static final RegistryObject<SoundEvent> YAGA_STEP=sound("yaga_step");
 public static final RegistryObject<SoundEvent> YAGA_HUT_CREAK=sound("yaga_hut_creak");
 public static final RegistryObject<SoundEvent> YAGA_HUT_STEP=sound("yaga_hut_step");
}
