package org.slavicmyths.brewing;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket;
import net.minecraft.world.*;
import net.minecraft.world.entity.player.*;
import net.minecraft.world.inventory.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import org.slavicmyths.kitchen.*;
public final class BrewTile extends BlockEntity implements Container,MenuProvider {
 public final NonNullList<ItemStack> items=NonNullList.withSize(9,ItemStack.EMPTY);public final String kind;public int progress,total,pressActions,servings;public String beverage="",quality="ready",mode="";public ItemStack pending=ItemStack.EMPTY;private boolean dirty=true;
 public BrewTile(BlockPos p,BlockState s){super(Brewing.TYPE.get(),p,s);kind=((BrewBlock)s.getBlock()).kind;}
 public net.minecraft.world.phys.AABB getRenderBoundingBox(){return new net.minecraft.world.phys.AABB(worldPosition).inflate(.7);}
 public int getContainerSize(){return 9;}public boolean isEmpty(){return items.stream().allMatch(ItemStack::isEmpty);}public ItemStack getItem(int i){return items.get(i);}public ItemStack removeItem(int i,int n){ItemStack r=ContainerHelper.removeItem(items,i,n);setChanged();return r;}public ItemStack removeItemNoUpdate(int i){return ContainerHelper.takeItem(items,i);}public void setItem(int i,ItemStack s){items.set(i,s);s.limitSize(s.getMaxStackSize());setChanged();}public void clearContent(){items.clear();setChanged();}
 public boolean stillValid(Player p){return p.isAlive()&&!isRemoved()&&p.level().getBlockEntity(worldPosition)==this&&p.distanceToSqr(worldPosition.getCenter())<=64;}
 public boolean canPlaceItem(int i,ItemStack s){return kind.equals("fermentation_vat")&&total==0&&(i<4||i==8);}public boolean canTakeItem(Container c,int i,ItemStack s){return total==0||i>=4&&i<8;}
 public Component getDisplayName(){return Component.translatable("block.slavicmyths."+kind);}
 public AbstractContainerMenu createMenu(int id,Inventory inv,Player p){return new org.slavicmyths.brewing.VatMenu(id,inv,worldPosition,this,this);}

 public void setChanged(){super.setChanged();dirty=true;if(level!=null&&!level.isClientSide){int v=kind.equals("fruit_press")?pressActions:kind.equals("small_keg")?(servings+1)/2:total==0?0:mode.equals("MALTING")?1:mode.equals("INFUSION")?2:mode.equals("WORT")?3:4;if(getBlockState().getValue(BrewBlock.VISUAL)!=v)level.setBlock(worldPosition,getBlockState().setValue(BrewBlock.VISUAL,v),2);level.sendBlockUpdated(worldPosition,getBlockState(),getBlockState(),2);}}
 private void saveProgress(){super.setChanged();}
 private static boolean insert(ItemStack[] slots,ItemStack s){s=s.copy();for(int i=0;i<slots.length;i++){if(slots[i].isEmpty()){slots[i]=s;return true;}if(ItemStack.isSameItemSameComponents(slots[i],s)){int n=Math.min(s.getCount(),slots[i].getMaxStackSize()-slots[i].getCount());slots[i].grow(n);s.shrink(n);if(s.isEmpty())return true;}}return false;}
 public static void tick(BrewTile t){if(t.level==null||t.level.isClientSide)return;
  if(t.total>0){t.progress++;t.saveProgress();if(t.progress%100==0&&t.level instanceof net.minecraft.server.level.ServerLevel server)server.sendParticles(net.minecraft.core.particles.ParticleTypes.BUBBLE_POP,t.worldPosition.getX()+.5,t.worldPosition.getY()+.8,t.worldPosition.getZ()+.5,2,.2,.02,.2,.01);if(t.progress>=t.total){ItemStack[] out={t.items.get(6).copy(),t.items.get(7).copy()};if(insert(out,t.pending)){t.items.set(6,out[0]);t.items.set(7,out[1]);t.pending=ItemStack.EMPTY;t.total=t.progress=0;t.mode="";t.setChanged();}}return;}
  if(!t.dirty)return;t.dirty=false;KitchenInput input=new KitchenInput(List.of(t.items.get(0),t.items.get(1),t.items.get(2),t.items.get(3)));
  for(var h:t.level.getRecipeManager().getRecipesFor(VatRecipe.TYPE.get(),input,t.level)){VatRecipe r=h.value();ItemStack catalyst=t.items.get(8);if(!r.catalyst().isEmpty()&&!r.catalyst().test(catalyst)||r.catalyst().isEmpty()&&!catalyst.isEmpty())continue;int[] used=r.allocation(input);ItemStack[] out={t.items.get(6).copy(),t.items.get(7).copy()},rem={t.items.get(4).copy(),t.items.get(5).copy()};if(!insert(out,r.result()))continue;boolean fits=true;for(ItemStack s:r.remainders())if(!insert(rem,s))fits=false;if(!fits)continue;for(int i=0;i<4;i++)t.items.get(i).shrink(used[i]);if(!r.catalyst().isEmpty()&&!r.retainCatalyst())catalyst.shrink(1);t.items.set(4,rem[0]);t.items.set(5,rem[1]);t.pending=r.result().copy();t.total=r.time();t.progress=0;t.mode=r.mode();t.setChanged();t.dirty=false;break;}
 }
 public void interact(Player p,InteractionHand hand){if(p.isSpectator())return;ItemStack held=p.getItemInHand(hand);if(kind.equals("small_keg")){keg(p,held);return;}
  if(held.isEmpty()){if(!items.get(1).isEmpty()){KitchenTile.give(p,removeItem(1,items.get(1).getCount()));return;}if(!items.get(2).isEmpty()){KitchenTile.give(p,removeItem(2,items.get(2).getCount()));return;}if(p.isShiftKeyDown()){KitchenTile.give(p,removeItem(0,items.get(0).getCount()));pressActions=0;setChanged();return;}ItemStack in=items.get(0);if(in.getCount()<4||!items.get(1).isEmpty()||!items.get(2).isEmpty())return;boolean apple=in.is(Items.APPLE),berries=in.is(KitchenII.tag("berries"));if(!apple&&!berries)return;pressActions++;level.playSound(null,worldPosition,net.minecraft.sounds.SoundEvents.WOOD_STEP,net.minecraft.sounds.SoundSource.BLOCKS,.7F,.8F);if(pressActions==3){in.shrink(4);items.set(1,new ItemStack(Brewing.item(apple?"apple_juice_bottle":"berry_mash"),apple?1:2));items.set(2,new ItemStack(Brewing.item("fruit_pomace")));pressActions=0;}setChanged();return;}
  if(!held.is(Items.APPLE)&&!held.is(KitchenII.tag("berries")))return;ItemStack old=items.get(0);if(!old.isEmpty()&&!ItemStack.isSameItemSameComponents(old,held))return;int n=Math.min(held.getCount(),held.getMaxStackSize()-old.getCount());if(n<=0)return;if(old.isEmpty())items.set(0,held.copyWithCount(n));else old.grow(n);held.consume(n,p);setChanged();
 }
 private void keg(Player p,ItemStack held){String id=Brewing.key(held);if(BeverageItem.emptyContainer(held)){int n=id.equals("ceramic_pitcher")&&BeverageItem.pitcherAllowed(beverage)&&servings>=4?4:id.equals("wooden_mug")&&BeverageItem.mugAllowed(beverage)||id.equals("dark_bottle")?1:0;if(n==0||servings<n)return;ItemStack out=BeverageItem.filled(beverage,quality,id,n);held.shrink(1);servings-=n;if(servings==0)beverage="";BeverageItem.obtained(p,out);KitchenTile.give(p,out);setChanged();return;}
  if(!(held.getItem()instanceof BeverageItem)||servings>=8)return;String b=BeverageItem.beverage(held),q=BeverageItem.quality(held);if(id.equals("ceramic_pitcher")||id.equals("wooden_mug")||id.equals("dark_bottle")||!Arrays.asList(Brewing.BEERS).contains(b)&&!BeverageItem.pitcherAllowed(b))return;if(servings>0&&(!beverage.equals(b)||!quality.equals(q))){p.displayClientMessage(Component.translatable("brewing.slavicmyths.no_mix"),true);return;}
  beverage=b;quality=q;servings++;if(id.equals("filled_pitcher")||id.equals("berry_mors_pitcher")){CompoundTag n=BeverageItem.data(held);int left=n.getInt("Servings")-1;if(left<=0){held.shrink(1);KitchenTile.give(p,new ItemStack(Brewing.item("ceramic_pitcher")));}else{n.putInt("Servings",left);BeverageItem.data(held,n);}}else{String empty=BeverageItem.empty(held);held.shrink(1);KitchenTile.give(p,new ItemStack(Brewing.item(empty)));}setChanged();
 }
 public void dropAll(){for(int i=0;i<9;i++){ItemStack s=items.get(i);items.set(i,ItemStack.EMPTY);if(!s.isEmpty())Block.popResource(level,worldPosition,s);}if(!pending.isEmpty()){pending=ItemStack.EMPTY;}while(servings>0){servings--;Block.popResource(level,worldPosition,BeverageItem.filled(beverage,quality,BeverageItem.mugAllowed(beverage)?"wooden_mug":"dark_bottle",1));}beverage="";}
 protected void saveAdditional(CompoundTag n,HolderLookup.Provider p){super.saveAdditional(n,p);ContainerHelper.saveAllItems(n,items,p);n.putInt("Progress",progress);n.putInt("Total",total);n.putInt("PressActions",pressActions);n.putInt("Servings",servings);n.putString("Beverage",beverage);n.putString("Quality",quality);n.putString("Mode",mode);if(!pending.isEmpty())n.put("Pending",pending.save(p));}
 protected void loadAdditional(CompoundTag n,HolderLookup.Provider p){super.loadAdditional(n,p);items.clear();ContainerHelper.loadAllItems(n,items,p);total=Math.max(0,Math.min(12000,n.getInt("Total")));progress=Math.max(0,Math.min(total,n.getInt("Progress")));pressActions=Math.max(0,Math.min(2,n.getInt("PressActions")));servings=Math.max(0,Math.min(8,n.getInt("Servings")));beverage=n.getString("Beverage");quality=n.getString("Quality");mode=n.getString("Mode");pending=ItemStack.parseOptional(p,n.getCompound("Pending"));if(pending.isEmpty())total=0;dirty=true;}
 public CompoundTag getUpdateTag(HolderLookup.Provider p){return saveWithoutMetadata(p);}public ClientboundBlockEntityDataPacket getUpdatePacket(){return ClientboundBlockEntityDataPacket.create(this);}
}
