package org.slavicmyths.verify;

import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.gametest.*;
import net.neoforged.neoforge.common.util.FakePlayerFactory;
import org.slavicmyths.rpg.classes.*;
import org.slavicmyths.rpg.PathData;

@GameTestHolder("slavicmyths_classes") @PrefixGameTestTemplate(false)
public final class ClassGameTests {
    private static final class FixtureConnection extends net.minecraft.network.Connection {
        private final io.netty.channel.embedded.EmbeddedChannel channel=new io.netty.channel.embedded.EmbeddedChannel();
        FixtureConnection(){super(net.minecraft.network.protocol.PacketFlow.SERVERBOUND);}
        @Override public io.netty.channel.Channel channel(){return channel;}
    }
    private static final class FixtureListener extends net.minecraft.server.network.ServerGamePacketListenerImpl {
        int particles;
        FixtureListener(ServerPlayer p){super(p.getServer(),new FixtureConnection(),p,net.minecraft.server.network.CommonListenerCookie.createInitial(p.getGameProfile(),false));}
        @Override public void send(net.minecraft.network.protocol.Packet<?> packet){if(packet instanceof net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket)particles++;}
        @Override public void send(net.minecraft.network.protocol.Packet<?> packet,net.minecraft.network.PacketSendListener listener){}
    }
    private static ServerPlayer player(GameTestHelper t,String name){var w=t.getLevel();var p=new ServerPlayer(w.getServer(),w,new com.mojang.authlib.GameProfile(UUID.randomUUID(),name),ClientInformation.createDefault());p.connection=new FixtureListener(p);p.setNoGravity(true);p.setGameMode(GameType.SURVIVAL);p.moveTo(t.absoluteVec(new net.minecraft.world.phys.Vec3(3,2,3)));return p;}
    private static void train(ServerPlayer p,String base){ClassState.choose(p,base);var d=ClassState.data(p);d.putInt("Level",50);d.putInt("Points",100);for(var s:ClassDefinitions.SKILLS.values())if(s.base().equals(base)&&s.kind()!=ClassDefinitions.Kind.EVOLUTION)d.getCompound("Ranks").putInt(s.id(),3);}
    @GameTest(template="empty") public static void migration(GameTestHelper t){var old=new CompoundTag();old.putString("Main","koldun");var skills=new CompoundTag();skills.putInt("storm_sign",1);skills.putInt("rune_knowledge",1);old.put("Skills",skills);old.putLong("CD_ability_storm_sign",400);var d=ClassState.migrate(old,100);t.assertTrue(d.getString("Base").equals("vedun")&&d.getString("First").equals("koldun"),"Fourth base survived migration");t.assertTrue(d.getCompound("Ranks").getInt("hex")==1&&d.getCompound("Cooldowns").getLong("hex")==400,"Legacy ranks/cooldown lost");t.assertTrue(!old.contains("Class2")&&d.getCompound("LegacyPaths").equals(old),"Migration modified source");var p=player(t,"ClassLegacyRune");PathData.data(p).merge(old);ClassState.data(p);t.assertTrue(org.slavicmyths.rpg.Runes.cost(p,10)==9,"Earned legacy rune discount lost");t.assertTrue(d.getInt("Points")==d.getInt("Level")-2,"Migration duplicated point budget");t.succeed();}
    @GameTest(template="empty") public static void authorityAndProgress(GameTestHelper t){var a=player(t,"ClassAlice");var b=player(t,"ClassBob");t.assertTrue(ClassState.choose(a,"druzhinnik")&&!ClassState.choose(a,"vedun"),"Free class replacement");t.assertTrue(!ClassState.choose(b,"koldun"),"Fourth base accepted");t.assertTrue(!ClassState.equip(a,"lunge",0)&&!ClassRuntime.activate(a,7),"Unlearned/invalid slot accepted");t.assertTrue(ClassState.learn(a,"lunge")&&!ClassState.learn(a,"hex"),"Cross-class purchase");ClassState.awardXp(a,100);t.assertTrue(ClassState.data(a).getInt("Level")==2&&ClassState.data(a).getInt("Points")==1,"Class XP progression");t.assertTrue(a.experienceLevel==0&&ClassState.data(b).getString("Base").isEmpty(),"Vanilla XP/other player modified");t.assertTrue(!ClassState.advance(a,"vityaz"),"Low-level branch accepted");t.assertTrue(!t.getLevel().getServer().getCommands().getDispatcher().getRoot().getChild("smclass").canUse(a.createCommandSourceStack().withPermission(0)),"Non-OP admin commands");t.succeed();}
    @GameTest(template="empty") public static void attributesAndSlots(GameTestHelper t){var p=player(t,"ClassStats");train(p,"druzhinnik");t.assertTrue(ClassState.equip(p,"temper",3),"Passive equip failed");for(int n=0;n<10;n++)ClassState.restore(p);t.assertTrue(p.getMaxHealth()==24,"Health modifier duplicated");t.assertTrue(!ClassState.equip(p,"riposte",0)&&!ClassState.equip(p,"temper",0),"Automatic/passive active slot accepted");ClassState.equip(p,"lunge",0);ClassState.equip(p,"lunge",2);t.assertTrue(ClassState.data(p).getString("Active0").isEmpty(),"Duplicate active slots");ClassState.equip(p,"steadfast",3);t.assertTrue(p.getMaxHealth()==20&&p.getAttributeValue(Attributes.KNOCKBACK_RESISTANCE)<1,"Old passive retained");t.succeed();}
    @GameTest(template="empty") public static void rankAndEvolution(GameTestHelper t){var p=player(t,"ClassRanks");ClassState.choose(p,"druzhinnik");var d=ClassState.data(p);d.putInt("Level",50);d.putInt("Points",100);for(int n=0;n<3;n++)t.assertTrue(ClassState.learn(p,"lunge"),"Rank purchase "+n);t.assertTrue(!ClassState.learn(p,"lunge")&&!ClassState.learn(p,"onslaught"),"Invalid rank/branch evolution");ClassState.advance(p,"vityaz");t.assertTrue(ClassState.learn(p,"onslaught"),"Evolution unavailable");t.assertTrue(ClassBalance.range(d,"lunge",3)>3&&ClassBalance.power(d,"lunge",3)>.75,"Evolution has no effect");for(var s:ClassDefinitions.SKILLS.values())for(int r=1;r<=s.maxRank();r++)t.assertTrue(s.cooldown(r)>=0&&s.duration(r)>=0&&Double.isFinite(s.power(r)),"Invalid balance "+s.id());t.succeed();}
    @GameTest(template="empty") public static void raycastAndEquipment(GameTestHelper t){var p=player(t,"ClassRay");train(p,"vedun");ClassState.equip(p,"binding_sign",0);p.setYRot(0);p.setXRot(0);var zombie=EntityType.ZOMBIE.create(t.getLevel());zombie.setNoAi(true);zombie.moveTo(p.getX(),p.getY(),p.getZ()+5);t.getLevel().addFreshEntity(zombie);t.assertTrue(ClassRuntime.target(p,12)==zombie,"Ray missed visible target");t.setBlock(new BlockPos(3,3,5),Blocks.STONE);t.assertTrue(ClassRuntime.target(p,12)==null&&!ClassRuntime.activate(p,0),"Wall ignored");t.assertTrue(ClassState.remaining(p,"binding_sign")==0,"Failed cast consumed cooldown");t.setBlock(new BlockPos(3,3,5),Blocks.AIR);t.assertTrue(ClassRuntime.activate(p,0)&&!ClassRuntime.activate(p,0),"Cooldown missing");t.assertTrue(zombie.hasEffect(org.slavicmyths.registry.ModEffects.CLASS_ROOT),"Ordinary mob not rooted");var fighter=player(t,"ClassNoWeapon");train(fighter,"druzhinnik");ClassState.equip(fighter,"flurry",0);t.assertTrue(!ClassRuntime.activate(fighter,0),"Empty hand accepted");fighter.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_SWORD));t.assertTrue(ClassRuntime.activate(fighter,0)&&fighter.getAttributeValue(Attributes.ATTACK_SPEED)>4,"Real attack speed unchanged");zombie.discard();t.succeed();}
    @GameTest(template="empty") public static void controlAndCleanse(GameTestHelper t){var p=player(t,"ClassSoft");t.assertTrue(ClassControl.apply(p,100,false)&&!p.hasEffect(org.slavicmyths.registry.ModEffects.CLASS_ROOT),"PvP hard lock");t.assertTrue(!ClassControl.apply(p,100,false),"Control spam ignored recovery window");train(p,"vedun");ClassState.equip(p,"cleanse",0);p.addEffect(new net.minecraft.world.effect.MobEffectInstance(org.slavicmyths.registry.ModEffects.CURSE,400,0));p.addEffect(new net.minecraft.world.effect.MobEffectInstance(net.minecraft.world.effect.MobEffects.POISON,400,0));t.assertTrue(ClassRuntime.activate(p,0)&&p.hasEffect(org.slavicmyths.registry.ModEffects.CURSE)&&!p.hasEffect(net.minecraft.world.effect.MobEffects.POISON),"Protected curse cleansed");t.succeed();}
    @GameTest(template="empty",timeoutTicks=200) public static void everyActiveRank(GameTestHelper t){int casts=0;
        for(String base:ClassDefinitions.BASES){var p=player(t,"ClassMatrix");train(p,base);for(var s:ClassDefinitions.SKILLS.values())if(s.base().equals(base)&&s.kind()==ClassDefinitions.Kind.ACTIVE)for(int rank=1;rank<=3;rank++){
            p.moveTo(t.absoluteVec(new net.minecraft.world.phys.Vec3(3,2,3)));p.setYRot(0);p.setXRot(0);p.setOnGround(true);p.setDeltaMovement(net.minecraft.world.phys.Vec3.ZERO);p.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_SWORD));p.setItemInHand(net.minecraft.world.InteractionHand.OFF_HAND,new ItemStack(Items.SHIELD));
            var d=ClassState.data(p);d.getCompound("Ranks").putInt(s.id(),rank);d.getCompound("Cooldowns").remove(s.id());ClassState.equip(p,s.id(),0);var mob=EntityType.ZOMBIE.create(t.getLevel());mob.setNoAi(true);mob.moveTo(p.getX(),p.getY(),p.getZ()+2);t.getLevel().addFreshEntity(mob);
            if(s.id().equals("cleanse"))p.addEffect(new net.minecraft.world.effect.MobEffectInstance(net.minecraft.world.effect.MobEffects.POISON,100,0));
            if(s.id().equals("ward")){p.removeEffect(net.minecraft.world.effect.MobEffects.ABSORPTION);p.setAbsorptionAmount(0);}
            if(s.id().equals("keen_eye")){p.getPersistentData().putUUID("ClassLastTarget",mob.getUUID());p.getPersistentData().putString("ClassLastTargetDimension",p.level().dimension().location().toString());p.getPersistentData().putLong("ClassLastTargetTick",ClassState.now(p));}
            t.assertTrue(ClassRuntime.activate(p,0),"Cast rejected "+s.id()+" rank "+rank);t.assertTrue(ClassState.remaining(p,s.id())==ClassBalance.cooldown(d,s.id(),rank),"Incorrect rank cooldown "+s.id());if(s.id().equals("ward"))t.assertTrue(Math.abs(p.getAbsorptionAmount()-ClassBalance.power(d,s.id(),rank))<.001,"Ward pool rounded to vanilla hearts "+rank);t.assertTrue(!ClassRuntime.activate(p,0),"Immediate duplicate cast "+s.id());mob.discard();casts++;
        }}System.out.println("CLASS_ACTIVE_RANK_MATRIX_PASS casts="+casts);t.succeed();}
    @GameTest(template="empty") public static void wireAndPlayerIsolation(GameTestHelper t){var a=player(t,"ClassWireA");var b=player(t,"ClassWireB");train(a,"razboinik");train(b,"vedun");var buffer=new net.minecraft.network.FriendlyByteBuf(io.netty.buffer.Unpooled.buffer());try{var intent=new ClassNetwork.Intent(2,"dash",1);ClassNetwork.Intent.CODEC.encode(buffer,intent);t.assertTrue(ClassNetwork.Intent.CODEC.decode(buffer).equals(intent),"Intent codec changed");t.assertTrue(ClassNetwork.handle(a,intent),"Own learned slot rejected");t.assertTrue(!ClassNetwork.handle(b,intent)&&ClassState.data(b).getString("Active1").isEmpty(),"Cross-player/class intent accepted");t.assertTrue(!ClassNetwork.handle(a,new ClassNetwork.Intent(99,"",0)),"Unknown action accepted");}finally{buffer.release();}t.succeed();}
    @GameTest(template="empty") public static void nativePlayerStorageRestart(GameTestHelper t){String phase=System.getProperty("slavicmyths.classRestartPhase","none");var w=t.getLevel();var p=new ServerPlayer(w.getServer(),w,new com.mojang.authlib.GameProfile(UUID.fromString("48f9834f-ced7-46e4-b8ad-f87d6d131131"),"ClassRestart"),ClientInformation.createDefault());p.connection=new FixtureListener(p);var expectedFile=java.nio.file.Path.of("class-restart-131.nbt");try{
        if(!phase.equals("verify")){train(p,"druzhinnik");ClassState.equip(p,"temper",3);ClassState.equip(p,"lunge",0);ClassState.advance(p,"vityaz");ClassState.advance(p,"bogatyr");ClassState.data(p).putLong("Xp",37);ClassState.data(p).putBoolean("Hud",false);ClassState.cooldown(p,"lunge",12000);var expected=ClassState.data(p).copy();net.minecraft.nbt.NbtIo.writeCompressed(expected,expectedFile);w.getServer().getPlayerList().remove(p);System.out.println("CLASS_NATIVE_PLAYER_STORAGE_WRITE_PASS");}
        if(!phase.equals("write")){var expected=net.minecraft.nbt.NbtIo.readCompressed(expectedFile,net.minecraft.nbt.NbtAccounter.unlimitedHeap());t.assertTrue(w.getServer().getPlayerList().load(p).isPresent(),"Native .dat load missing");ClassEvents.login(new net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedInEvent(p));t.assertTrue(ClassState.data(p).equals(expected),"Class state changed after native disk/new-process load");t.assertTrue(p.getMaxHealth()==24&&ClassState.remaining(p,"lunge")>0,"Loaded modifier/cooldown invalid");System.out.println("CLASS_NATIVE_PLAYER_STORAGE_"+(phase.equals("verify")?"NEW_PROCESS":"SAME_PROCESS")+"_PASS");}
        t.succeed();
    }catch(java.io.IOException ex){throw new RuntimeException(ex);}}
    @GameTest(template="empty",timeoutTicks=200) public static void nativeDeathAndRespawn(GameTestHelper t){var p=player(t,"ClassDeath");train(p,"druzhinnik");ClassState.equip(p,"temper",3);ClassState.equip(p,"lunge",0);ClassState.cooldown(p,"lunge",500);var expected=ClassState.data(p).copy();p.setRespawnPosition(t.getLevel().dimension(),t.absolutePos(new BlockPos(3,2,3)),0,true,false);p.kill();t.assertTrue(!p.isAlive(),"Native kill did not kill");var respawn=t.getLevel().getServer().getPlayerList().respawn(p,false,Entity.RemovalReason.KILLED);try{var actual=ClassState.data(respawn);t.assertTrue(actual.getString("Base").equals(expected.getString("Base"))&&actual.getCompound("Ranks").equals(expected.getCompound("Ranks"))&&actual.getCompound("Cooldowns").equals(expected.getCompound("Cooldowns")),"Native clone lost class data");t.assertTrue(respawn.getMaxHealth()==24&&ClassState.remaining(respawn,"lunge")>0,"Respawn reset attributes/cooldown");}finally{t.getLevel().getServer().getPlayerList().remove(respawn);}t.succeed();}
    @GameTest(template="empty",timeoutTicks=200) public static void fullLoadoutOrdinaryDeathAndCommand(GameTestHelper t){int deaths=0;for(String base:ClassDefinitions.BASES)for(boolean command:java.util.List.of(false,true)){var p=player(t,"ClassLifecycle");train(p,base);var active=ClassDefinitions.SKILLS.values().stream().filter(s->s.base().equals(base)&&s.kind()==ClassDefinitions.Kind.ACTIVE).toList();for(int slot=0;slot<3;slot++){ClassState.equip(p,active.get(slot).id(),slot);ClassState.cooldown(p,active.get(slot).id(),500);}ClassState.equip(p,base.equals("druzhinnik")?"temper":base.equals("vedun")?"ward_power":"light_step",3);ClassState.data(p).putLong("Xp",37);ClassState.data(p).putBoolean("Hud",false);String first=ClassDefinitions.BRANCHES.values().stream().filter(b->b.parent().equals(base)).findFirst().orElseThrow().id();ClassState.advance(p,first);var expected=ClassState.data(p).copy();double max=p.getMaxHealth(),speed=p.getAttributeValue(Attributes.MOVEMENT_SPEED);p.setRespawnPosition(t.getLevel().dimension(),t.absolutePos(new BlockPos(3,2,3)),0,true,false);
        if(command)t.getLevel().getServer().getCommands().performPrefixedCommand(p.createCommandSourceStack().withPermission(2),"kill");else{for(int n=0;n<61;n++)p.tick();p.hurt(p.damageSources().generic(),100);}
        t.assertTrue(!p.isAlive(),"Death route did not kill: "+base+" command="+command);var next=t.getLevel().getServer().getPlayerList().respawn(p,false,Entity.RemovalReason.KILLED);next.connection.player=next;try{t.assertTrue(ClassState.data(next).equals(expected),"Full class loadout lost: "+base);for(int n=0;n<4;n++)ClassState.restore(next);t.assertTrue(next.getMaxHealth()==max&&Math.abs(next.getAttributeValue(Attributes.MOVEMENT_SPEED)-speed)<.00001,"Passive modifier doubled: "+base);}finally{t.getLevel().getServer().getPlayerList().remove(next);}deaths++;
    }System.out.println("CLASS_NATIVE_ORDINARY_AND_COMMAND_DEATH_PASS deaths="+deaths);t.succeed();}
    @GameTest(template="empty") public static void lowHealthTriggers(GameTestHelper t){for(String base:java.util.List.of("druzhinnik","vedun"))for(int rank=1;rank<=3;rank++){var p=player(t,"ClassLowHp");train(p,base);String id=base.equals("druzhinnik")?"second_wind":"last_rite";ClassState.data(p).getCompound("Ranks").putInt(id,rank);for(int n=0;n<61;n++)p.tick();t.assertTrue(p.hurt(p.damageSources().generic(),15)&&p.getHealth()<6,"Native low-health damage failed");t.assertTrue(ClassState.remaining(p,id)>0,"Low-health trigger failed "+id);if(id.equals("last_rite"))t.assertTrue(p.getAbsorptionAmount()==ClassDefinitions.SKILLS.get(id).power(rank),"Last rite rank capacity wrong");ClassState.data(p).getCompound("Cooldowns").remove(id);p.setHealth(7);p.setAbsorptionAmount(0);p.invulnerableTime=0;p.hurt(p.damageSources().generic(),2);t.assertTrue(ClassState.remaining(p,id)==0,"HP oscillation retriggered protection");}t.succeed();}
    @GameTest(template="empty") public static void projectileAndEscape(GameTestHelper t){for(int rank=1;rank<=3;rank++){var p=player(t,"ClassArrow");train(p,"razboinik");for(String skill:java.util.List.of("keen_eye","hunters_fervor","opportunity"))ClassState.data(p).getCompound("Ranks").putInt(skill,rank);var mob=EntityType.ZOMBIE.create(t.getLevel());mob.setNoAi(true);mob.moveTo(p.getX()+3,p.getY(),p.getZ()+7);t.getLevel().addFreshEntity(mob);var hit=new net.minecraft.world.entity.projectile.Arrow(EntityType.ARROW,t.getLevel());hit.setOwner(p);t.assertTrue(mob.hurt(p.damageSources().arrow(hit,p),3),"Native ranged damage failed");t.assertTrue(ClassState.remaining(p,"hunters_fervor")>0&&p.hasEffect(net.minecraft.world.effect.MobEffects.MOVEMENT_SPEED),"Ranged hit trigger missing");ClassState.equip(p,"keen_eye",0);t.assertTrue(ClassRuntime.activate(p,0),"Marked target activation failed");var next=new net.minecraft.world.entity.projectile.Arrow(EntityType.ARROW,t.getLevel());next.setOwner(p);next.setPos(p.getEyePosition());next.setDeltaMovement(0,0,2);t.getLevel().addFreshEntity(next);double angle=Math.toDegrees(Math.acos(next.getDeltaMovement().normalize().dot(new net.minecraft.world.phys.Vec3(0,0,1))));t.assertTrue(angle>ClassDefinitions.SKILLS.get("keen_eye").power(rank)-.01&&angle<=ClassDefinitions.SKILLS.get("keen_eye").power(rank)+.01&&Math.abs(next.getDeltaMovement().length()-2)<.00001,"Unbounded/missing projectile correction");t.assertTrue(!p.getPersistentData().contains("ClassArmed_keen_eye"),"Correction can repeat");next.discard();mob.moveTo(p.getX(),p.getY(),p.getZ()-1);mob.setTarget(p);mob.swinging=true;p.setOnGround(true);p.setYRot(0);p.setXRot(0);ClassState.equip(p,"dash",1);t.assertTrue(ClassRuntime.activate(p,1)&&p.getPersistentData().getLong("ClassOpportunityUntil")>ClassState.now(p),"Confirmed escape trigger missing");mob.discard();}t.succeed();}
    @GameTest(template="empty") public static void confirmedShieldRiposte(GameTestHelper t){var p=player(t,"ClassShield");train(p,"druzhinnik");for(int n=0;n<61;n++)p.tick();p.setYRot(0);p.setXRot(0);p.setItemInHand(net.minecraft.world.InteractionHand.OFF_HAND,new ItemStack(Items.SHIELD));p.startUsingItem(net.minecraft.world.InteractionHand.OFF_HAND);for(int n=0;n<6;n++)p.doTick();t.assertTrue(p.isBlocking(),"Fixture shield not raised");var mob=EntityType.ZOMBIE.create(t.getLevel());mob.moveTo(p.getX(),p.getY(),p.getZ()+2);var difficulty=t.getLevel().getDifficulty();try{t.getLevel().getServer().setDifficulty(net.minecraft.world.Difficulty.NORMAL,true);for(int rank=1;rank<=3;rank++){ClassState.data(p).getCompound("Ranks").putInt("riposte",rank);ClassState.data(p).getCompound("Cooldowns").remove("riposte");p.invulnerableTime=0;float health=p.getHealth();p.hurt(p.damageSources().mobAttack(mob),5);ClassEvents.tick(new net.neoforged.neoforge.event.tick.PlayerTickEvent.Post(p));t.assertTrue(p.getHealth()==health&&ClassState.remaining(p,"riposte")==ClassDefinitions.SKILLS.get("riposte").cooldown(rank),"Native shield/riposte rank "+rank);}}finally{t.getLevel().getServer().setDifficulty(difficulty,true);}System.out.println("CLASS_NATIVE_SHIELD_RANKS_PASS stat_counter="+p.getStats().getValue(net.minecraft.stats.Stats.CUSTOM.get(net.minecraft.stats.Stats.DAMAGE_BLOCKED_BY_SHIELD)));t.succeed();}
    @GameTest(template="empty") public static void passiveRanks(GameTestHelper t){int count=0;for(String base:ClassDefinitions.BASES)for(var s:ClassDefinitions.SKILLS.values())if(s.base().equals(base)&&s.kind()==ClassDefinitions.Kind.PASSIVE)for(int rank=1;rank<=3;rank++){var p=player(t,"ClassPassive");train(p,base);ClassState.data(p).getCompound("Ranks").putInt(s.id(),rank);ClassState.equip(p,s.id(),3);for(int n=0;n<3;n++)ClassState.restore(p);
        if(s.id().equals("temper"))t.assertTrue(p.getMaxHealth()==20+new double[]{2,3,4}[rank-1],"Native health rank "+rank);
        if(s.id().equals("steadfast"))t.assertTrue(Math.abs(p.getAttributeValue(Attributes.KNOCKBACK_RESISTANCE)-new double[]{.08,.12,.16}[rank-1])<.00001,"Resistance rank "+rank);
        if(s.id().equals("light_step"))t.assertTrue(Math.abs(p.getAttributeValue(Attributes.MOVEMENT_SPEED)-.1*(1+new double[]{.03,.05,.07}[rank-1]))<.00001,"Movement rank "+rank);
        if(s.id().equals("herbalism")){p.setHealth(10);ClassEvents.healFromHerb(p,1);t.assertTrue(p.getHealth()==10+new double[]{1,1.5,2}[rank-1],"Herbal healing rank "+rank);}
        if(s.id().equals("ward_power")){ClassState.equip(p,"ward",0);t.assertTrue(ClassRuntime.activate(p,0)&&Math.abs(p.getAbsorptionAmount()-8*(1+new double[]{.1,.2,.3}[rank-1]))<.001,"Native ward enhancement rank "+rank);p.setHealth(20);p.setAbsorptionAmount(0);for(int n=0;n<61;n++)p.tick();p.hurt(p.damageSources().generic(),15);t.assertTrue(Math.abs(p.getAbsorptionAmount()-4*(1+new double[]{.1,.2,.3}[rank-1]))<.001,"Native Last rite enhancement rank "+rank);}
        if(s.id().equals("steady_aim")){var arrow=new net.minecraft.world.entity.projectile.Arrow(EntityType.ARROW,t.getLevel());arrow.setOwner(p);arrow.setCritArrow(true);arrow.setPos(p.getEyePosition());arrow.setDeltaMovement(0,0,1);t.getLevel().addFreshEntity(arrow);t.assertTrue(Math.abs(arrow.getBaseDamage()-2*(1+new double[]{.04,.07,.1}[rank-1]))<.00001,"Native critical arrow rank "+rank);arrow.discard();}
        if(s.id().equals("cold_blood")){var cow=EntityType.COW.create(t.getLevel());cow.moveTo(p.getX(),p.getY(),p.getZ()+2);cow.setHealth(2);cow.setNoAi(true);t.getLevel().addFreshEntity(cow);p.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_SWORD));cow.hurt(p.damageSources().playerAttack(p),1);t.assertTrue(Math.abs((2-cow.getHealth())-(1+new double[]{.05,.08,.12}[rank-1]))<.00001,"Native wounded-target damage rank "+rank);cow.discard();}
        if(s.id().equals("spirit_sense")){var listener=(FixtureListener)p.connection;t.getLevel().addNewPlayer(p);var spirit=org.slavicmyths.registry.ModEntities.DOMOVOY.get().create(t.getLevel());spirit.moveTo(p.getX(),p.getY(),p.getZ()+3);t.getLevel().addFreshEntity(spirit);try{int before=listener.particles;p.tickCount=40;ClassEvents.tick(new net.neoforged.neoforge.event.tick.PlayerTickEvent.Post(p));t.assertTrue(listener.particles>before,"No server mythical-sense signal rank "+rank);}finally{spirit.discard();t.getLevel().removePlayerImmediately(p,Entity.RemovalReason.DISCARDED);}}
        count++;
    }System.out.println("CLASS_PASSIVE_RANK_MATRIX_PASS cases="+count);t.succeed();}
}
