modLoader="javafml"
loaderVersion="[36,37)"
license="All Rights Reserved"
[[mods]]
modId="slavicmyths"
version="${version}"
displayName="Slavic Myths"
description='''A small foundation for a world gradually touched by Slavic mythology. Mythological connections are game interpretations.'''
[[dependencies.slavicmyths]]
modId="curios"
mandatory=true
versionRange="[1.16.5-4.1.0.0,1.16.5-5)"
ordering="AFTER"
side="BOTH"
[[dependencies.slavicmyths]]
modId="forge"
mandatory=true
versionRange="[36.2.42,37)"
ordering="NONE"
side="BOTH"
[[dependencies.slavicmyths]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.16.6)"
ordering="NONE"
side="BOTH"
