package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.level.block.*;
import net.neoforged.neoforge.gametest.*;
import org.slavicmyths.gorodishche.*;
@GameTestHolder("slavicmyths_city") @PrefixGameTestTemplate(false)
public final class GorodishcheDefenseGameTests {
 @BeforeBatch(batch="city_defense")public static void terrain(net.minecraft.server.level.ServerLevel l){GorodishcheGameTests.flat(l);}
 @GameTest(template="empty",batch="city_defense",timeoutTicks=1000)
 public static void gateAndNativeRaid(GameTestHelper t){var l=t.getLevel();int x=700000,z=700000;Set<net.minecraft.world.level.ChunkPos>held=new HashSet<>();for(int cx=(x-32)>>4;cx<=(x+208)>>4;cx++)for(int cz=(z-32)>>4;cz<=(z+208)>>4;cz++){l.getChunk(cx,cz);l.setChunkForced(cx,cz,true);held.add(new net.minecraft.world.level.ChunkPos(cx,cz));}var source=l.getServer().createCommandSourceStack().withLevel(l).withPosition(new net.minecraft.world.phys.Vec3(x-8,-56,z-8));t.assertTrue(CityCommands.showcase(source,"temperate")==22,"Defense showcase failed");var plan=CityPlan.make("temperate",125176,x,z,(a,b)->-57,true);var barracks=plan.placements().stream().filter(p->p.building().name().equals("druzhinnik_barracks_01")).findFirst().orElseThrow();var anchor=barracks.transform(barracks.building().jobs().getFirst().pos());var site=CitySites.find(l,anchor).orElseThrow();t.assertTrue(!site.bounds().isInside(site.approach()),"Raid approach is inside walls");var probe=net.minecraft.world.entity.EntityType.VILLAGER.create(l);var initial=site.approach();probe.moveTo(initial.getX()+.5,initial.getY(),initial.getZ()+.5,0,0);probe.setNoAi(true);((net.minecraft.world.entity.ai.navigation.GroundPathNavigation)probe.getNavigation()).setCanOpenDoors(true);l.addFreshEntity(probe);
 t.runAfterDelay(20,()->{probe.setOnGround(true);var inside=initial.relative(site.outward().getOpposite(),24);var path=probe.getNavigation().createPath(inside,1);t.assertTrue(path!=null&&path.canReach(),"Gate path blocked from outside");probe.moveTo(inside.getX()+.5,inside.getY(),inside.getZ()+.5,0,0);var exit=probe.getNavigation().createPath(initial,1);t.assertTrue(exit!=null&&exit.canReach(),"Gate exit blocked");probe.discard();System.out.println("CITY_GATE_PATH_PASS outsideToInside=true insideToOutside=true clearPass=5x5");});
 List<org.slavicmyths.bandit.BanditEntity>party=new ArrayList<>();Set<java.util.UUID>crossed=new HashSet<>(),engaged=new HashSet<>();t.onEachTick(()->{for(var b:party){if(b.isAlive()&&plan.bounds().isInside(b.blockPosition()))crossed.add(b.getUUID());if(b.getLastHurtByMob() instanceof net.minecraft.world.entity.npc.Villager v&&org.slavicmyths.military.Military.guard(v))engaged.add(b.getUUID());}});
 t.runAfterDelay(500,()->{t.assertTrue(l.isVillage(anchor),"City not recognized as native village");t.assertTrue(org.slavicmyths.military.BanditRaids.get(l).start(l,anchor,UUID.randomUUID(),true),"City raid did not start");var raid=org.slavicmyths.military.BanditRaids.get(l).inspect(anchor);for(var raw:raid.getList("Attackers",10)){var e=l.getEntity(((net.minecraft.nbt.CompoundTag)raw).getUUID("Id"));t.assertTrue(e instanceof org.slavicmyths.bandit.BanditEntity,"Raid attacker missing");var b=(org.slavicmyths.bandit.BanditEntity)e;t.assertTrue(!plan.bounds().isInside(b.blockPosition()),"Raid spawned inside city");party.add(b);}System.out.println("CITY_RAID_STARTED outsideOnly=true attackers="+party.size());});
 t.runAfterDelay(850,()->{try{t.assertTrue(!party.isEmpty()&&(!crossed.isEmpty()||!engaged.isEmpty()),"Raid neither crossed the gate nor engaged city guards");var records=org.slavicmyths.worldgen.ManualStructureRecords.get(l);var roundtrip=org.slavicmyths.worldgen.ManualStructureRecords.load(records.save(new net.minecraft.nbt.CompoundTag(),l.registryAccess()));t.assertTrue(roundtrip.entries().stream().anyMatch(e->e.family().equals("gorodishche")&&e.bounds().isInside(anchor)),"Manual city record lost on NBT roundtrip");System.out.println("CITY_RAID_GATE_PASS crossed="+crossed.size()+" guardEngaged="+engaged.size()+" nativeVillage=true existingRaidSystem=true loadedLookupOnly=true manualRecordRoundtrip=true");t.succeed();}finally{for(var b:party)b.discard();for(var q:held)l.setChunkForced(q.x,q.z,false);}});
 }
}
