package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.*;
import net.neoforged.neoforge.gametest.*;
import org.slavicmyths.gorodishche.*;
@GameTestHolder("slavicmyths_city") @PrefixGameTestTemplate(false)
public final class GorodishcheGameTests {
 @GameTest(template="empty",timeoutTicks=200)
 public static void assetsAndPlans(GameTestHelper t)throws Exception{
  var l=t.getLevel();int templates=0,states=0;
  for(var entry:l.getServer().getResourceManager().listResources("structure/gorodishche",r->r.getNamespace().equals("slavicmyths")&&r.getPath().endsWith(".nbt")).entrySet()){
   CompoundTag n;try(var stream=entry.getValue().open()){n=NbtIo.readCompressed(stream,NbtAccounter.unlimitedHeap());}
   for(var raw:n.getList("palette",10)){var s=(CompoundTag)raw;var id=ResourceLocation.parse(s.getString("Name"));t.assertTrue(BuiltInRegistries.BLOCK.containsKey(id),"Missing block "+id+" "+entry.getKey());var b=BuiltInRegistries.BLOCK.get(id);var props=s.getCompound("Properties");for(var key:props.getAllKeys()){var property=b.getStateDefinition().getProperty(key);t.assertTrue(property!=null&&property.getValue(props.getString(key)).isPresent(),"Invalid state "+id+" "+key+" "+entry.getKey());}states++;}templates++;
  }
  t.assertTrue(templates==240,"Expected 240 real templates: "+templates);
  for(String climate:List.of("temperate","cold","warm"))for(int seed=0;seed<32;seed++){
   var plan=CityPlan.make(climate,seed,10000,10000,(x,z)->-57,seed==0);CityPlacement.validate(plan,l.getStructureManager(),l,l.getServer().getResourceManager());t.assertTrue(plan.residential()>=8&&plan.residential()<=14&&plan.professions()>=3&&plan.professions()<=6,"Building counts");t.assertTrue(plan.beds()>=24&&plan.beds()<=40,"Bed count "+plan.beds());var other=CityPlan.make(climate,seed,10000,10000,(x,z)->-57,seed==0);t.assertTrue(plan.placements().toString().equals(other.placements().toString()),"Non deterministic plan");for(var p:plan.placements()){if(p.lot().category().equals("defense"))continue;int front=switch(p.lot().facing()){case NORTH->p.box().minZ();case SOUTH->p.box().maxZ();case EAST->p.box().maxX();case WEST->p.box().minX();default->0;};t.assertTrue(front==p.lot().front(),"Red line mismatch "+p.building().id());}
  }
  System.out.println("CITY_ASSETS_PLANS_PASS templates="+templates+" rawStates="+states+" plans=96 threeClimates=true deterministic=true frontage=true");t.succeed();
 }
 @GameTest(template="empty",timeoutTicks=200)
 public static void nativeNoiseTerrain(GameTestHelper t){var l=t.getLevel();var registries=l.registryAccess();var biome=net.minecraft.world.level.biome.MultiNoiseBiomeSource.createFromPreset(registries.registryOrThrow(Registries.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST).getHolderOrThrow(net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterLists.OVERWORLD));var settings=registries.registryOrThrow(Registries.NOISE_SETTINGS).getHolderOrThrow(net.minecraft.world.level.levelgen.NoiseGeneratorSettings.OVERWORLD);var generator=new net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator(biome,settings);var city=registries.registryOrThrow(Registries.STRUCTURE).get(ResourceLocation.fromNamespaceAndPath("slavicmyths","gorodishche"));var placement=(net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement)registries.registryOrThrow(Registries.STRUCTURE_SET).get(ResourceLocation.fromNamespaceAndPath("slavicmyths","gorodishche")).placement();int accepted=0,rejected=0;Map<String,Integer>reasons=new HashMap<>();
  for(long seed:List.of(125176L,918273L,20261007L)){var random=net.minecraft.world.level.levelgen.RandomState.create(settings.value(),registries.lookupOrThrow(Registries.NOISE),seed);int count=0;for(int i=0;i<17&&count<1;i++){int cell=seed==918273L&&i==0?72:i;var chunk=placement.getPotentialStructureChunk(seed,(cell%16-8)*128,(cell/16-4)*128);var start=city.generate(registries,generator,biome,random,l.getStructureManager(),seed,chunk,0,l,city.biomes()::contains);if(!start.isValid()){rejected++;var diagnostic=org.slavicmyths.worldgen.StructureCoverageService.lastPlacement();reasons.merge(String.valueOf(diagnostic==null?null:diagnostic.lastReason()),1,Integer::sum);if(i<4)System.out.println("CITY_NATIVE_REJECT seed="+seed+" chunk="+chunk+" diagnostics="+org.slavicmyths.worldgen.StructureCoverageService.lastPlacement());continue;}count++;accepted++;t.assertTrue(start.getPieces().stream().anyMatch(p->p instanceof CityBuildingPiece),"Native start missing authored pieces");t.assertTrue(org.slavicmyths.worldgen.StructureCoverageService.referencesFit(chunk,start.getPieces()),"Native city outside reference window");System.out.println("CITY_NATIVE_ACCEPT seed="+seed+" chunk="+chunk+" pieces="+start.getPieces().size()+" bounds="+start.getBoundingBox());}System.out.println("CITY_NATIVE_SEED seed="+seed+" accepted="+count+" reasons="+reasons);}
  t.assertTrue(accepted>0,"No native noise-terrain city accepted across three seeds");System.out.println("CITY_NATIVE_NOISE_PASS seeds=3 accepted="+accepted+" rejected="+rejected+" standardOverworldNoise=true noWorldEdits=true");t.succeed();
 }
 @GameTest(template="empty",timeoutTicks=100)
 public static void boundsAbort(GameTestHelper t){var l=t.getLevel();var witness=new BlockPos(600010,l.getMaxBuildHeight()-2,600010);l.getChunk(witness.getX()>>4,witness.getZ()>>4);l.setBlock(witness,Blocks.GOLD_BLOCK.defaultBlockState(),2);l.setBlock(new BlockPos(600008,witness.getY(),600008),Blocks.GRASS_BLOCK.defaultBlockState(),2);var source=l.getServer().createCommandSourceStack().withLevel(l).withPosition(new net.minecraft.world.phys.Vec3(600000,0,600000));t.assertTrue(CityCommands.showcase(source,"temperate")==0,"Out-of-height city accepted");t.assertTrue(l.getBlockState(witness).is(Blocks.GOLD_BLOCK),"Rejected city edited world");System.out.println("CITY_ABORT_PASS noEditsBeforeValidation=true");t.succeed();}
 @GameTest(template="empty",timeoutTicks=100)
 public static void protectedInventoryAbort(GameTestHelper t){var l=t.getLevel();int x=800000,z=800000;l.getChunk(x>>4,z>>4);int ground=org.slavicmyths.worldgen.LandTerrain.ground(l,x,z);var witness=new BlockPos(x+15,ground+1,z+42);l.getChunk(witness.getX()>>4,witness.getZ()>>4);l.setBlock(witness,Blocks.CHEST.defaultBlockState(),2);var chest=(net.minecraft.world.level.block.entity.ChestBlockEntity)l.getBlockEntity(witness);chest.setItem(0,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.DIAMOND,7));var source=l.getServer().createCommandSourceStack().withLevel(l).withPosition(new net.minecraft.world.phys.Vec3(x-8,ground+1,z-8));t.assertTrue(CityCommands.showcase(source,"temperate")==0,"Protected inventory overwritten");t.assertTrue(l.getBlockState(witness).is(Blocks.CHEST)&&chest.getItem(0).getCount()==7,"Rejected city deleted chest contents");System.out.println("CITY_INVENTORY_ABORT_PASS chestAndSevenDiamondsRetained=true");t.succeed();}
 @BeforeBatch(batch="city_placement") public static void flat(net.minecraft.server.level.ServerLevel l){var settings=((net.minecraft.world.level.levelgen.FlatLevelSource)l.getChunkSource().getGenerator()).settings();settings.getLayersInfo().clear();settings.getLayersInfo().add(new net.minecraft.world.level.levelgen.flat.FlatLayerInfo(1,Blocks.BEDROCK));settings.getLayersInfo().add(new net.minecraft.world.level.levelgen.flat.FlatLayerInfo(6,Blocks.DIRT));settings.getLayersInfo().add(new net.minecraft.world.level.levelgen.flat.FlatLayerInfo(1,Blocks.GRASS_BLOCK));settings.updateLayers();l.getGameRules().getRule(net.minecraft.world.level.GameRules.RULE_DOMOBSPAWNING).set(false,l.getServer());l.setDayTime(2000);l.getGameRules().getRule(net.minecraft.world.level.GameRules.RULE_DAYLIGHT).set(false,l.getServer());}
 @GameTest(template="empty",batch="city_placement",timeoutTicks=800)
 public static void threeShowcases(GameTestHelper t)throws Exception{var l=t.getLevel();int n=0;List<Runnable>checks=new ArrayList<>();List<net.minecraft.world.entity.npc.Villager>workers=new ArrayList<>();List<net.minecraft.world.item.trading.MerchantOffer>paidOffers=new ArrayList<>();Set<net.minecraft.world.level.ChunkPos>held=new HashSet<>();
 for(String climate:List.of("temperate","cold","warm")){int x=400000+n++*512,z=400000;var source=l.getServer().createCommandSourceStack().withLevel(l).withPosition(new net.minecraft.world.phys.Vec3(x-8,-56,z-8));int count=l.getServer().getCommands().getDispatcher().execute("sm test gorodishche_showcase "+climate,source);t.assertTrue(count>=18,"Showcase failed "+climate+" result="+count);var plan=CityPlan.make(climate,125176,x,z,(a,b)->-57,true);int beds=0,guards=0;
 for(int cx=x>>4;cx<=(x+175)>>4;cx++)for(int cz=z>>4;cz<=(z+175)>>4;cz++){var q=new net.minecraft.world.level.ChunkPos(cx,cz);held.add(q);l.setChunkForced(cx,cz,true);}
 for(var p:plan.placements()){
  if(p.building().category().equals("defense"))continue;var v=net.minecraft.world.entity.EntityType.VILLAGER.create(l);var outside=p.transform(p.building().entrance()).relative(p.lot().facing(),2);v.moveTo(outside.getX()+.5,outside.getY(),outside.getZ()+.5,0,0);v.setNoAi(true);((net.minecraft.world.entity.ai.navigation.GroundPathNavigation)v.getNavigation()).setCanOpenDoors(true);l.addFreshEntity(v);
  for(var local:p.building().beds()){var pos=p.transform(local);t.assertTrue(l.getBlockState(pos).getBlock() instanceof BedBlock,"Lost bed "+p.building().id()+" "+pos);beds++;}
  for(var job:p.building().jobs()){var pos=p.transform(job.pos());t.assertTrue(BuiltInRegistries.BLOCK.getKey(l.getBlockState(pos).getBlock()).equals(job.block()),"Lost job "+p.building().id()+" "+pos);}
  checks.add(()->{v.setOnGround(true);try{for(var local:p.building().beds()){var pos=p.transform(local);var path=v.getNavigation().createPath(pos,2);if((path==null||!path.canReach())&&p.building().name().equals("terem_01")){for(var cp:List.of(new BlockPos(28,4,8),new BlockPos(28,5,9),new BlockPos(28,9,14),new BlockPos(19,9,16))){var q=p.transform(cp);var pp=v.getNavigation().createPath(q,0);System.out.println("TEREM_PATH_DEBUG local="+cp+" reach="+(pp!=null&&pp.canReach())+" end="+(pp==null?null:pp.getEndNode())+" state="+l.getBlockState(q)+" below="+l.getBlockState(q.below()));}}t.assertTrue(path!=null&&path.canReach(),"Bed path blocked "+p.building().id()+" target="+pos+" from="+v.position()+" end="+(path==null?null:path.getEndNode()));}for(var job:p.building().jobs()){var pos=p.transform(job.pos());var path=v.getNavigation().createPath(pos,1);t.assertTrue(path!=null&&path.canReach(),"Job path blocked "+p.building().id()+" "+pos);} }finally{v.discard();}});
 }
 for(var p:plan.placements())if(p.building().name().startsWith("trading_house")){var tradeWorkers=l.getEntitiesOfClass(net.minecraft.world.entity.npc.Villager.class,net.minecraft.world.phys.AABB.of(p.box()),v->!v.isNoAi());t.assertTrue(tradeWorkers.size()==3,"Trade hall does not have three workers");Set<ResourceLocation>roles=new HashSet<>();for(var v:tradeWorkers){roles.add(BuiltInRegistries.VILLAGER_PROFESSION.getKey(v.getVillagerData().getProfession()));var offer=v.getOffers().getFirst();var player=t.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.moveTo(v.getX(),v.getY(),v.getZ()+1,0,0);v.setTradingPlayer(player);var menu=new net.minecraft.world.inventory.MerchantMenu(1,player.getInventory(),v);menu.setSelectionHint(0);menu.getSlot(0).set(offer.getCostA().copy());if(!offer.getCostB().isEmpty())menu.getSlot(1).set(offer.getCostB().copy());t.assertTrue(menu.getSlot(2).hasItem(),"Trade result missing");var result=menu.getSlot(2).remove(offer.getResult().getCount());menu.getSlot(2).onTake(player,result);t.assertTrue(!result.isEmpty()&&offer.getUses()==1&&menu.getSlot(0).getItem().isEmpty(),"Native merchant payment failed");v.setTradingPlayer(null);paidOffers.add(offer);}t.assertTrue(roles.size()==3,"Duplicated trading roles");var template=l.getStructureManager().get(p.building().id()).orElseThrow().save(new CompoundTag());for(var raw:template.getList("blocks",10)){var row=(CompoundTag)raw;var tag=row.getCompound("nbt");if(!tag.getString("LootTable").equals("slavicmyths:chests/gorodishche/trading"))continue;var a=row.getList("pos",3);var pos=p.transform(new BlockPos(a.getInt(0),a.getInt(1),a.getInt(2)));var chest=(net.minecraft.world.level.block.entity.ChestBlockEntity)l.getBlockEntity(pos);chest.unpackLootTable(null);chest.clearContent();chest.unpackLootTable(null);t.assertTrue(chest.isEmpty(),"Structure chest replenished loot");}}
 var actual=l.getEntitiesOfClass(net.minecraft.world.entity.npc.Villager.class,net.minecraft.world.phys.AABB.of(plan.bounds()),v->!v.isNoAi()&&v.getVillagerData().getProfession()!=net.minecraft.world.entity.npc.VillagerProfession.NONE);workers.addAll(actual);guards=(int)actual.stream().filter(org.slavicmyths.military.Military::guard).count();t.assertTrue(guards>=6,"Less than six guards "+guards);System.out.println("CITY_SHOWCASE_PLACED climate="+climate+" buildings="+count+" beds="+beds+" guards="+guards+" ground=-57");
 }
 t.runAfterDelay(20,()->{workers.clear();for(int a=0;a<3;a++)workers.addAll(l.getEntitiesOfClass(net.minecraft.world.entity.npc.Villager.class,net.minecraft.world.phys.AABB.of(CityPlan.make(List.of("temperate","cold","warm").get(a),125176,400000+a*512,400000,(xx,zz)->-57,true).bounds()),v->!v.isNoAi()&&v.getVillagerData().getProfession()!=net.minecraft.world.entity.npc.VillagerProfession.NONE));List<String>failures=new ArrayList<>();for(var check:checks)try{check.run();}catch(Exception ex){failures.add(ex.getMessage());System.out.println("CITY_PATH_FAILURE "+ex.getMessage());}t.assertTrue(failures.isEmpty(),"City paths "+failures);System.out.println("CITY_PATHS_PASS buildings="+checks.size()+" outsideToBedsAndJobs=true upperFloors=true");});
 t.runAfterDelay(600,()->{try{List<String>missing=new ArrayList<>();for(var v:workers){var job=v.getBrain().getMemory(net.minecraft.world.entity.ai.memory.MemoryModuleType.JOB_SITE);if(job.isEmpty())missing.add(BuiltInRegistries.VILLAGER_PROFESSION.getKey(v.getVillagerData().getProfession())+" "+v.blockPosition());}t.assertTrue(missing.isEmpty(),"City native claims "+missing);for(var offer:paidOffers)t.assertTrue(offer.getUses()==0,"Trade hall has not automatically restocked");System.out.println("CITY_TRADING_PASS merchants="+paidOffers.size()+" actualPayment=true automaticRestock=true distinctRoles=true lazyLootIndependent=true");System.out.println("CITY_CLAIMS_PASS workers="+workers.size()+" nativeClaims=true noJobMemoryShortcut=true");t.succeed();}finally{for(var q:held)l.setChunkForced(q.x,q.z,false);}});
 }
}
