package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.nbt.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.npc.*;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.animal.IronGolem;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.level.levelgen.structure.templatesystem.*;
import net.neoforged.neoforge.gametest.*;
import org.slavicmyths.military.*;
import org.slavicmyths.village.*;
import org.slavicmyths.registry.*;
import static org.slavicmyths.verify.SettlementGameTests.*;
@GameTestHolder("slavicmyths_village") @PrefixGameTestTemplate(false)
public final class MilitaryGameTests {
 @GameTest(template="empty",timeoutTicks=1800)
 public static void naturalGuardAssignment(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=EntityType.VILLAGER.create(t.getLevel());var p=t.absolutePos(new BlockPos(4,2,3));v.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);t.getLevel().addFreshEntity(v);t.succeedWhen(()->{t.assertTrue(Military.guard(v)&&v.getData(Military.ARCHETYPE)>=0,"Native guard assignment/archetype");t.assertTrue(v.getOffers().isEmpty(),"Fake guard trades");t.assertTrue(v.getMaxHealth()==30,"Guard health balance");var loaded=EntityType.VILLAGER.create(t.getLevel());loaded.load(v.saveWithoutId(new CompoundTag()));t.assertTrue(loaded.getData(Military.ARCHETYPE).equals(v.getData(Military.ARCHETYPE)),"Archetype rerolled on NBT load");t.assertTrue(v.getMainHandItem().isEmpty()&&v.getOffhandItem().isEmpty(),"Role gear materialized as farm loot");System.out.println("MILITARY_ASSIGN_PASS nativeJob=true stableArchetype=true hp=30 noFakeTrade=true renderOwnedGear=true");});}
 @GameTest(template="empty",batch="guard_loss",timeoutTicks=1700)
 public static void tableLossGrace(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",job);v.setVillagerXp(0);t.runAfterDelay(100,()->{t.getLevel().getPoiManager().getInRange(h->h.is(VillageRoles.JOBS.get("druzhinnik").getKey()),job,64,net.minecraft.world.entity.ai.village.poi.PoiManager.Occupancy.ANY).map(x->x.getPos()).toList().forEach(x->t.getLevel().destroyBlock(x,false));v.getBrain().eraseMemory(MemoryModuleType.JOB_SITE);});t.runAfterDelay(400,()->t.assertTrue(Military.guard(v),"Grace period lost"));t.runAfterDelay(1500,()->{t.assertTrue(v.getVillagerData().getProfession()==VillagerProfession.NONE,"Guard did not demote after grace");t.assertTrue(v.getMaxHealth()==20&&v.getMainHandItem().isEmpty(),"Role protection/gear not removed");System.out.println("MILITARY_TABLE_LOSS_PASS grace=true demotion=true roleModifiersRemoved=true noGear=true");t.succeed();});}
 @GameTest(template="empty",timeoutTicks=900)
 public static void actualGuardCombat(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",job);v.setData(Military.ARCHETYPE,1);var z=EntityType.ZOMBIE.create(t.getLevel());var p=t.absolutePos(new BlockPos(5,2,3));z.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);z.setNoAi(true);t.getLevel().addFreshEntity(z);t.succeedWhen(()->{t.assertTrue(!z.isAlive(),"Actual guard did not defeat zombie");t.assertTrue(v.getHealth()>0&&v.getMaxHealth()==30,"Guard died/balance");System.out.println("MILITARY_COMBAT_PASS actualNativeBrain=true realZombieKilled=true");});}
 @GameTest(template="empty",timeoutTicks=100)
 public static void targetsAndFriendlyFire(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",job);var citizen=EntityType.VILLAGER.create(t.getLevel());var golem=EntityType.IRON_GOLEM.create(t.getLevel());var creeper=EntityType.CREEPER.create(t.getLevel());t.assertTrue(!GuardBehavior.hostile(v,citizen)&&!GuardBehavior.hostile(v,golem)&&!GuardBehavior.hostile(v,creeper),"Friendly/creeper target");t.assertTrue(GuardBehavior.hostile(v,EntityType.SKELETON.create(t.getLevel()))&&GuardBehavior.hostile(v,ModEntities.BANDIT_FIGHTER.get().create(t.getLevel()))&&GuardBehavior.hostile(v,ModEntities.UPYR.get().create(t.getLevel())),"Hostile tags");float hp=citizen.getHealth();citizen.hurt(t.getLevel().damageSources().mobAttack(v),5);t.assertTrue(citizen.getHealth()==hp,"Friendly damage not excluded");System.out.println("MILITARY_TARGETS_PASS tags=true alliesSafe=true creeperSafe=true");t.succeed();}
 @GameTest(template="empty",timeoutTicks=700)
 public static void actualGolemBanditTarget(GameTestHelper t){floor(t);var g=EntityType.IRON_GOLEM.create(t.getLevel());var b=ModEntities.BANDIT_FIGHTER.get().create(t.getLevel());var p=t.absolutePos(new BlockPos(5,2,5));g.moveTo(p.getX(),p.getY(),p.getZ(),0,0);b.moveTo(p.getX()+2,p.getY(),p.getZ(),0,0);b.setNoAi(true);t.getLevel().addFreshEntity(g);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(g.getTarget()==b||!b.isAlive(),"Golem did not acquire bandit");g.discard();b.discard();System.out.println("MILITARY_GOLEM_PASS realTargetSelection=true banditThreat=true");});}
 @GameTest(template="empty",timeoutTicks=100)
 public static void questAuthorityAndDoubleClaim(GameTestHelper t){floor(t);var pos=place(t,3,3,Military.TABLE.get());var p=new net.minecraft.server.level.ServerPlayer(t.getLevel().getServer(),t.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"quest-test"),net.minecraft.server.level.ClientInformation.createDefault());p.moveTo(pos.getX(),pos.getY(),pos.getZ(),0,0);var offer=MilitaryQuests.available(p,pos).stream().filter(q->q.getString("Type").equals("trophy")).findFirst().orElseThrow();String key=offer.getString("Key");t.assertTrue(MilitaryQuests.action(p,pos,key,0),"Accept");t.assertTrue(!MilitaryQuests.action(p,pos,key,2),"Reward without tokens");p.getInventory().add(new ItemStack(Military.TOKEN.get(),6));t.assertTrue(MilitaryQuests.action(p,pos,key,2),"Turn in tokens");int coins=p.getInventory().countItem(ModItems.ANCIENT_COIN.get());t.assertTrue(coins==6&&p.getInventory().countItem(Military.TOKEN.get())==0,"Consumption/reward");t.assertTrue(!MilitaryQuests.action(p,pos,key,2)&&p.getInventory().countItem(ModItems.ANCIENT_COIN.get())==coins,"Duplicate claim");var before=MilitaryQuests.available(p,pos).stream().map(q->q.getString("Key")+q.getList("Rewards",10)).toList();t.assertTrue(before.equals(MilitaryQuests.available(p,pos).stream().map(q->q.getString("Key")+q.getList("Rewards",10)).toList()),"Reopen reroll");var saved=MilitaryQuests.state(p).copy();p.setData(Military.QUESTS,saved);t.assertTrue(!MilitaryQuests.action(p,pos,key,2),"Attachment restore duplicate");p.discard();System.out.println("MILITARY_QUEST_PASS serverValidated=true tokensConsumed=6 rewardOnce=true reopenStable=true attachmentRoundtrip=true");t.succeed();}
 @GameTest(template="empty",batch="barracks_124",timeoutTicks=100)
 public static void barracksPhysicalPaths(GameTestHelper t){
  var origin=t.absolutePos(new BlockPos(1,1,1));var template=t.getLevel().getStructureManager().getOrCreate(VillageRoles.id("military/barracks"));t.assertTrue(template.getSize().equals(new Vec3i(20,21,20)),"Missing rebuilt barracks");
  template.placeInWorld(t.getLevel(),origin,origin,new StructurePlaceSettings().setKnownShape(true).addProcessor(JigsawReplacementProcessor.INSTANCE),t.getLevel().random,2);
  var v=EntityType.VILLAGER.create(t.getLevel());v.setNoAi(true);v.moveTo(origin.getX()+7.5,origin.getY()+3,origin.getZ()+3.5,0,0);((net.minecraft.world.entity.ai.navigation.GroundPathNavigation)v.getNavigation()).setCanOpenDoors(true);t.getLevel().addFreshEntity(v);
  t.runAfterDelay(20,()->{v.setOnGround(true);for(var offset:List.of(new BlockPos(10,3,7),new BlockPos(10,3,10))){var path=v.getNavigation().createPath(origin.offset(offset),0);t.assertTrue(path!=null&&path.canReach(),"Barracks tables inaccessible "+offset);}
   for(int y=3;y<=15;y++){var p=origin.offset(15,y,13);var state=t.getLevel().getBlockState(p);t.assertTrue(state.is(Blocks.LADDER)&&state.canSurvive(t.getLevel(),p),"Broken tower ladder "+p);}
   var chest=t.getLevel().getBlockEntity(origin.offset(11,3,15));t.assertTrue(chest instanceof net.minecraft.world.level.block.entity.ChestBlockEntity,"Supply chest absent");System.out.println("MILITARY_BARRACKS_PASS rebuilt=true twoTablesReachable=true supportedPlayerLadder=true supplyChest=true");v.discard();t.succeed();});
 }

 @GameTest(template="empty",timeoutTicks=100)
 public static void nativeVillageBarracksPlanning(GameTestHelper t){var l=t.getLevel();var structure=l.registryAccess().registryOrThrow(net.minecraft.core.registries.Registries.STRUCTURE).get(net.minecraft.resources.ResourceLocation.withDefaultNamespace("village_plains"));var generator=l.getChunkSource().getGenerator();int found=0,plans=0;for(int i=0;i<128;i++){var start=structure.generate(l.registryAccess(),generator,generator.getBiomeSource(),l.getChunkSource().randomState(),l.getStructureManager(),l.getSeed(),new net.minecraft.world.level.ChunkPos(2000+i*40,3000+i*31),0,l,b->true);if(!start.isValid())continue;plans++;long count=start.getPieces().stream().filter(p->p instanceof net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece e&&e.getElement().toString().contains("slavicmyths:military/barracks")).count();t.assertTrue(count<=1,"Natural jigsaw assembly contains duplicate barracks");if(count==1&&++found>=3)break;}t.assertTrue(found>0,"Natural native village planning never selected barracks");System.out.println("MILITARY_NATURAL_PLANNING_PASS nativeVillagePlans="+plans+" barracksPlans="+found+" maxPerVillage=1 noChunkLoading=true");t.succeed();}
 @GameTest(template="empty",batch="raid",timeoutTicks=500)
 public static void actualBanditRaid(GameTestHelper t){var l=t.getLevel();BlockPos anchor=t.absolutePos(new BlockPos(5,2,5));for(int dx=-4;dx<=4;dx++)for(int dz=-4;dz<=4;dz++){l.setChunkForced((anchor.getX()>>4)+dx,(anchor.getZ()>>4)+dz,true);l.getChunk((anchor.getX()>>4)+dx,(anchor.getZ()>>4)+dz);}t.runAfterDelay(40,()->{var events=BanditRaids.get(l);t.assertTrue(events.start(l,anchor,UUID.randomUUID(),true),"Real raid failed to start outside settlement");var state=events.inspect(anchor);var ids=state.getList("Attackers",10);t.assertTrue(ids.size()>=3&&ids.size()<=5,"Small party size");t.assertTrue(!events.start(l,anchor,UUID.randomUUID(),true),"Duplicate raid started");for(Tag tag:ids){var b=(org.slavicmyths.bandit.BanditEntity)l.getEntity(((CompoundTag)tag).getUUID("Id"));t.assertTrue(b!=null&&b.getPersistentData().getBoolean("MilitaryRaider")&&b.blockPosition().distSqr(anchor)>40*40&&b.role!=org.slavicmyths.bandit.BanditEntity.ATAMAN,"Spawn/role/record invalid: entity="+b+" state="+(b==null?"missing":b.getPersistentData()+" distance="+b.blockPosition().distSqr(anchor)+" role="+b.role));}
  t.runAfterDelay(100,()->{var current=events.inspect(anchor).getList("Attackers",10);for(Tag tag:current){var b=(org.slavicmyths.bandit.BanditEntity)l.getEntity(((CompoundTag)tag).getUUID("Id"));t.assertTrue(b!=null,"Attacker vanished");b.hurt(l.damageSources().generic(),10000);}t.assertTrue(!events.inspect(anchor).getBoolean("Active")&&events.inspect(anchor).getString("EndReason").equals("VICTORY"),"Raid did not finish on actual deaths");t.assertTrue(events.inspect(anchor).getLong("Cooldown")>l.getGameTime(),"Post-raid cooldown lost");for(int dx=-4;dx<=4;dx++)for(int dz=-4;dz<=4;dz++)l.setChunkForced((anchor.getX()>>4)+dx,(anchor.getZ()>>4)+dz,false);System.out.println("MILITARY_RAID_PASS actualSpawnOutside=true smallParty=true duplicateStartBlocked=true realDeathEvents=true victory=true cooldown=true");t.succeed();});});}
 @GameTest(template="empty",timeoutTicks=100)
 public static void supplyLootStatistics(GameTestHelper t){var l=t.getLevel();var loot=l.getServer().reloadableRegistries().getLootTable(net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.LOOT_TABLE,VillageRoles.id("chests/barracks_supply")));var params=new net.minecraft.world.level.storage.loot.LootParams.Builder(l).withParameter(net.minecraft.world.level.storage.loot.parameters.LootContextParams.ORIGIN,t.absolutePos(BlockPos.ZERO).getCenter()).create(net.minecraft.world.level.storage.loot.parameters.LootContextParamSets.CHEST);int diamonds=0,saddles=0,food=0;for(int i=0;i<1000;i++)for(var item:loot.getRandomItems(params)){if(item.is(Items.DIAMOND)){t.assertTrue(item.getCount()==1,"Diamond stack");diamonds++;}if(item.is(Items.SADDLE))saddles++;if(item.is(Items.BREAD))food++;}t.assertTrue(diamonds<20&&saddles<80&&food>500,"Loot tiers unbalanced");System.out.println("MILITARY_LOOT_PASS samples=1000 diamonds="+diamonds+" saddles="+saddles+" bread="+food+" diamondCount=1");t.succeed();}

 @GameTest(template="empty",batch="guard_archer",timeoutTicks=800)
 public static void realArcherAttack(GameTestHelper t){floor(t);var anchor=place(t,2,2,Military.TABLE.get());var v=worker(t,2,3,"druzhinnik",anchor);v.setData(Military.ARCHETYPE,3);var z=EntityType.ZOMBIE.create(t.getLevel());var p=t.absolutePos(new BlockPos(9,2,8));z.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);z.setNoAi(true);z.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.LEATHER_HELMET));t.getLevel().addFreshEntity(z);t.succeedWhen(()->{t.assertTrue(z.getHealth()<z.getMaxHealth(),"Archer did not land a real ranged shot");t.assertTrue(v.distanceToSqr(z)>25,"Archer closed into melee");z.discard();v.discard();System.out.println("MILITARY_ARCHER_PASS realArrowDamage=true rangedDistance=true");});}
 @GameTest(template="empty",timeoutTicks=100)
 public static void shieldFrontalReduction(GameTestHelper t){floor(t);var anchor=place(t,2,2,Military.TABLE.get());var v=worker(t,3,3,"druzhinnik",anchor);v.setNoAi(true);v.setYRot(0);v.setHealth(20);var z=EntityType.ZOMBIE.create(t.getLevel());z.moveTo(v.getX(),v.getY(),v.getZ()+2,0,0);v.getPersistentData().putLong("GuardBlockUntil",t.getLevel().getGameTime()+100);v.hurt(t.getLevel().damageSources().mobAttack(z),10);float front=20-v.getHealth();t.assertTrue(front>0&&front<10,"Frontal shield is absent or invulnerable");System.out.println("MILITARY_SHIELD_PASS frontalDamage="+front+" noInvulnerability=true");v.discard();t.succeed();}
 @GameTest(template="empty",timeoutTicks=500)
 public static void residentsFearBandits(GameTestHelper t){floor(t);var v=worker(t,3,3,"miller",place(t,2,2,VillageRoles.MILLSTONE.get()));var b=ModEntities.BANDIT_FIGHTER.get().create(t.getLevel());b.moveTo(v.getX()+3,v.getY(),v.getZ(),0,0);b.setNoAi(true);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(v.getBrain().isActive(Activity.PANIC),"Native resident did not react to tagged bandit");b.discard();v.discard();System.out.println("MILITARY_RESIDENT_PASS nativeThreatSensor=true panic=true");});}
 @GameTest(template="empty",batch="guard_night",timeoutTicks=1600)
 public static void nightRestAndThreat(GameTestHelper t){floor(t);var anchor=place(t,2,2,Military.TABLE.get());t.setBlock(new BlockPos(4,2,3),Blocks.RED_BED.defaultBlockState().setValue(net.minecraft.world.level.block.BedBlock.FACING,Direction.SOUTH).setValue(net.minecraft.world.level.block.BedBlock.PART,net.minecraft.world.level.block.state.properties.BedPart.FOOT));t.setBlock(new BlockPos(4,2,4),Blocks.RED_BED.defaultBlockState().setValue(net.minecraft.world.level.block.BedBlock.FACING,Direction.SOUTH).setValue(net.minecraft.world.level.block.BedBlock.PART,net.minecraft.world.level.block.state.properties.BedPart.HEAD));var v=worker(t,4,4,"druzhinnik",anchor);v.setData(Military.ARCHETYPE,1);v.getBrain().setMemory(MemoryModuleType.HOME,GlobalPos.of(t.getLevel().dimension(),t.absolutePos(new BlockPos(4,2,4))));t.getLevel().setDayTime(13000);v.getBrain().updateActivityFromSchedule(13000,t.getLevel().getGameTime()+40);final Zombie[] attacker={null};t.succeedWhen(()->{if(attacker[0]==null){t.assertTrue(v.isSleeping(),"Guard never rested at night");attacker[0]=EntityType.ZOMBIE.create(t.getLevel());attacker[0].moveTo(v.getX()+1,v.getY(),v.getZ()+1,0,0);attacker[0].setNoAi(true);t.getLevel().addFreshEntity(attacker[0]);v.hurt(t.getLevel().damageSources().mobAttack(attacker[0]),1);throw new GameTestAssertException("Wait for actual night combat");}t.assertTrue(!attacker[0].isAlive()&&v.isSleeping(),"Guard failed night defense or return to rest");t.getLevel().setDayTime(3000);v.discard();System.out.println("MILITARY_NIGHT_PASS actualSleep=true directThreatKilled=true resumedRest=true");});}

 @GameTest(template="empty",batch="guard_neutral",timeoutTicks=100)
 public static void neutralSpiritAggression(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",job);var resident=worker(t,5,3,"miller",job);var spirit=ModEntities.LESHY.get().create(t.getLevel());spirit.moveTo(v.getX()+2,v.getY(),v.getZ(),0,0);spirit.setNoAi(true);t.getLevel().addFreshEntity(spirit);t.assertTrue(!GuardBehavior.hostile(v,spirit),"Calm neutral spirit targeted");resident.hurt(t.getLevel().damageSources().mobAttack(spirit),1);t.assertTrue(GuardBehavior.hostile(v,spirit),"Guard did not defend against aggressive neutral spirit");spirit.discard();v.discard();resident.discard();System.out.println("MILITARY_NEUTRAL_PASS calmExcluded=true actualResidentAttackAccepted=true");t.succeed();}

 @GameTest(template="empty",batch="guard_boundary",timeoutTicks=500)
 public static void pursuitBoundary(GameTestHelper t){floor(t);var anchor=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",anchor);v.setData(Military.ARCHETYPE,1);var z=EntityType.ZOMBIE.create(t.getLevel());z.moveTo(v.getX()+5,v.getY(),v.getZ()+4,0,0);z.setNoAi(true);z.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.LEATHER_HELMET));t.getLevel().addFreshEntity(z);final boolean[] moved={false};t.succeedWhen(()->{if(!moved[0]){t.assertTrue(v.getPersistentData().hasUUID("GuardTarget"),"No actual threat acquired");z.moveTo(anchor.getX()+55,anchor.getY(),anchor.getZ(),0,0);moved[0]=true;throw new GameTestAssertException("Wait for bounded pursuit cleanup");}t.assertTrue(!v.getPersistentData().hasUUID("GuardTarget"),"Guard retained target outside 48 blocks");t.assertTrue(v.blockPosition().distSqr(anchor)<=32*32,"Guard exceeded patrol boundary");z.discard();v.discard();System.out.println("MILITARY_PURSUIT_PASS acquiredRealThreat=true targetReleasedBeyond48=true withinPatrol32=true");t.succeed();});}

 @GameTest(template="empty",batch="guard_reassign",timeoutTicks=1150)
 public static void nativeGuardReassignment(GameTestHelper t){floor(t);var job=place(t,3,3,Military.TABLE.get());var v=worker(t,4,3,"druzhinnik",job);v.setVillagerXp(0);v.setData(Military.ARCHETYPE,4);final BlockPos[] replacement={null};t.runAfterDelay(100,()->{t.getLevel().getPoiManager().getInRange(h->h.is(VillageRoles.JOBS.get("druzhinnik").getKey()),job,64,net.minecraft.world.entity.ai.village.poi.PoiManager.Occupancy.ANY).map(x->x.getPos()).toList().forEach(x->t.getLevel().destroyBlock(x,false));v.getBrain().eraseMemory(MemoryModuleType.JOB_SITE);replacement[0]=place(t,6,3,Military.TABLE.get());});t.succeedWhen(()->{t.assertTrue(replacement[0]!=null,"Replacement not placed");var memory=v.getBrain().getMemory(MemoryModuleType.JOB_SITE);t.assertTrue(memory.isPresent()&&memory.get().pos().equals(replacement[0]),"Native AI did not reassign free table");t.assertTrue(Military.guard(v)&&v.getData(Military.ARCHETYPE)==4,"Reassignment changed role/archetype");System.out.println("MILITARY_REASSIGN_PASS nativeNewPoi=true sameRole=true stableArchetype=true");v.discard();t.succeed();});}
 @GameTest(template="empty",batch="vanilla_raid_conflict",timeoutTicks=100)
 public static void vanillaRaidConflict(GameTestHelper t){floor(t);var anchor=place(t,3,3,Military.TABLE.get());var player=new net.minecraft.server.level.ServerPlayer(t.getLevel().getServer(),t.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"RaidGateTest"),net.minecraft.server.level.ClientInformation.createDefault());var raid=t.getLevel().getRaids().createOrExtendRaid(player,anchor);t.assertTrue(raid!=null&&t.getLevel().getRaidAt(anchor)!=null,"Actual vanilla raid not registered");t.assertTrue(!BanditRaids.get(t.getLevel()).start(t.getLevel(),anchor,UUID.randomUUID(),true),"Bandit party overlapped vanilla raid");raid.stop();System.out.println("MILITARY_VANILLA_RAID_PASS actualVanillaRaid=true banditStartBlocked=true");t.succeed();}

 @GameTest(template="empty",batch="bandit_aggression",timeoutTicks=1000)
 public static void ordinaryBanditAttacksResident(GameTestHelper t){floor(t);var v=EntityType.VILLAGER.create(t.getLevel());var b=ModEntities.BANDIT_FIGHTER.get().create(t.getLevel());var p=t.absolutePos(new BlockPos(4,2,4));v.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);v.setNoAi(true);b.moveTo(p.getX()+5.5,p.getY(),p.getZ()+.5,0,0);b.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SWORD));t.getLevel().addFreshEntity(v);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(v.getHealth()<v.getMaxHealth(),"Ordinary bandit did not actually damage resident; target="+b.getTarget());t.assertTrue(b.getTarget()==v||!v.isAlive(),"Resident damage came from another attacker");b.discard();v.discard();System.out.println("MILITARY_BANDIT_RESIDENT_PASS ordinarySpawn=true actualTarget=true nativePath=true realDamage=true");});}
 @GameTest(template="empty",batch="bandit_stronghold_aggression",timeoutTicks=1000)
 public static void strongholdBanditAttacksResident(GameTestHelper t){floor(t);var v=EntityType.VILLAGER.create(t.getLevel());var b=ModEntities.BANDIT_FIGHTER.get().create(t.getLevel());var p=t.absolutePos(new BlockPos(4,2,4));v.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);v.setNoAi(true);b.moveTo(p.getX()+4.5,p.getY(),p.getZ()+.5,0,0);b.camp=UUID.randomUUID();b.campTotal=org.slavicmyths.bandit.StrongholdRecords.TOTAL;b.campMember=2;b.home=p;b.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SWORD));t.getLevel().addFreshEntity(v);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(v.getHealth()<v.getMaxHealth(),"Stronghold alarm gate blocked actual resident combat");b.discard();v.discard();System.out.println("MILITARY_STRONGHOLD_RESIDENT_PASS calmZone=true npcTargetNotAlarmBlocked=true realDamage=true");});}
 @GameTest(template="empty",batch="golem_real_combat",timeoutTicks=1200)
 public static void golemActuallyDefeatsBandit(GameTestHelper t){floor(t);var g=EntityType.IRON_GOLEM.create(t.getLevel());var b=ModEntities.BANDIT_FIGHTER.get().create(t.getLevel());var p=t.absolutePos(new BlockPos(2,2,5));g.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);b.moveTo(p.getX()+7.5,p.getY(),p.getZ()+.5,0,0);b.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.IRON_SWORD));t.getLevel().addFreshEntity(g);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(!b.isAlive(),"Golem failed actual live bandit combat; target="+g.getTarget());t.assertTrue(g.isAlive(),"Bandit defeated golem");g.discard();System.out.println("MILITARY_GOLEM_COMBAT_PASS liveBandit=true actualMelee=true banditDefeated=true");});}

 @GameTest(template="empty",batch="bandit_archer_resident",timeoutTicks=1200)
 public static void banditArcherAttacksResident(GameTestHelper t){floor(t);var v=EntityType.VILLAGER.create(t.getLevel());var b=ModEntities.BANDIT_ARCHER.get().create(t.getLevel());var p=t.absolutePos(new BlockPos(1,2,2));v.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);v.setNoAi(true);var bp=t.absolutePos(new BlockPos(9,2,8));b.moveTo(bp.getX()+.5,bp.getY(),bp.getZ()+.5,0,0);b.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.BOW));t.getLevel().addFreshEntity(v);t.getLevel().addFreshEntity(b);t.succeedWhen(()->{t.assertTrue(v.getHealth()<v.getMaxHealth(),"Bandit archer never damaged resident with arrow");t.assertTrue(b.getTarget()==v||!v.isAlive(),"Archer selected a different target");b.discard();v.discard();System.out.println("MILITARY_BANDIT_ARCHER_PASS autonomousResidentTarget=true realArrowDamage=true");});}

}
