package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.npc.*;
import net.minecraft.world.entity.animal.Sheep;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.GameRules;
import net.neoforged.neoforge.gametest.*;
import org.slavicmyths.village.*;
import static org.slavicmyths.verify.SettlementGameTests.*;
@GameTestHolder("slavicmyths_village") @PrefixGameTestTemplate(false)
public final class SettlementActivitiesTests {
    // Isolate the physical harvest chain from other tests changing global schedules.
    @BeforeBatch(batch="shepherd") public static void shepherdDay(net.minecraft.server.level.ServerLevel level){level.setDayTime(3000);level.getGameRules().getRule(GameRules.RULE_DAYLIGHT).set(false,level.getServer());}
    @AfterBatch(batch="shepherd") public static void restoreDaylight(net.minecraft.server.level.ServerLevel level){level.getGameRules().getRule(GameRules.RULE_DAYLIGHT).set(true,level.getServer());}
    @BeforeBatch(batch="linen") public static void linenDay(net.minecraft.server.level.ServerLevel level){shepherdDay(level);}
    @AfterBatch(batch="linen") public static void linenDaylight(net.minecraft.server.level.ServerLevel level){restoreDaylight(level);}
    @BeforeBatch(batch="fishing") public static void fishingDay(net.minecraft.server.level.ServerLevel level){shepherdDay(level);}
    @AfterBatch(batch="fishing") public static void fishingDaylight(net.minecraft.server.level.ServerLevel level){restoreDaylight(level);}
    private static Villager nativeRole(GameTestHelper t,int x,int z,VillagerProfession role,BlockPos job){var v=worker(t,x,z,"miller",job);v.setVillagerData(v.getVillagerData().setProfession(role));v.refreshBrain(t.getLevel());v.getBrain().setActiveActivityIfPossible(Activity.WORK);return v;}
    @GameTest(template="empty",batch="fishing",timeoutTicks=4500)
    public static void actualFishingAndDeposit(GameTestHelper t){floor(t);var job=place(t,2,2,Blocks.BARREL);var v=nativeRole(t,3,2,VillagerProfession.FISHERMAN,job);v.getInventory().addItem(new ItemStack(Items.FISHING_ROD));t.setBlock(new BlockPos(5,1,4),Blocks.WATER);var chest=(SettlementChest)t.getLevel().getBlockEntity(place(t,4,3,SettlementStorage.BLOCK.get()));
        t.succeedWhen(()->{int count=0;for(int i=0;i<64;i++)if(chest.getItem(i).is(WorkPolicy.tag("outputs","fisherman")))count+=chest.getItem(i).getCount();t.assertTrue(count==1,"Physical fishing catch not deposited: activity="+v.getBrain().getActiveNonCoreActivity()+" task="+VillageWork.state(v).task+" failure="+VillageWork.state(v).failure+" inventory="+v.getInventory().getItems());t.assertTrue(v.getInventory().getItems().stream().anyMatch(s->s.is(Items.FISHING_ROD)&&s.getDamageValue()==1),"Fishing did not use real rod");System.out.println("SETTLEMENT_FISHING_PASS existingWaterFishing=true catch=1 rodDamage=1 physicalDeposit=true");});}
    @GameTest(template="empty",batch="shepherd",timeoutTicks=4500)
    public static void actualShearingAndDeposit(GameTestHelper t){floor(t);var job=place(t,2,2,Blocks.LOOM);var v=nativeRole(t,3,2,VillagerProfession.SHEPHERD,job);v.getInventory().addItem(new ItemStack(Items.SHEARS));var sheep=EntityType.SHEEP.create(t.getLevel());var p=t.absolutePos(new BlockPos(5,2,4));sheep.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);sheep.setNoAi(true);t.getLevel().addFreshEntity(sheep);var chest=(SettlementChest)t.getLevel().getBlockEntity(place(t,4,3,SettlementStorage.BLOCK.get()));
        t.runAfterDelay(4300,()->System.out.println("SHEPHERD_FINAL time="+t.getLevel().getDayTime()+" activity="+v.getBrain().getActiveNonCoreActivity()+" role="+v.getVillagerData().getProfession()+" job="+v.getBrain().getMemory(MemoryModuleType.JOB_SITE)+" walk="+v.getBrain().getMemory(MemoryModuleType.WALK_TARGET)+" running="+v.getBrain().getRunningBehaviors().stream().map(b->b.getClass().getSimpleName()).toList()+" cargo="+v.getInventory().getItems().stream().map(s->s+" deposit="+WorkPolicy.deposit(v,s)).toList()));
        t.runAfterDelay(2400,()->System.out.println("SHEPHERD_DIAGNOSTIC sheared="+sheep.isSheared()+" pos="+v.position()+" inventory="+v.getInventory().getItems()+" task="+VillageWork.state(v).task+" failure="+VillageWork.state(v).failure+" storage="+VillageWork.state(v).storage+" items="+t.getLevel().getEntitiesOfClass(net.minecraft.world.entity.item.ItemEntity.class,new net.minecraft.world.phys.AABB(job).inflate(12)).stream().map(e->e.getItem()+" flagged="+e.getItem().get(net.minecraft.core.component.DataComponents.CUSTOM_DATA)).toList()));
        t.succeedWhen(()->{int count=0;for(int i=0;i<64;i++)if(chest.getItem(i).is(net.minecraft.tags.ItemTags.WOOL))count+=chest.getItem(i).getCount();t.assertTrue(sheep.isSheared()&&count>=1&&count<=3,"Actual shearing/wool deposit not complete");t.assertTrue(v.getInventory().getItems().stream().anyMatch(s->s.is(Items.SHEARS)&&s.getDamageValue()==1),"Real shears not used");System.out.println("SETTLEMENT_SHEPHERD_PASS nativeShearing=true realWool="+count+" shearsDamage=1 actualHarvestException=true");});}
    @GameTest(template="empty",batch="grief",timeoutTicks=700)
    public static void mobGriefingOff(GameTestHelper t){floor(t);var job=place(t,2,2,Blocks.COMPOSTER);var v=nativeRole(t,3,2,VillagerProfession.FARMER,job);t.setBlock(new BlockPos(4,1,2),Blocks.FARMLAND.defaultBlockState().setValue(FarmBlock.MOISTURE,7));t.setBlock(new BlockPos(4,2,2),Blocks.WHEAT.defaultBlockState().setValue(CropBlock.AGE,7));t.getLevel().getGameRules().getRule(GameRules.RULE_MOBGRIEFING).set(false,t.getLevel().getServer());
        t.runAfterDelay(600,()->{boolean intact=t.getBlockState(new BlockPos(4,2,2)).is(Blocks.WHEAT)&&t.getBlockState(new BlockPos(4,2,2)).getValue(CropBlock.AGE)==7;t.getLevel().getGameRules().getRule(GameRules.RULE_MOBGRIEFING).set(true,t.getLevel().getServer());t.assertTrue(intact&&v.getInventory().isEmpty(),"Farmer bypassed griefing rule");System.out.println("SETTLEMENT_GRIEF_PASS matureCropRetained=true noHarvest=true");t.succeed();});}
    private static void load(GameTestHelper t,int count){floor(t);List<Villager> workers=new ArrayList<>();for(int i=0;i<count;i++){int x=1+i%8,z=1+i/8;var job=place(t,x,z,VillageRoles.MILLSTONE.get());workers.add(worker(t,x,z+1,"miller",job));}
        for(int x:new int[]{2,5,8}){var chest=(SettlementChest)t.getLevel().getBlockEntity(place(t,x,9,SettlementStorage.BLOCK.get()));chest.setItem(0,new ItemStack(Items.WHEAT,64));}
        t.runAfterDelay(1000,()->{int paths=0,searches=0,actions=0;for(var v:workers){var s=VillageWork.state(v);paths+=s.pathRequests;searches+=s.searches;actions+=s.actions;v.discard();}t.assertTrue(paths<=count*25&&searches<=count*8,"Bounded work search/path budget exceeded");System.out.println("SETTLEMENT_LOAD_PASS villagers="+count+" ticks=1000 paths="+paths+" searches="+searches+" actions="+actions+" metric=actualCountersNotMSPT");t.succeed();});}
    @GameTest(template="empty",batch="load20",timeoutTicks=1100) public static void workload20(GameTestHelper t){load(t,20);}
    @GameTest(template="empty",batch="load40",timeoutTicks=1100) public static void workload40(GameTestHelper t){load(t,40);}
    @GameTest(template="empty",batch="night",timeoutTicks=700)
    public static void actualNightSchedule(GameTestHelper t){floor(t);t.getLevel().setDayTime(13000);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);v.getBrain().updateActivityFromSchedule(13000,t.getLevel().getGameTime()+40);v.getInventory().addItem(new ItemStack(Items.WHEAT,2));
        t.runAfterDelay(500,()->{boolean untouched=v.getInventory().countItem(Items.WHEAT)==2&&VillageWork.state(v).actions==0&&!VillageWork.eligible(t.getLevel(),v);t.getLevel().setDayTime(3000);t.assertTrue(untouched,"Night schedule produced items");System.out.println("SETTLEMENT_NIGHT_PASS actualDayTime=13000 noIndustry=true nativeSchedule=true");t.succeed();});}
    @GameTest(template="empty",timeoutTicks=700)
    public static void actualThreatYieldsToPanic(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);var zombie=EntityType.ZOMBIE.create(t.getLevel());var p=t.absolutePos(new BlockPos(5,2,2));zombie.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);zombie.setNoAi(true);t.getLevel().addFreshEntity(zombie);
        t.succeedWhen(()->{t.assertTrue(v.getBrain().isActive(Activity.PANIC)&&!VillageWork.eligible(t.getLevel(),v),"Native panic not triggered by actual zombie");zombie.discard();System.out.println("SETTLEMENT_THREAT_PASS actualZombie=true nativePanic=true workStopped=true");});}
    @GameTest(template="empty",timeoutTicks=800)
    public static void fullStorageRetainsRealOutput(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);v.getInventory().addItem(new ItemStack(Items.WHEAT,2));t.assertTrue(VillageProduction.process(t.getLevel(),v,null).equals("PRODUCED"),"Real mill input/output setup");var chest=(SettlementChest)t.getLevel().getBlockEntity(place(t,6,2,SettlementStorage.BLOCK.get()));for(int i=0;i<64;i++)chest.setItem(i,new ItemStack(Items.STONE,64));
        t.succeedWhen(()->{t.assertTrue(VillageWork.state(v).failure.equals("STORAGE_FULL"),"Fullness failure not exposed");t.assertTrue(v.getInventory().countItem(org.slavicmyths.kitchen.KitchenII.item("wheat_flour"))==1&&chest.isFull(),"Full storage lost/duplicated output");System.out.println("SETTLEMENT_FULL_CARGO_PASS actualFlourRetained=1 failure=STORAGE_FULL");});}
    @GameTest(template="empty",batch="linen",timeoutTicks=24000)
    public static void actualWholeLinenChain(GameTestHelper t){floor(t);var job=place(t,3,3,org.slavicmyths.textile.Textiles.BLOCKS.get("loom_table").get());place(t,4,5,org.slavicmyths.textile.Textiles.BLOCKS.get("flax_breaker").get());place(t,7,5,org.slavicmyths.textile.Textiles.BLOCKS.get("spinning_wheel").get());var v=worker(t,4,3,"weaver",job);var chest=(SettlementChest)t.getLevel().getBlockEntity(place(t,8,8,SettlementStorage.BLOCK.get()));chest.setItem(0,new ItemStack(org.slavicmyths.textile.Textiles.item("flax_stalk"),8));
        t.runAfterDelay(8500,()->{for(var q:List.of(new BlockPos(3,2,3),new BlockPos(4,2,5),new BlockPos(7,2,5)))System.out.println("LINEN_STATION "+q+" "+t.getLevel().getBlockEntity(t.absolutePos(q)).saveWithoutMetadata(t.getLevel().registryAccess()));System.out.println("LINEN_FINAL inventory="+v.getInventory().getItems()+" chest="+InventoryTransactions.snapshot(chest)+" actions="+VillageWork.state(v).actions+" failure="+VillageWork.state(v).failure);});
        t.runAfterDelay(5800,()->{System.out.println("LINEN_DIAGNOSTIC pos="+v.position()+" inventory="+v.getInventory().getItems()+" task="+VillageWork.state(v).task+" failure="+VillageWork.state(v).failure+" pending="+VillageWork.state(v).pending);t.getLevel().setDayTime(27000);v.getBrain().updateActivityFromSchedule(27000,t.getLevel().getGameTime()+40);});
        t.succeedWhen(()->{int cloth=0;for(int i=0;i<64;i++)if(chest.getItem(i).is(org.slavicmyths.textile.Textiles.item("linen_cloth")))cloth+=chest.getItem(i).getCount();t.assertTrue(cloth==1,"Whole physical linen chain not finished");t.assertTrue(VillageWork.state(v).actions>=10,"Skipped textile workstation stages");System.out.println("SETTLEMENT_LINEN_CHAIN_PASS actualNPC=true stalks=8 breaker=true wheel=true loom=true physicalClothDeposit=1");});}
}
