package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.npc.*;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.*;
import net.neoforged.neoforge.gametest.*;
import org.slavicmyths.village.*;

@GameTestHolder("slavicmyths_village") @PrefixGameTestTemplate(false)
public final class SettlementGameTests {
    static BlockPos place(GameTestHelper t,int x,int z,Block block){BlockPos p=t.absolutePos(new BlockPos(x,2,z));var state=block.defaultBlockState();t.getLevel().setBlock(p,state,3);block.setPlacedBy(t.getLevel(),p,state,null,ItemStack.EMPTY);return p;}
    static void floor(GameTestHelper t){for(int x=0;x<12;x++)for(int z=0;z<12;z++){t.setBlock(new BlockPos(x,1,z),Blocks.STONE);if(x==0||z==0||x==11||z==11)for(int y=2;y<5;y++)t.setBlock(new BlockPos(x,y,z),Blocks.GLASS);}t.getLevel().setDayTime(3000);}
    static Villager worker(GameTestHelper t,int x,int z,String role,BlockPos job){Villager v=EntityType.VILLAGER.create(t.getLevel());v.setVillagerData(new VillagerData(VillagerType.PLAINS,VillageRoles.ROLES.get(role).get(),1));var p=t.absolutePos(new BlockPos(x,2,z));v.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,0,0);v.setVillagerXp(1);v.setPersistenceRequired();t.getLevel().addFreshEntity(v);v.refreshBrain(t.getLevel());v.getBrain().setMemory(MemoryModuleType.JOB_SITE,GlobalPos.of(t.getLevel().dimension(),job));v.getBrain().setActiveActivityIfPossible(Activity.WORK);return v;}
    private static SettlementChest chest(GameTestHelper t,int x,int z){return (SettlementChest)t.getLevel().getBlockEntity(place(t,x,z,SettlementStorage.BLOCK.get()));}
    @GameTest(template="empty",timeoutTicks=100)
    public static void storageTransactions(GameTestHelper t){floor(t);var a=chest(t,4,4);var b=chest(t,6,4);t.assertTrue(a.getContainerSize()==64&&a.freeSlots()==64,"64 slots");a.setItem(63,new ItemStack(Items.WHEAT,20));var saved=a.saveWithoutMetadata(t.getLevel().registryAccess());var loaded=new SettlementChest(a.getBlockPos(),a.getBlockState());loaded.loadWithComponents(saved,t.getLevel().registryAccess());t.assertTrue(loaded.getItem(63).getCount()==20,"Last slot persistence");t.assertTrue(b.isEmpty(),"Adjacent inventories merged");
        t.assertTrue(net.minecraft.world.entity.ai.behavior.VillagerGoalPackages.getWorkPackage(VillageRoles.ROLES.get("miller").get(),.5F).stream().anyMatch(p->p.getSecond() instanceof VillageWork),"WORK package mixin was not installed");
        SimpleContainer one=new SimpleContainer(8),two=new SimpleContainer(8);t.assertTrue(InventoryTransactions.transfer(a,63,one,20),"First worker");t.assertTrue(!InventoryTransactions.transfer(a,63,two,20)&&two.isEmpty()&&one.countItem(Items.WHEAT)==20,"Second worker duplicated");
        for(int i=0;i<64;i++)a.setItem(i,new ItemStack(Items.STONE,64));t.assertTrue(a.isFull()&&a.freeSlots()==0&&a.fillRatio()==1&&!a.hasSpace(new ItemStack(Items.WHEAT)),"Fullness API");t.assertTrue(!InventoryTransactions.transfer(one,0,a,20)&&one.countItem(Items.WHEAT)==20,"Full storage lost cargo");
        t.assertTrue(a.getBlockState().getAnalogOutputSignal(t.getLevel(),a.getBlockPos())==15,"Comparator full");t.assertTrue(t.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.ItemHandler.BLOCK,a.getBlockPos(),Direction.UP).getSlots()==64,"Capability");System.out.println("SETTLEMENT_TRANSACTION_PASS 64slots=64 save=true twoWorkers=true full=true comparator=15 capabilities=true");t.succeed();}
    @GameTest(template="empty",timeoutTicks=150)
    public static void hopperAutomationAndBreak(GameTestHelper t){floor(t);var store=chest(t,4,4);BlockPos above=store.getBlockPos().above();t.getLevel().setBlock(above,Blocks.HOPPER.defaultBlockState(),3);var input=(HopperBlockEntity)t.getLevel().getBlockEntity(above);input.setItem(0,new ItemStack(Items.DIAMOND,3));BlockPos below=store.getBlockPos().below();t.getLevel().setBlock(below,Blocks.HOPPER.defaultBlockState(),3);var output=(HopperBlockEntity)t.getLevel().getBlockEntity(below);
        t.runAfterDelay(60,()->{t.assertTrue(input.isEmpty()&&output.getItem(0).getCount()==3,"Hopper input/output");t.getLevel().removeBlock(above,false);t.getLevel().removeBlock(below,false);store.setItem(63,new ItemStack(Items.WHEAT,11));t.getLevel().destroyBlock(store.getBlockPos(),true);var drops=t.getLevel().getEntitiesOfClass(net.minecraft.world.entity.item.ItemEntity.class,new net.minecraft.world.phys.AABB(store.getBlockPos()).inflate(2));int wheat=drops.stream().filter(e->e.getItem().is(Items.WHEAT)).mapToInt(e->e.getItem().getCount()).sum();t.assertTrue(wheat==11,"Break dropped contents more/less than once");System.out.println("SETTLEMENT_HOPPER_BREAK_PASS input=true output=true exactDrop=11");t.succeed();});}
    @GameTest(template="empty",timeoutTicks=4000)
    public static void physicalMillerChain(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var store=chest(t,8,2);store.setItem(0,new ItemStack(Items.WHEAT,4));var v=worker(t,3,2,"miller",job);int xp=v.getVillagerXp();
        t.runAfterDelay(850,()->System.out.println("CHAIN_DIAGNOSTIC activity="+v.getBrain().getActiveNonCoreActivity()+" job="+v.getBrain().getMemory(MemoryModuleType.JOB_SITE)+" task="+VillageWork.state(v).task+" failure="+VillageWork.state(v).failure+" paths="+VillageWork.state(v).pathRequests+" inventory="+v.getInventory().getItems()+" walk="+v.getBrain().getMemory(MemoryModuleType.WALK_TARGET)+" time="+t.getLevel().getDayTime()));
        t.runAfterDelay(1750,()->System.out.println("CHAIN_FINAL_DIAGNOSTIC pos="+v.position()+" storage="+VillageWork.state(v).storage+" task="+VillageWork.state(v).task+" failure="+VillageWork.state(v).failure+" paths="+VillageWork.state(v).pathRequests+" actions="+VillageWork.state(v).actions+" cooldown="+(VillageWork.state(v).nextAttempt-t.getLevel().getGameTime())+" inventory="+v.getInventory().getItems()+" walk="+v.getBrain().getMemory(MemoryModuleType.WALK_TARGET)+" depositAllowed="+v.getInventory().getItems().stream().map(x->WorkPolicy.deposit(v,x)).toList()+" running="+v.getBrain().getRunningBehaviors().stream().map(x->x.getClass().getSimpleName()).toList()));
        t.succeedWhen(()->{int all=0,wheat=0;for(int i=0;i<64;i++){if(store.getItem(i).is(org.slavicmyths.kitchen.KitchenII.item("wheat_flour")))all+=store.getItem(i).getCount();if(store.getItem(i).is(Items.WHEAT))wheat+=store.getItem(i).getCount();}t.assertTrue(wheat==0,"NPC hasn't extracted");t.assertTrue(all==2,"Flour not returned through physical chain");t.assertTrue(v.getVillagerXp()==xp,"Production granted trade XP");t.assertTrue(VillageWork.state(v).actions>=3,"Missing extract/work/deposit steps");System.out.println("SETTLEMENT_PHYSICAL_CHAIN_PASS wheat=4 flour=2 physicalActions="+VillageWork.state(v).actions+" tradeXPunchanged=true");});}
    @GameTest(template="empty",timeoutTicks=700)
    public static void playerContainerSecurity(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var chest=(Container)t.getLevel().getBlockEntity(place(t,4,2,Blocks.CHEST));var barrel=(Container)t.getLevel().getBlockEntity(place(t,4,4,Blocks.BARREL));chest.setItem(0,new ItemStack(Items.WHEAT,16));barrel.setItem(0,new ItemStack(Items.WHEAT,16));chest(t,8,2);var v=worker(t,3,2,"miller",job);
        t.runAfterDelay(600,()->{t.assertTrue(chest.getItem(0).getCount()==16&&barrel.getItem(0).getCount()==16&&v.getInventory().isEmpty(),"Stole player inventory");t.assertTrue(VillageWork.state(v).searches<=5,"Search spam");System.out.println("SETTLEMENT_PLAYER_SECURITY_PASS chest=16 barrel=16 noInput=true");t.succeed();});}
    @GameTest(template="empty",timeoutTicks=100)
    public static void sellOutputAndHarvestPolicy(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);var store=chest(t,6,2);var before=store.saveWithoutMetadata(t.getLevel().registryAccess());var offer=v.getOffers().getFirst();v.notifyTrade(offer);v.restock();t.assertTrue(before.equals(store.saveWithoutMetadata(t.getLevel().registryAccess())),"Trade mutated physical chest");
        v.setVillagerData(v.getVillagerData().setProfession(VillageRoles.ROLES.get("cook").get()));t.assertTrue(!WorkPolicy.deposit(v,new ItemStack(org.slavicmyths.kitchen.KitchenII.item("bliny"))),"Cook sell output deposited");
        v.setVillagerData(v.getVillagerData().setProfession(VillagerProfession.SHEPHERD));t.assertTrue(!WorkPolicy.deposit(v,new ItemStack(Items.WHITE_WOOL)),"Ordinary trade wool bypassed policy");var wool=WorkPolicy.harvest(new ItemStack(Items.WHITE_WOOL,3));t.assertTrue(WorkPolicy.deposit(v,wool)&&ItemStack.isSameItemSameComponents(WorkPolicy.clean(wool),new ItemStack(Items.WHITE_WOOL)),"Real harvest exception/normalization");System.out.println("SETTLEMENT_POLICY_PASS virtualTradesIndependent=true blockedSell=true actualHarvestException=true");t.succeed();}
    @GameTest(template="empty",timeoutTicks=100)
    public static void safeRecipeCapacity(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);for(int i=0;i<8;i++)v.getInventory().setItem(i,new ItemStack(i==0?Items.WHEAT:Items.STONE,64));int grain=v.getInventory().countItem(Items.WHEAT);String result=VillageProduction.process(t.getLevel(),v,null);t.assertTrue(result.equals("PERSONAL_INVENTORY_FULL")&&v.getInventory().countItem(Items.WHEAT)==grain,"Consumed input without output space");System.out.println("SETTLEMENT_CAPACITY_PASS inputsRetained="+grain);t.succeed();}
    @GameTest(template="empty",timeoutTicks=700)
    public static void cagedTradingHall(GameTestHelper t){floor(t);var job=place(t,4,3,VillageRoles.MILLSTONE.get());var v=worker(t,4,4,"miller",job);for(var p:List.of(new BlockPos(3,2,4),new BlockPos(5,2,4),new BlockPos(4,2,5)))for(int y=0;y<2;y++)t.setBlock(p.above(y),Blocks.GLASS);t.setBlock(new BlockPos(4,3,3),Blocks.GLASS);
        var o=v.getOffers().getFirst();int xp=v.getVillagerXp();var player=t.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.moveTo(v.getX(),v.getY(),v.getZ()+1,0,0);v.setTradingPlayer(player);var menu=new net.minecraft.world.inventory.MerchantMenu(1,player.getInventory(),v);menu.setSelectionHint(0);menu.getSlot(0).set(o.getCostA().copy());t.assertTrue(menu.getSlot(2).hasItem(),"Merchant result absent");ItemStack paidResult=menu.getSlot(2).remove(o.getResult().getCount());menu.getSlot(2).onTake(player,paidResult);t.assertTrue(menu.getSlot(0).getItem().isEmpty()&&o.getUses()==1&&!paidResult.isEmpty(),"Native payment/use/result");t.assertTrue(!VillageWork.eligible(t.getLevel(),v),"Work interferes with open merchant menu");v.setTradingPlayer(null);
        t.runAfterDelay(600,()->{t.assertTrue(v.getVillagerXp()>xp&&v.getVillagerData().getProfession()==VillageRoles.ROLES.get("miller").get(),"Caged trade XP/profession failed");t.assertTrue(v.getOffers().getFirst().getUses()==0,"Automatic vanilla workstation restock not reached");t.assertTrue(VillageWork.state(v).searches<=5&&VillageWork.state(v).pathRequests<=8,"Cage path/search spam");System.out.println("SETTLEMENT_HALL_PASS nativeMerchantMenuPayment=true tradeXP=true professionLocked=true automaticRestock=true storageRequired=false paths="+VillageWork.state(v).pathRequests);t.succeed();});}
    @GameTest(template="empty",timeoutTicks=100)
    public static void activitySafety(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var v=worker(t,3,2,"miller",job);v.getBrain().setActiveActivityIfPossible(Activity.PANIC);t.assertTrue(!VillageWork.eligible(t.getLevel(),v),"Work during panic");v.getBrain().setActiveActivityIfPossible(Activity.REST);t.assertTrue(!VillageWork.eligible(t.getLevel(),v),"Work during rest");v.getBrain().setActiveActivityIfPossible(Activity.WORK);v.setAge(-24000);t.assertTrue(!VillageWork.eligible(t.getLevel(),v),"Baby working");v.setAge(0);v.setVillagerData(v.getVillagerData().setProfession(VillagerProfession.NITWIT));t.assertTrue(!VillageWork.eligible(t.getLevel(),v),"Nitwit working");System.out.println("SETTLEMENT_ACTIVITY_PASS panic=false rest=false baby=false nitwit=false");t.succeed();}
    @GameTest(template="empty",timeoutTicks=1800)
    public static void kitchenRealProcess(GameTestHelper t){floor(t);BlockPos job=place(t,3,3,org.slavicmyths.registry.ModBlocks.KITCHEN_TABLE.get());var v=worker(t,4,3,"cook",job);v.getInventory().addItem(new ItemStack(org.slavicmyths.kitchen.KitchenII.item("rye_flour"),3));v.getInventory().addItem(new ItemStack(Items.WATER_BUCKET));v.getInventory().addItem(new ItemStack(org.slavicmyths.kitchen.KitchenII.item("rolling_pin")));var tile=(org.slavicmyths.kitchen.KitchenTile)t.getLevel().getBlockEntity(job);
        t.succeedWhen(()->{t.assertTrue(v.getInventory().countItem(org.slavicmyths.kitchen.KitchenII.item("rye_bread"))==1,"Existing kitchen hasn't produced/collected rye bread");t.assertTrue(v.getInventory().countItem(org.slavicmyths.kitchen.KitchenII.item("rye_flour"))==0&&v.getInventory().countItem(Items.BUCKET)==1,"Exact input/remainder");t.assertTrue(tile.inventory.getItem(0).is(org.slavicmyths.kitchen.KitchenII.item("rolling_pin")),"Tool not installed/retained");System.out.println("SETTLEMENT_KITCHEN_PASS existingRecipe=true actualProcess=true flour=3 water=1 bread=1 bucket=1 retainedTool=true");});}
    @GameTest(template="empty",timeoutTicks=2200)
    public static void brewerDuration(GameTestHelper t){floor(t);BlockPos job=place(t,3,3,org.slavicmyths.brewing.Brewing.BLOCKS.get("fermentation_vat").get());var v=worker(t,4,3,"brewer",job);v.getInventory().addItem(new ItemStack(org.slavicmyths.kitchen.KitchenII.item("barley_grain"),4));v.getInventory().addItem(new ItemStack(Items.WATER_BUCKET));var vat=(org.slavicmyths.brewing.BrewTile)t.getLevel().getBlockEntity(job);
        t.runAfterDelay(500,()->t.assertTrue(v.getInventory().countItem(org.slavicmyths.brewing.Brewing.item("malted_barley"))==0&&vat.getItem(6).isEmpty(),"NPC fast-forwarded malting"));
        t.succeedWhen(()->{t.assertTrue(v.getInventory().countItem(org.slavicmyths.brewing.Brewing.item("malted_barley"))==4,"Malting not collected");t.assertTrue(v.getInventory().countItem(Items.BUCKET)==1,"Malting remainder lost");System.out.println("SETTLEMENT_BREWER_PASS existingVat=true duration=1200 malt=4 bucket=1");});}
    @GameTest(template="empty",timeoutTicks=100)
    public static void textileSharedProcess(GameTestHelper t){floor(t);BlockPos job=place(t,3,3,org.slavicmyths.textile.Textiles.BLOCKS.get("loom_table").get());var v=worker(t,4,3,"weaver",job);var loom=(org.slavicmyths.textile.TextileStation)t.getLevel().getBlockEntity(job);v.getInventory().addItem(new ItemStack(org.slavicmyths.textile.Textiles.item("linen_thread"),4));t.assertTrue(VillageProduction.process(t.getLevel(),v,loom).equals("LOADED"),"Loom loading");for(int i=0;i<159;i++)loom.tick();t.assertTrue(loom.npcOutput().isEmpty(),"Instant loom output");loom.tick();t.assertTrue(VillageProduction.process(t.getLevel(),v,loom).equals("COLLECTED")&&v.getInventory().countItem(org.slavicmyths.textile.Textiles.item("linen_cloth"))==1,"Loom shared input/output");System.out.println("SETTLEMENT_TEXTILE_PASS nativeSteps=160 linenThread=4 linenCloth=1");t.succeed();}
    @GameTest(template="empty",timeoutTicks=700)
    public static void destroyedChestClearsCache(GameTestHelper t){floor(t);var job=place(t,2,2,VillageRoles.MILLSTONE.get());var storage=chest(t,8,2);var v=worker(t,3,2,"miller",job);VillageWork.state(v).storage=storage.getBlockPos();t.getLevel().destroyBlock(storage.getBlockPos(),true);t.runAfterDelay(600,()->{t.assertTrue(VillageWork.state(v).storage==null&&v.getInventory().isEmpty(),"Destroyed cache/ghost extraction");System.out.println("SETTLEMENT_DESTROYED_TARGET_PASS cacheCleared=true remoteTransfer=false");t.succeed();});}
    @GameTest(template="empty",timeoutTicks=1800)
    public static void farmerNativePlayerField(GameTestHelper t){floor(t);BlockPos job=place(t,3,3,Blocks.COMPOSTER);var v=worker(t,4,3,"miller",job);v.setVillagerData(v.getVillagerData().setProfession(VillagerProfession.FARMER));v.refreshBrain(t.getLevel());v.getBrain().setMemory(MemoryModuleType.JOB_SITE,GlobalPos.of(t.getLevel().dimension(),job));v.getBrain().setMemory(MemoryModuleType.SECONDARY_JOB_SITE,List.of(GlobalPos.of(t.getLevel().dimension(),t.absolutePos(new BlockPos(5,1,3)))));v.getBrain().setActiveActivityIfPossible(Activity.WORK);
        t.setBlock(new BlockPos(5,1,3),Blocks.FARMLAND.defaultBlockState().setValue(FarmBlock.MOISTURE,7));t.setBlock(new BlockPos(5,2,3),Blocks.WHEAT.defaultBlockState().setValue(CropBlock.AGE,7));t.setBlock(new BlockPos(5,1,4),Blocks.FARMLAND.defaultBlockState().setValue(FarmBlock.MOISTURE,7));t.setBlock(new BlockPos(5,2,4),Blocks.WHEAT.defaultBlockState().setValue(CropBlock.AGE,1));v.getInventory().addItem(new ItemStack(Items.WHEAT_SEEDS,4));
        t.succeedWhen(()->{var mature=t.getBlockState(new BlockPos(5,2,3));var young=t.getBlockState(new BlockPos(5,2,4));t.assertTrue(mature.is(Blocks.WHEAT)&&mature.getValue(CropBlock.AGE)<7,"Native farmer hasn't harvested/replanted");t.assertTrue(young.is(Blocks.WHEAT),"Destroyed immature crop");System.out.println("SETTLEMENT_FARMER_PASS nativeHarvest=true replant=true playerField=true immatureRetained=true");});}
}
