package org.slavicmyths.client;
import java.util.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ItemStack;
import net.minecraft.nbt.*;
import net.minecraft.network.chat.Component;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.network.PacketDistributor;
import org.slavicmyths.military.*;
@EventBusSubscriber(modid="slavicmyths",value=Dist.CLIENT)
public final class MilitaryScreen extends AbstractContainerScreen<MilitaryMenu> {
 private static CompoundTag latest=new CompoundTag();private int selected,listOffset,textOffset;private List<CompoundTag> quests=List.of();private ItemStack hoveredReward=ItemStack.EMPTY;private final Map<Integer,Integer> rows=new LinkedHashMap<>();
 public MilitaryScreen(MilitaryMenu m,Inventory inv,Component title){super(m,inv,title);imageWidth=456;imageHeight=310;}
 @SubscribeEvent public static void synced(MilitaryNetwork.Synced e){latest=e.data.copy();if(net.minecraft.client.Minecraft.getInstance().screen instanceof MilitaryScreen s&&latest.getLong("Table")==s.menu.pos.asLong()){s.read();s.init();}}
 private Component tr(String key,Object... a){return Component.translatable("military.slavicmyths."+key,a);}
 private void read(){List<CompoundTag> all=new ArrayList<>();for(Tag t:latest.getList("Quests",10))all.add((CompoundTag)t);quests=all;selected=Math.max(0,Math.min(selected,quests.size()-1));}
 protected void init(){imageWidth=Math.min(456,width-8);imageHeight=Math.min(310,height-8);super.init();clearWidgets();read();int left=imageWidth*30/100,right=imageWidth*24/100;
  rows.clear();int yy=28;for(int i=0;i<5&&i+listOffset<quests.size();i++){final int n=listOffset+i;int h=font.split(tr("quest."+quests.get(n).getString("Id")),left-36).size()*9+font.split(Component.literal(quests.get(n).getInt("Progress")+"/"+quests.get(n).getInt("Amount")+" • ").append(tr("difficulty."+quests.get(n).getInt("Difficulty"))),left-24).size()*9+14;if(yy+h>imageHeight-50)break;rows.put(n,yy);addRenderableWidget(FolkUi.button(leftPos+8,topPos+yy,left-14,h-1,Component.empty(),n==selected,b->{selected=n;textOffset=0;init();}));yy+=h;}
  CompoundTag q=quests.isEmpty()?null:quests.get(selected);String[] actions={"accept","track","turn_in","abandon","close"};int bw=(imageWidth-16)/3;for(int i=0;i<5;i++){final int action=i;Button b=addRenderableWidget(FolkUi.button(leftPos+8+(i<3?i:i-3)*(i<3?bw:(imageWidth-16)/2),topPos+imageHeight-(i<3?46:24),(i<3?bw:(imageWidth-16)/2)-2,20,tr(actions[i]),false,x->{if(action==4){onClose();return;}if(q!=null)PacketDistributor.sendToServer(new MilitaryNetwork.Request(menu.containerId,action,q.getString("Key")));}));if(i<4)b.visible=q!=null&&!q.getBoolean("Claimed")&&!q.getBoolean("Abandoned")&&(i==0?!q.getBoolean("Accepted"):q.getBoolean("Accepted"));if(i==2&&q!=null&&q.getInt("Progress")<q.getInt("Amount"))b.visible=false;if(i<4)b.active=q!=null&&!q.getBoolean("Claimed")&&!q.getBoolean("Abandoned")&&(i==0?!q.getBoolean("Accepted"):q.getBoolean("Accepted"));}
 }
 protected void renderBg(GuiGraphics g,float partial,int mx,int my){hoveredReward=ItemStack.EMPTY;int x=leftPos,y=topPos,w=imageWidth,h=imageHeight,l=w*30/100,r=w*24/100;g.blit(org.slavicmyths.village.VillageRoles.id("textures/gui/military.png"),x,y,w,h,0,0,512,512,512,512);g.fill(x+5,y+23,x+l-3,y+h-50,0xffd4bd8d);g.fill(x+l+1,y+23,x+w-r-3,y+h-50,0xffead8ac);g.fill(x+w-r+1,y+23,x+w-5,y+h-50,0xffd4bd8d);
  if(quests.isEmpty())return;var q=quests.get(selected);int cx=x+l+7,cw=w-l-r-14;List<net.minecraft.util.FormattedCharSequence> text=new ArrayList<>();text.addAll(font.split(tr("quest."+q.getString("Id")),cw));text.addAll(font.split(tr("description."+q.getString("Id")),cw));text.addAll(font.split(tr("difficulty."+q.getInt("Difficulty")),cw));text.addAll(font.split(tr("objective",q.getInt("Progress"),q.getInt("Amount")),cw));if(q.contains("Location")){var p=net.minecraft.core.BlockPos.of(q.getLong("Location"));text.addAll(font.split(tr("location",p.getX(),p.getY(),p.getZ()),cw));}text.addAll(font.split(tr("turn_in_hint"),cw));int visible=(h-84)/11;textOffset=Math.min(textOffset,Math.max(0,text.size()-visible));g.enableScissor(cx,y+28,cx+cw,y+h-51);for(int i=0;i<visible&&i+textOffset<text.size();i++)g.drawString(font,text.get(i+textOffset),cx,y+30+i*11,0xff38261c,false);g.disableScissor();if(text.size()>visible){g.fill(cx+cw-2,y+29,cx+cw,y+h-53,0xffa08761);int bar=Math.max(6,(h-84)*visible/text.size()),sy=y+29+(h-84-bar)*textOffset/Math.max(1,text.size()-visible);g.fill(cx+cw-2,sy,cx+cw,sy+bar,0xff633f2b);}
  int rx=x+w-r+5;g.drawString(font,tr("rewards"),rx,y+28,0xff38261c,false);int yy=y+43;g.enableScissor(rx,y+41,x+w-5,y+h-51);for(Tag t:q.getList("Rewards",10)){ItemStack reward=ItemStack.parseOptional(minecraft.level.registryAccess(),(CompoundTag)t);g.renderItem(reward,rx,yy);g.renderItemDecorations(font,reward,rx,yy);var lines=font.split(reward.getHoverName(),r-12);for(int n=0;n<lines.size();n++)g.drawString(font,lines.get(n),rx,yy+18+n*9,0xff38261c,false);if(mx>=rx&&mx<x+w-5&&my>=yy&&my<yy+18+lines.size()*9&&my<y+h-51)hoveredReward=reward;yy+=22+lines.size()*9;}g.disableScissor();
 }
 private String status(CompoundTag q){return q.getBoolean("Claimed")?"claimed":q.getBoolean("Abandoned")?"abandoned":q.getInt("Progress")>=q.getInt("Amount")?"complete":q.getBoolean("Accepted")?"active":"available";}
 protected void renderLabels(GuiGraphics g,int mx,int my){g.drawString(font,title,8,9,0xffead8ac,false);int l=imageWidth*30/100;for(var row:rows.entrySet()){var q=quests.get(row.getKey());int yy=row.getValue()+2;var lines=font.split(tr("quest."+q.getString("Id")),l-36);g.renderItem(new ItemStack(q.getString("Type").equals("trophy")?Military.TOKEN.get():q.getString("Type").equals("defend")?org.slavicmyths.registry.ModItems.RETAINER_SHIELD.get():net.minecraft.world.item.Items.IRON_SWORD),10,yy+3);for(int n=0;n<lines.size();n++)g.drawString(font,lines.get(n),29,yy+n*9,0xff3b281c,false);int bottom=yy+lines.size()*9;g.drawString(font,tr("status."+status(q)),12,bottom,0xff713b30,false);var detail=font.split(Component.literal(q.getInt("Progress")+"/"+q.getInt("Amount")+" • ").append(tr("difficulty."+q.getInt("Difficulty"))),l-24);for(int n=0;n<detail.size();n++)g.drawString(font,detail.get(n),12,bottom+9+n*9,0xff493c2b,false);}}
 public void render(GuiGraphics g,int mx,int my,float partial){super.render(g,mx,my,partial);if(!hoveredReward.isEmpty())g.renderTooltip(font,hoveredReward,mx,my);}
 public boolean mouseScrolled(double x,double y,double dx,double dy){if(x<leftPos+imageWidth*.3){listOffset=Math.max(0,Math.min(Math.max(0,quests.size()-1),listOffset-(int)dy));init();}else textOffset=Math.max(0,textOffset-(int)dy);return true;}
}
