package org.slavicmyths.client;
import java.util.*;
import com.mojang.blaze3d.matrix.MatrixStack;
import net.minecraft.client.gui.screen.inventory.ContainerScreen;
import net.minecraft.client.gui.screen.inventory.InventoryScreen;
import net.minecraft.client.gui.widget.button.Button;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.PlayerInventory;
import net.minecraft.item.ItemStack;
import net.minecraft.util.text.*;
import net.minecraft.util.ResourceLocation;
import org.slavicmyths.yaga.*;
/** Standard Forge menu UI. Help is opt-in, and reward visibility follows synchronized server stage. */
public final class YagaScreen extends ContainerScreen<YagaMenu>{
 private static final ResourceLocation BG=new ResourceLocation("slavicmyths","textures/gui/yaga.png");
 private int popup,page,last=-1;private final List<Button> controls=new ArrayList<>();private final Map<Button,Integer> tabs=new HashMap<>();
 public YagaScreen(YagaMenu menu,PlayerInventory inv,ITextComponent title){super(menu,inv,title);imageWidth=320;imageHeight=236;}
 private ITextComponent tr(String key,Object...args){return new TranslationTextComponent("yaga."+key,args);}private void send(int action){minecraft.gameMode.handleInventoryButtonClick(menu.containerId,action);}
 private Button button(int x,int y,int w,String text,Runnable run){Button b=addButton(new Button(leftPos+x,topPos+y,w,16,tr(text),v->run.run()));controls.add(b);return b;}
 @Override protected void init(){super.init();controls.clear();tabs.clear();last=-1;page=0;popup=0;String[] names={"talk","quests","exchange","cauldron"};for(int i=0;i<4;i++){final int tab=i;Button b=button(8+i*77,126,74,"tab."+names[i],()->{menu.clientTab(tab);send(tab);page=0;popup=0;});tabs.put(b,i);}button(283,22,14,"help",()->popup=1);button(301,22,14,"help",()->popup=2);refresh();}
 private void refresh(){if(controls.size()>6){for(int i=controls.size()-1;i>=6;i--){Button b=controls.remove(i);buttons.remove(b);children.remove(b);}}int tab=menu.tab();if(tab==0){button(112,80,198,"talk.work",()->send(10));button(112,99,97,"talk.question",()->send(11));button(213,99,97,"talk.forest",()->send(12));button(12,107,84,"talk.bye",()->send(13));}
  if(tab==1){if(menu.stage()<3){button(265,22,14,"next",()->{page=1-page;last=-1;});}boolean contract=menu.stage()>=3||page==1;if(contract){button(234,106,76,menu.active()==10+menu.contract()?"submit":"accept",()->send(menu.active()==10+menu.contract()?220:120));}else{int stage=menu.stage();button(234,106,76,menu.active()==stage+1?"submit":"accept",()->send(menu.active()==stage+1?200+stage:100+stage));}}
  if(tab==2){button(265,22,14,"next",()->{page=1-page;last=-1;});for(int row=0;row<3;row++){final int id=page*3+row;Button b=button(234,44+row*25,76,"exchange",()->send(400+id));b.active=menu.stage()>=YagaServices.EXCHANGES[id].stage;}}
  if(tab==3){button(112,44,16,"previous",()->send(500+Math.floorMod(menu.recipe()-1,YagaServices.BREWS.length)));button(294,44,16,"next",()->send(500+(menu.recipe()+1)%YagaServices.BREWS.length));Button b=button(230,81,80,"brew",()->send(600));b.active=menu.stage()>=YagaServices.BREWS[menu.recipe()].stage;}
 }
 @Override public void tick(){super.tick();int signature=menu.tab()+8*menu.stage()+32*menu.active()+1024*menu.recipe()+16384*page;if(signature!=last){last=signature;refresh();}for(Map.Entry<Button,Integer> e:tabs.entrySet())e.getKey().active=e.getValue()!=menu.tab();}
 private void text(MatrixStack m,ITextComponent t,int x,int y,int width,int max,int color){List<net.minecraft.util.IReorderingProcessor> lines=font.split(t,width);for(int i=0;i<Math.min(lines.size(),max);i++)font.draw(m,lines.get(i),x,y+i*9,color);}
 private void icon(ItemStack s,int x,int y){itemRenderer.renderAndDecorateItem(s,leftPos+x,topPos+y);itemRenderer.renderGuiItemDecorations(font,s,leftPos+x,topPos+y);}
 @Override protected void renderBg(MatrixStack m,float partial,int mx,int my){minecraft.getTextureManager().bind(BG);blit(m,leftPos,topPos,0,0,320,236,512,256);for(net.minecraft.inventory.container.Slot slot:menu.slots)if(slot.isActive()){fill(m,leftPos+slot.x-1,topPos+slot.y-1,leftPos+slot.x+17,topPos+slot.y+17,0xff241b17);fill(m,leftPos+slot.x,topPos+slot.y,leftPos+slot.x+16,topPos+slot.y+16,0xff9b8664);}Entity e=minecraft.level.getEntity(menu.npcId);if(e instanceof BabaYaga)InventoryScreen.renderEntityInInventory(leftPos+54,topPos+104,43,leftPos+54-mx,topPos+72-my,(BabaYaga)e);}
 @Override protected void renderLabels(MatrixStack m,int mx,int my){font.draw(m,title,12,7,0xffefd5a0);if(menu.tab()==0){font.draw(m,tr("favor.label"),112,20,0xffefd5a0);font.draw(m,tr("favor."+(menu.stage()>=3?"trusted":menu.stage()>=1?"guest":"stranger")),112,30,0xffefd5a0);}
  if(menu.tab()==0){text(m,tr(menu.dialogue()==1?"dialogue.question":menu.dialogue()==2?"dialogue.forest":"dialogue.stage"+menu.stage()),112,44,198,3,0xff2c211b);}
  if(menu.tab()==1){boolean repeat=menu.stage()>=3||page==1;YagaServices.Entry e=repeat?YagaServices.CONTRACTS[YagaServices.POOL[menu.contract()]]:YagaServices.MAIN[menu.stage()];text(m,tr("quest."+e.id+".title"),112,44,198,1,0xff36271b);text(m,tr("quest."+e.id+".desc"),112,55,198,2,0xff44382b);if(e.inputs.length==0)text(m,tr("quest.boss_proof"),112,77,198,2,0xff36271b);else for(int i=0;i<e.inputs.length;i++)icon(e.inputs[i].stack(),112+i*34,77);if(menu.stage()>0){font.draw(m,tr("reward"),112,97,0xff36271b);icon(e.output(),183,96);}else text(m,tr("reward.hidden"),112,97,120,2,0xff44382b);if(repeat&&menu.contractWait()>0)text(m,tr("cooldown",menu.contractWait()),12,111,84,1,0xffefd5a0);}
  if(menu.tab()==2){for(int row=0;row<3;row++){YagaServices.Entry e=YagaServices.EXCHANGES[page*3+row];icon(e.inputs[0].stack(),112,44+row*25);font.draw(m,tr("arrow"),166,48+row*25,0xff44382b);icon(e.output(),204,44+row*25);if(menu.stage()<e.stage)text(m,tr("locked"),130,48+row*25,70,1,0xff652c23);}}
  if(menu.tab()==3){YagaServices.Entry e=YagaServices.BREWS[menu.recipe()];text(m,e.output().getHoverName(),132,47,156,1,0xff36271b);text(m,tr("recipe."+e.id),112,64,198,2,0xff44382b);font.draw(m,tr("ingredients"),120,99,0xff36271b);font.draw(m,tr("vessel"),223,99,0xff36271b);icon(e.output(),208,81);for(int i=0;i<4;i++)if(menu.input.getItem(i).isEmpty())icon(e.inputs[i].stack(),126+i*28,108);if(menu.stage()<e.stage)text(m,tr("locked"),112,83,94,1,0xff652c23);}
 }
 @Override public void render(MatrixStack m,int x,int y,float partial){renderBackground(m);super.render(m,x,y,partial);if(popup==0){renderTooltip(m,x,y);if(menu.tab()==1){boolean repeat=menu.stage()>=3||page==1;YagaServices.Entry e=repeat?YagaServices.CONTRACTS[YagaServices.POOL[menu.contract()]]:YagaServices.MAIN[menu.stage()];for(int i=0;i<e.inputs.length;i++)if(x>=leftPos+112+i*34&&x<leftPos+128+i*34&&y>=topPos+77&&y<topPos+93)renderTooltip(m,e.inputs[i].stack(),x,y);}if(menu.tab()==1&&menu.stage()>0&&x>=leftPos+183&&x<leftPos+199&&y>=topPos+96&&y<topPos+112){boolean repeat=menu.stage()>=3||page==1;renderTooltip(m,(repeat?YagaServices.CONTRACTS[YagaServices.POOL[menu.contract()]]:YagaServices.MAIN[menu.stage()]).output(),x,y);}if(menu.tab()==2)for(int row=0;row<3;row++){YagaServices.Entry e=YagaServices.EXCHANGES[page*3+row];if(y>=topPos+44+row*25&&y<topPos+60+row*25){if(x>=leftPos+112&&x<leftPos+128)renderTooltip(m,e.inputs[0].stack(),x,y);if(x>=leftPos+204&&x<leftPos+220)renderTooltip(m,e.output(),x,y);}}if(menu.tab()==3){YagaServices.Entry e=YagaServices.BREWS[menu.recipe()];for(int i=0;i<4;i++)if(menu.input.getItem(i).isEmpty()&&x>=leftPos+126+i*28&&x<leftPos+142+i*28&&y>=topPos+108&&y<topPos+124)renderTooltip(m,e.inputs[i].stack(),x,y);}}else{fill(m,leftPos+30,topPos+35,leftPos+290,topPos+124,0xff241b17);fill(m,leftPos+32,topPos+37,leftPos+288,topPos+122,0xffdac6a1);font.draw(m,tr(popup==1?"help.favor.title":"help.services.title"),leftPos+40,topPos+42,0xff36271b);text(m,tr(popup==1?"help.favor.body":"help.services.body"),leftPos+40,topPos+55,235,7,0xff44382b);font.draw(m,tr("close"),leftPos+274,topPos+41,0xff652c23);}}
 @Override public boolean mouseClicked(double x,double y,int button){if(popup!=0){if(x>=leftPos+270&&y>=topPos+37&&x<=leftPos+290&&y<=topPos+54||x<leftPos+30||x>leftPos+290||y<topPos+35||y>topPos+124)popup=0;return true;}return super.mouseClicked(x,y,button);}
 @Override public boolean keyPressed(int key,int scan,int mods){if(key==256&&popup!=0){popup=0;return true;}return super.keyPressed(key,scan,mods);}
}
