package org.slavicmyths.military;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.nbt.*;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.village.poi.PoiManager;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.levelgen.Heightmap;
import org.slavicmyths.bandit.BanditEntity;
import org.slavicmyths.registry.ModEntities;
/** Small persistent combat events; only loaded camp leaders and active parties are scheduled. */
public final class BanditRaids extends SavedData {
 private final Map<Long,CompoundTag> settlements=new HashMap<>();private final Set<Long> activeKeys=new HashSet<>();
 public static BanditRaids get(ServerLevel l){return l.getDataStorage().computeIfAbsent(new Factory<>(BanditRaids::new,(n,r)->{var s=new BanditRaids();for(Tag t:n.getList("Settlements",10)){var q=(CompoundTag)t;s.settlements.put(q.getLong("Anchor"),q);if(q.getBoolean("Active"))s.activeKeys.add(q.getLong("Anchor"));}return s;}),"slavicmyths_bandit_raids");}
 public CompoundTag save(CompoundTag n,HolderLookup.Provider r){ListTag a=new ListTag();settlements.values().forEach(q->a.add(q.copy()));n.put("Settlements",a);return n;}
 public boolean active(long anchor,UUID id){var q=settlements.get(anchor);return q!=null&&q.getBoolean("Active")&&q.getList("Attackers",10).stream().anyMatch(t->((CompoundTag)t).getUUID("Id").equals(id));}
 public CompoundTag inspect(BlockPos pos){return settlements.getOrDefault(pos.asLong(),new CompoundTag()).copy();}
 public CompoundTag inspectNearest(BlockPos pos){return settlements.values().stream().filter(q->BlockPos.of(q.getLong("Anchor")).distSqr(pos)<=96*96).min(Comparator.comparingDouble(q->BlockPos.of(q.getLong("Anchor")).distSqr(pos))).map(CompoundTag::copy).orElseGet(CompoundTag::new);}
 public void discover(ServerLevel l,BanditEntity leader){if(leader.camp==null||leader.campMember!=0||leader.home==null||leader.getPersistentData().getBoolean("MilitaryRaider"))return;
  if(leader.campTotal==org.slavicmyths.bandit.StrongholdRecords.TOTAL?org.slavicmyths.bandit.StrongholdRecords.get(l).record(leader.camp).cleared:org.slavicmyths.bandit.CampRecords.get(l).isCleared(leader.camp))return;var home=leader.home;var pois=l.getPoiManager();var sites=pois.getInRange(h->h.is(net.minecraft.tags.PoiTypeTags.VILLAGE),home,Military.RAID_SEARCH,PoiManager.Occupancy.ANY).map(x->x.getPos()).filter(l::hasChunkAt).sorted(Comparator.comparingDouble(p->p.distSqr(home))).limit(16).toList();
  BlockPos anchor=sites.stream().filter(l::isVillage).findFirst().orElse(null);if(anchor==null)return;var tables=pois.getInRange(h->h.is(org.slavicmyths.village.VillageRoles.JOBS.get("druzhinnik").getKey()),anchor,48,PoiManager.Occupancy.ANY).map(x->x.getPos()).filter(l::hasChunkAt).findFirst();if(tables.isPresent())anchor=tables.get();
  var q=settlements.computeIfAbsent(anchor.asLong(),k->new CompoundTag());long now=l.getGameTime();if(q.getBoolean("Active")||q.getLong("Cooldown")>now||l.getRaidAt(anchor)!=null)return;q.putLong("Anchor",anchor.asLong());q.putLong("Cooldown",now+Military.RAID_COOLDOWN);q.putUUID("SourceCamp",leader.camp);setDirty();if(l.random.nextInt(Military.RAID_CHANCE)!=0)return;start(l,anchor,leader.camp,false);
 }
 public boolean start(ServerLevel l,BlockPos anchor,UUID camp,boolean test){var q=settlements.computeIfAbsent(anchor.asLong(),k->new CompoundTag());if(q.getBoolean("Active")||l.getRaidAt(anchor)!=null||!test&&q.getLong("LastStart")+Military.RAID_COOLDOWN>l.getGameTime())return false;
  // Separate nearby table positions cannot start overlapping settlement events.
  for(var other:settlements.values())if(other.getBoolean("Active")&&BlockPos.of(other.getLong("Anchor")).distSqr(anchor)<96*96)return false;
  int homes=(int)l.getPoiManager().getInRange(h->h.is(net.minecraft.world.entity.ai.village.poi.PoiTypes.HOME),anchor,48,PoiManager.Occupancy.ANY).count();int size=homes<8?3+l.random.nextInt(3):homes<20?5+l.random.nextInt(4):8+l.random.nextInt(5);ListTag ids=new ListTag();List<BanditEntity> spawned=new ArrayList<>();var city=org.slavicmyths.gorodishche.CitySites.find(l,anchor);
  for(int i=0;i<size;i++){BanditEntity b=null;for(int attempt=0;attempt<16;attempt++){double angle=l.random.nextDouble()*Math.PI*2;BlockPos pos=new BlockPos(anchor.getX()+(int)(Math.cos(angle)*56),anchor.getY(),anchor.getZ()+(int)(Math.sin(angle)*56));if(city.isPresent()){var site=city.get();pos=site.approach().relative(site.outward(),l.random.nextInt(9)).relative(site.outward().getClockWise(),l.random.nextInt(17)-8);if(site.bounds().isInside(pos))continue;}if(!l.hasChunkAt(pos))continue;pos=l.getHeightmapPos(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,pos);BlockPos spawn=pos;if(!l.getBlockState(pos.below()).isSolid()||!l.getBlockState(pos).isAir()||!l.getBlockState(pos.above()).isAir()||l.players().stream().anyMatch(p->p.distanceToSqr(spawn.getCenter())<24*24))continue;
    b=(i%4==3?ModEntities.BANDIT_ARCHER:ModEntities.BANDIT_FIGHTER).get().create(l);b.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,0,0);if(!l.noCollision(b)){b=null;continue;}b.finalizeSpawn(l,l.getCurrentDifficultyAt(pos),MobSpawnType.EVENT,null);b.setPersistenceRequired();b.home=city.map(site->site.approach().relative(site.outward().getOpposite(),20)).orElse(anchor);b.restrictTo(b.home,64);if(!l.addFreshEntity(b)){b=null;continue;}b.getPersistentData().putBoolean("MilitaryRaider",true);b.getPersistentData().putLong("RaidAnchor",anchor.asLong());CompoundTag id=new CompoundTag();id.putUUID("Id",b.getUUID());ids.add(id);spawned.add(b);break;} }
  int minimum=homes<8?3:homes<20?5:8;if(ids.size()<minimum){spawned.forEach(BanditEntity::discard);return false;}q.putLong("Anchor",anchor.asLong());q.putUUID("SourceCamp",camp);q.put("Attackers",ids);q.put("Participants",new ListTag());q.putBoolean("Active",true);activeKeys.add(anchor.asLong());q.putInt("Total",ids.size());q.putLong("LastStart",l.getGameTime());q.putLong("Cooldown",l.getGameTime()+Military.RAID_COOLDOWN);q.putString("EndReason","");setDirty();return true;
 }
 public void killed(ServerLevel l,BanditEntity b,ServerPlayer killer){if(!b.getPersistentData().getBoolean("MilitaryRaider"))return;var q=settlements.get(b.getPersistentData().getLong("RaidAnchor"));if(q==null||!q.getBoolean("Active"))return;var ids=q.getList("Attackers",10);ids.removeIf(t->((CompoundTag)t).getUUID("Id").equals(b.getUUID()));if(killer!=null)participant(q,killer);setDirty();if(ids.isEmpty())finish(l,q,"VICTORY");}
 private void participant(CompoundTag q,ServerPlayer p){var list=q.getList("Participants",10);if(list.stream().noneMatch(t->((CompoundTag)t).getUUID("Id").equals(p.getUUID()))){CompoundTag n=new CompoundTag();n.putUUID("Id",p.getUUID());list.add(n);}}
 public void tick(ServerLevel l){if(activeKeys.isEmpty())return;for(long key:new ArrayList<>(activeKeys)){var q=settlements.get(key);BlockPos anchor=BlockPos.of(q.getLong("Anchor"));if(!l.hasChunkAt(anchor))continue;if(l.getRaidAt(anchor)!=null){finish(l,q,"VANILLA_RAID");continue;}for(var p:l.players())if(p.isAlive()&&!p.isSpectator()&&p.blockPosition().distSqr(anchor)<=64*64)participant(q,p);if(l.getGameTime()-q.getLong("LastStart")>Military.RAID_DURATION)finish(l,q,"TIMEOUT");}setDirty();}
 private void finish(ServerLevel l,CompoundTag q,String reason){q.putBoolean("Active",false);activeKeys.remove(q.getLong("Anchor"));q.putString("EndReason",reason);q.putLong("Cooldown",l.getGameTime()+Military.RAID_COOLDOWN);if(reason.equals("VICTORY"))for(var p:l.players())if(p.isAlive()&&!p.isSpectator()&&p.blockPosition().distSqr(BlockPos.of(q.getLong("Anchor")))<=64*64)participant(q,p);for(Tag t:q.getList("Attackers",10)){var e=l.getEntity(((CompoundTag)t).getUUID("Id"));if(e instanceof BanditEntity b){b.getPersistentData().remove("MilitaryRaider");b.setTarget(null);b.home=null;b.clearRestriction();}}if(reason.equals("VICTORY"))for(Tag t:q.getList("Participants",10)){var p=l.getServer().getPlayerList().getPlayer(((CompoundTag)t).getUUID("Id"));if(p!=null&&p.serverLevel()==l)MilitaryQuests.defended(p,BlockPos.of(q.getLong("Anchor")));}setDirty();}
}
