package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.nbt.*;
import net.minecraft.core.BlockPos;
import org.slavicmyths.hunt.*;
public final class HuntHeadless {
 private static void check(boolean c,String m){if(!c)throw new AssertionError(m);}
 public static void main(String[] args){UUID player=UUID.randomUUID(),mob=UUID.randomUUID();HuntRecords d=new HuntRecords();d.hunts.put(player,new HuntRecords.Hunt(mob,new BlockPos(23,70,12),true,6000));check(d.active(player),"active encounter");
  CompoundTag saved=d.save(new CompoundTag());HuntRecords copy=new HuntRecords();copy.load(saved);check(copy.save(new CompoundTag()).equals(saved)&&copy.active(player),"unloaded encounter/owner/cooldown roundtrip");check(!copy.finish(player,UUID.randomUUID(),HuntRecords.Status.CLEARED)&&copy.active(player),"unknown UUID must not clear an unloaded target");
  check(copy.finish(player,mob,HuntRecords.Status.CLEARED)&&!copy.active(player),"actual death must clear");check(!copy.finish(player,mob,HuntRecords.Status.FAILED)&&copy.hunts.get(player).status==HuntRecords.Status.CLEARED,"double finish changed completed hunt");check(copy.hunts.get(player).ready==6000,"death reset cooldown");
  for(HuntTarget kind:HuntTarget.values()){HuntRecords all=new HuntRecords();all.hunts.put(player,new HuntRecords.Hunt(mob,new BlockPos(20,80,20),kind,6500));HuntRecords loaded=new HuntRecords();loaded.load(all.save(new CompoundTag()));check(loaded.hunts.get(player).kind==kind&&loaded.active(player)&&loaded.hunts.get(player).ready==6500,"Hunt II save type/cooldown");}
  CompoundTag old=saved.copy();old.getList("Hunts",10).getCompound(0).remove("Kind");HuntRecords migrated=new HuntRecords();migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.OVINNIK&&migrated.active(player),"legacy Ovinnik owner migration");old.getList("Hunts",10).getCompound(0).putBoolean("Ovinnik",false);migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.VOLKOLAK,"legacy Volkolak migration");CompoundTag horn=new CompoundTag();horn.putBoolean("Volkolak",true);check(HuntTarget.read(horn,"HuntTarget")==HuntTarget.VOLKOLAK,"legacy horn");HuntTarget cycle=HuntTarget.OVINNIK;Set<HuntTarget> found=new HashSet<>();for(int i=0;i<4;i++){found.add(cycle);cycle=cycle.next();}check(found.size()==4&&cycle==HuntTarget.OVINNIK,"four target cycle");
  check(ElementRules.cooldown(ElementRules.State.ALIGN_DASH,false)==100&&ElementRules.cooldown(ElementRules.State.ALIGN_DASH,true)==120,"rain cooldown");check(ElementRules.fireDamage(10,true)==8&&ElementRules.ignite(60,true)==45,"rain damage and ignition");check(ElementRules.windup(ElementRules.State.ALIGN_DIVE)==24&&ElementRules.windup(ElementRules.State.VORTEX_CHARGE)==20,"Hunt II telegraphs");check(ElementRules.pull(6)<ElementRules.pull(4)&&ElementRules.pull(4)<ElementRules.pull(2),"gradual pull tiers");check(!ElementRules.dangerousFall(5.4F,-.5,false)&&!ElementRules.dangerousFall(6,-.1,false)&&!ElementRules.dangerousFall(6,-.5,true)&&ElementRules.dangerousFall(6,-.5,false),"fall protection guards");check(ElementRules.pushScale(20,false)==1&&ElementRules.pushScale(160,true)==.35&&ElementRules.pushScale(350,false)==.15,"wind pulse resistance");
  HuntRecords legacy=new HuntRecords();legacy.load(new CompoundTag());check(legacy.hunts.isEmpty(),"new save defaults");
  check(HuntRules.belt(false,true)==0&&HuntRules.belt(true,false)==.08&&HuntRules.belt(true,true)==.11,"belt schedule");check(Math.abs(HuntRules.nightSpeed(false,true,true,true,true)-.335*1.07*1.05*1.10)<.0000001,"wolf bonuses");check(HuntRules.nightSpeed(true,true,false,true,true)==.245*1.08,"moon/prey affected Ovinnik");
  check(HuntRules.Move.SLAM.windup==18&&HuntRules.Move.SLAM.recovery==22&&HuntRules.Move.COMBO.cooldown==110&&HuntRules.Move.HOWL.windup==20&&HuntRules.Move.POUNCE.windup==10,"combat timing contracts");for(HuntRules.Move m:HuntRules.Move.values())check(HuntRules.cooldown(m.cooldown,true)>=m.cooldown*.85,"rage reduction exceeds 15 percent");
  // ItemStack copies use deep CompoundTag copies; nested slot data must remain independent.
  CompoundTag pouch=new CompoundTag(),slot=new CompoundTag();slot.putByte("Slot",(byte)3);slot.putString("id","slavicmyths:klyk_volkolaka");slot.putByte("Count",(byte)4);ListTag contents=new ListTag();contents.add(slot);pouch.put("HuntTrophies",contents);CompoundTag clone=pouch.copy();clone.getList("HuntTrophies",10).getCompound(0).putByte("Count",(byte)1);check(pouch.getList("HuntTrophies",10).getCompound(0).getByte("Count")==4,"nested pouch copy alias");
  worldBossChecks();
  System.out.println("PASS: Hunt I+II four targets/legacy migration/rain/fall/push contracts; HuntRecords owner/UUID/cooldown/NBT, unloaded ACTIVE preservation, CLEARED lifecycle, bonus schedules, bounded timings and independent nested pouch NBT. Minecraft launches: 0; GUI/AI runtime not tested.");
 }
 private static void worldBossChecks(){
  int eligible=0;for(int rx=-50;rx<50;rx++)for(int rz=-10;rz<10;rz++){if(BossRules.eligibleRegion(912L,rx,rz,BossKind.LIKHO))eligible++;check(BossRules.eligibleRegion(912L,rx,rz,BossKind.TUGARIN),"eligible plains region rejected");for(BossKind k:BossKind.values()){long seed=BossRules.seed(912L,rx,rz,k);Set<Integer> cells=new HashSet<>();for(int i=0;i<64;i++){int[] p=BossRules.candidate(seed,rx,rz,i);check(Math.floorDiv(p[0],512)==rx&&Math.floorDiv(p[1],512)==rz,"anchor escaped region at negative coordinate");cells.add(Math.floorMod(p[0],512)/64+8*(Math.floorMod(p[1],512)/64));check(Arrays.equals(p,BossRules.candidate(seed,rx,rz,i)),"anchor seed is not deterministic");}check(cells.size()==64,"64 bounded candidates do not cover region");}}
  check(eligible>570&&eligible<830,"Likho regional eligibility departed from 35 percent");
  for(float start:new float[]{-179,-90,0,90,179})for(float goal:new float[]{-179,-90,0,90,179}){float current=start;int count=0;while(!DashFacing.aligned(current,goal,18)&&count++<20){float next=DashFacing.step(current,goal,12);check(Math.abs(DashFacing.wrap(next-current))<=12.001,"body turned instantly");current=next;}check(count<=20&&DashFacing.aligned(current,goal,18),"back/side launch never aligned");}
  check(!DashFacing.aligned(90,0,18)&&!DashFacing.aligned(180,0,25),"side/back dash allowed");
  check(BossRules.phase(BossKind.LIKHO,.66F)==1&&BossRules.phase(BossKind.LIKHO,.65F)==2&&BossRules.phase(BossKind.LIKHO,.30F)==3,"Likho phase thresholds");check(BossRules.phase(BossKind.TUGARIN,.71F)==1&&BossRules.phase(BossKind.TUGARIN,.70F)==2&&BossRules.phase(BossKind.TUGARIN,.35F)==3,"Tugarin phase thresholds");
  HuntRecords d=new HuntRecords();UUID player=UUID.randomUUID(),target=UUID.randomUUID();String key="likho_one_eyed:-1:2";HuntRecords.Boss b=new HuntRecords.Boss(key,BossKind.LIKHO,new BlockPos(-44,72,1111),true);b.owner=player;b.target=target;b.active=true;b.safe=true;d.bosses.put(key,b);d.bossRegions.add(key);d.bossOwners.put(player,key);CompoundTag n=d.save(new CompoundTag());HuntRecords restored=new HuntRecords();restored.load(n);check(restored.bossActive(player)&&restored.bosses.get(key).target.equals(target)&&restored.bossRegions.contains(key),"unloaded boss lost active UUID on save/reload");check(!restored.finishBoss(key,UUID.randomUUID(),1200)&&restored.bossActive(player),"unrelated UUID respawned boss");check(restored.finishBoss(key,target,1200)&&!restored.bossActive(player)&&restored.bosses.get(key).ready==169200,"boss death cooldown not seven days");check(!restored.finishBoss(key,target,5000)&&restored.bosses.get(key).ready==169200,"repeated death reset respawn timer");
  System.out.println("PASS: World Bosses regional coverage and negative coordinates; deterministic anchors and 35% policy; bounded side/back alignment; phase boundaries; active UUID persistence and seven-day death cooldown.");
 }
}
