package org.slavicmyths.verify;
import java.util.*;
import net.minecraft.nbt.*;
import net.minecraft.util.math.BlockPos;
import org.slavicmyths.hunt.*;
public final class HuntHeadless {
 private static void check(boolean c,String m){if(!c)throw new AssertionError(m);}
 public static void main(String[] args){UUID player=UUID.randomUUID(),mob=UUID.randomUUID();HuntRecords d=new HuntRecords();d.hunts.put(player,new HuntRecords.Hunt(mob,new BlockPos(23,70,12),true,6000));check(d.active(player),"active encounter");
  CompoundNBT saved=d.save(new CompoundNBT());HuntRecords copy=new HuntRecords();copy.load(saved);check(copy.save(new CompoundNBT()).equals(saved)&&copy.active(player),"unloaded encounter/owner/cooldown roundtrip");check(!copy.finish(player,UUID.randomUUID(),HuntRecords.Status.CLEARED)&&copy.active(player),"unknown UUID must not clear an unloaded target");
  check(copy.finish(player,mob,HuntRecords.Status.CLEARED)&&!copy.active(player),"actual death must clear");check(!copy.finish(player,mob,HuntRecords.Status.FAILED)&&copy.hunts.get(player).status==HuntRecords.Status.CLEARED,"double finish changed completed hunt");check(copy.hunts.get(player).ready==6000,"death reset cooldown");
  for(HuntTarget kind:HuntTarget.values()){HuntRecords all=new HuntRecords();all.hunts.put(player,new HuntRecords.Hunt(mob,new BlockPos(20,80,20),kind,6500));HuntRecords loaded=new HuntRecords();loaded.load(all.save(new CompoundNBT()));check(loaded.hunts.get(player).kind==kind&&loaded.active(player)&&loaded.hunts.get(player).ready==6500,"Hunt II save type/cooldown");}
  CompoundNBT old=saved.copy();old.getList("Hunts",10).getCompound(0).remove("Kind");HuntRecords migrated=new HuntRecords();migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.OVINNIK&&migrated.active(player),"legacy Ovinnik owner migration");old.getList("Hunts",10).getCompound(0).putBoolean("Ovinnik",false);migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.VOLKOLAK,"legacy Volkolak migration");CompoundNBT horn=new CompoundNBT();horn.putBoolean("Volkolak",true);check(HuntTarget.read(horn,"HuntTarget")==HuntTarget.VOLKOLAK,"legacy horn");HuntTarget cycle=HuntTarget.OVINNIK;Set<HuntTarget> found=new HashSet<>();for(int i=0;i<4;i++){found.add(cycle);cycle=cycle.next();}check(found.size()==4&&cycle==HuntTarget.OVINNIK,"four target cycle");
  check(ElementRules.cooldown(ElementRules.State.ALIGN_DASH,false)==100&&ElementRules.cooldown(ElementRules.State.ALIGN_DASH,true)==120,"rain cooldown");check(ElementRules.fireDamage(10,true)==8&&ElementRules.ignite(60,true)==45,"rain damage and ignition");check(ElementRules.windup(ElementRules.State.ALIGN_DIVE)==24&&ElementRules.windup(ElementRules.State.VORTEX_CHARGE)==20,"Hunt II telegraphs");check(ElementRules.pull(6)<ElementRules.pull(4)&&ElementRules.pull(4)<ElementRules.pull(2),"gradual pull tiers");check(!ElementRules.dangerousFall(5.4F,-.5,false)&&!ElementRules.dangerousFall(6,-.1,false)&&!ElementRules.dangerousFall(6,-.5,true)&&ElementRules.dangerousFall(6,-.5,false),"fall protection guards");check(ElementRules.pushScale(20,false)==1&&ElementRules.pushScale(160,true)==.35&&ElementRules.pushScale(350,false)==.15,"wind pulse resistance");
  HuntRecords legacy=new HuntRecords();legacy.load(new CompoundNBT());check(legacy.hunts.isEmpty(),"new save defaults");
  check(HuntRules.belt(false,true)==0&&HuntRules.belt(true,false)==.08&&HuntRules.belt(true,true)==.11,"belt schedule");check(Math.abs(HuntRules.nightSpeed(false,true,true,true,true)-.335*1.07*1.05*1.10)<.0000001,"wolf bonuses");check(HuntRules.nightSpeed(true,true,false,true,true)==.245*1.08,"moon/prey affected Ovinnik");
  check(HuntRules.Move.SLAM.windup==18&&HuntRules.Move.SLAM.recovery==22&&HuntRules.Move.COMBO.cooldown==110&&HuntRules.Move.HOWL.windup==20&&HuntRules.Move.POUNCE.windup==10,"combat timing contracts");for(HuntRules.Move m:HuntRules.Move.values())check(HuntRules.cooldown(m.cooldown,true)>=m.cooldown*.85,"rage reduction exceeds 15 percent");
  // ItemStack copies use deep CompoundNBT copies; nested slot data must remain independent.
  CompoundNBT pouch=new CompoundNBT(),slot=new CompoundNBT();slot.putByte("Slot",(byte)3);slot.putString("id","slavicmyths:klyk_volkolaka");slot.putByte("Count",(byte)4);ListNBT contents=new ListNBT();contents.add(slot);pouch.put("HuntTrophies",contents);CompoundNBT clone=pouch.copy();clone.getList("HuntTrophies",10).getCompound(0).putByte("Count",(byte)1);check(pouch.getList("HuntTrophies",10).getCompound(0).getByte("Count")==4,"nested pouch copy alias");
  System.out.println("PASS: Hunt I+II four targets/legacy migration/rain/fall/push contracts; HuntRecords owner/UUID/cooldown/NBT, unloaded ACTIVE preservation, CLEARED lifecycle, bonus schedules, bounded timings and independent nested pouch NBT. Minecraft launches: 0; GUI/AI runtime not tested.");
 }
}
