package org.slavicmyths.verify;
import java.util.UUID;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.core.BlockPos;
import org.slavicmyths.yaga.*;
import java.util.*;
public final class YagaHeadless {
 private static void check(boolean ok,String why){if(!ok)throw new AssertionError(why);}
 public static void main(String[] args){YagaData d=new YagaData();UUID player=UUID.randomUUID(),npc=UUID.randomUUID();d.anchor=new BlockPos(-1200,80,750);d.npc=npc;d.placed=true;d.examined.add(99L);YagaData.Progress p=d.progress(player);
  check(p.favor()==YagaData.Favor.STRANGER&&!p.rewardsVisible(),"stranger reward disclosure");check(!p.accept("main:1",0),"sequence bypass");check(p.accept("main:0",0)&&!p.accept("main:0",0),"duplicate acceptance");check(!p.completeMain(1)&&p.completeMain(0)&&!p.completeMain(0),"repeat reward or quest bypass");check(p.favor()==YagaData.Favor.GUEST&&p.rewardsVisible(),"guest unlock");check(p.accept("main:1",0)&&p.completeMain(1)&&p.favor()==YagaData.Favor.GUEST,"mid progression");check(p.accept("main:2",0)&&p.completeMain(2)&&p.favor()==YagaData.Favor.TRUSTED,"trusted unreachable");
  check(p.accept("contract:0",0)&&p.completeContract(0,10)&&!p.completeContract(0,10)&&!p.accept("contract:1",11),"contract duplicate or cooldown bypass");check(p.accept("contract:1",24010),"contract never reopens");check(!p.attack(25000,false)&&p.attack(25001,false)&&p.blocked(49000)&&!p.blocked(49001),"warning/temporary block boundaries");check(!p.accept("main:0",25001),"blocked service accepted");
  CompoundTag saved=d.save(new CompoundTag(),net.minecraft.core.RegistryAccess.fromRegistryOfRegistries(net.minecraft.core.registries.BuiltInRegistries.REGISTRY));YagaData copy=new YagaData();copy.load(saved);YagaData.Progress restored=copy.progress(player);check(copy.anchor.equals(d.anchor)&&copy.npc.equals(npc)&&copy.placed&&copy.examined.contains(99L),"home/UUID persistence");check(restored.favor()==YagaData.Favor.TRUSTED&&restored.active.equals(p.active)&&restored.blockedUntil==p.blockedUntil&&restored.contractReady==p.contractReady,"progress/death/logout persistence");check(copy.progress(UUID.randomUUID()).favor()==YagaData.Favor.STRANGER,"cross-player progress leak");
  for(int stage=1;stage<=3;stage++){int index=0;Set<Integer> seen=new HashSet<>();for(int i=0;i<28;i++){index=YagaServices.nextContract(stage,index);check(index>=0&&index<14,"pool index escaped bounds");check(stage==3||YagaServices.POOL[index]<4,"early player offered rare boss contract");seen.add(YagaServices.POOL[index]);}check(seen.size()==(stage==3?6:4),"finite contract pool misses target");}
  CompoundTag malformed=new CompoundTag();malformed.putLong("Anchor",BlockPos.ZERO.asLong());malformed.putBoolean("Placed",true);net.minecraft.nbt.ListTag plist=new net.minecraft.nbt.ListTag();CompoundTag bad=new CompoundTag();bad.putUUID("Player",player);bad.putInt("Stage",1);bad.putInt("Contract",8);bad.putString("Active","contract:8");plist.add(bad);malformed.put("Players",plist);YagaData repaired=new YagaData();repaired.load(malformed);check(YagaServices.POOL[repaired.progress(player).contract]<4&&repaired.progress(player).active.isEmpty(),"old/malformed rare contract strands guest");
  YagaHutPlan plan=new YagaHutPlan();check(plan.blocks.size()<5000,"unbounded hut blueprint");check(plan.blocks.get(YagaHutPlan.HOME).equals("minecraft:air")&&plan.blocks.get(YagaHutPlan.HOME.above()).equals("minecraft:air"),"NPC obstructed by furnishings");check(plan.blocks.get(YagaHutPlan.HOME.offset(-2,0,1)).equals("slavicmyths:yaga_cauldron"),"service anchor and hut disagree");
  for(int x=-5;x<=5;x++)for(int z=-6;z<=6;z++)check(plan.blocks.containsKey(new BlockPos(x,3,z)),"floor hole");for(int x:new int[]{-3,3}){for(int dx=-1;dx<=1;dx++)check(plan.blocks.get(new BlockPos(x+dx,0,-3)).contains("part=4"),"missing front claw");check(plan.blocks.get(new BlockPos(x,0,2)).contains("part=4"),"missing rear claw");check(plan.blocks.get(new BlockPos(x,2,0)).contains("part=1"),"straight pillar leg");}
  check(plan.blocks.get(new BlockPos(0,4,-6)).contains("half=lower")&&plan.blocks.get(new BlockPos(0,5,-6)).contains("half=upper"),"incomplete entrance");for(int z=-5;z<=1;z++)for(int y=4;y<=5;y++)check(plan.blocks.get(new BlockPos(0,y,z)).equals("minecraft:air"),"entry route obstructed");
  for(BlockPos pos:plan.blocks.keySet())check(Math.abs(pos.getX())<=9&&pos.getZ()>=-16&&pos.getZ()<=9&&pos.getY()>=-1&&pos.getY()<=13,"blueprint outside loading/rollback box");
  for(long seed:new long[]{0,-1,Long.MIN_VALUE,42,2026}){BlockPos spawn=new BlockPos(-1500,70,1900);List<BlockPos> sites=YagaHutPlan.candidates(seed,spawn);check(sites.size()==64&&sites.equals(YagaHutPlan.candidates(seed,spawn)),"unstable/unbounded candidates");for(BlockPos site:sites){double dx=site.getX()-spawn.getX(),dz=site.getZ()-spawn.getZ(),radius=Math.sqrt(dx*dx+dz*dz);check(radius>=800&&radius<=2500,"hut outside requested spawn radius");}}
  if(args.length==1){try{java.nio.file.Path path=java.nio.file.Paths.get(args[0]);java.nio.file.Files.createDirectories(path.getParent());StringBuilder json=new StringBuilder("[\n");boolean first=true;for(Map.Entry<BlockPos,String> e:plan.blocks.entrySet()){if(!first)json.append(",\n");first=false;BlockPos b=e.getKey();json.append("{\"x\":").append(b.getX()).append(",\"y\":").append(b.getY()).append(",\"z\":").append(b.getZ()).append(",\"block\":\"").append(e.getValue()).append("\"}");}json.append("\n]\n");java.nio.file.Files.write(path,json.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(java.io.IOException ex){throw new IllegalStateException(ex);}}
  System.out.println("PASS: Yaga progression, reward visibility, idempotent completion, finite contract cooldown, temporary punishment, independent player NBT, unloaded NPC UUID, malformed contract repair, bounded seeded hut placement, floor, entrance, service anchor and articulated 3+1 claw geometry. No Minecraft launch.");}
}
