package org.slavicmyths.storage;
import com.mojang.serialization.MapCodec;
import net.minecraft.core.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.*;
import net.minecraft.world.level.block.state.*;
import net.minecraft.world.level.block.state.properties.*;
import net.minecraft.world.phys.*;
import net.minecraft.world.phys.shapes.*;
import org.slavicmyths.storage.Household.Kind;
public class StorageBlock extends HorizontalDirectionalBlock implements EntityBlock{
 public static final IntegerProperty PART=IntegerProperty.create("part",0,3),FILL=IntegerProperty.create("fill",0,4),LEVEL=IntegerProperty.create("level",1,4);public static final EnumProperty<DoubleBlockHalf> HALF=BlockStateProperties.DOUBLE_BLOCK_HALF;public static final BooleanProperty OPEN=BooleanProperty.create("open"),BREWING=BooleanProperty.create("brewing");public final Kind kind;
 private static final MapCodec<StorageBlock>CODEC=com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(i->i.group(com.mojang.serialization.Codec.STRING.fieldOf("kind").forGetter(b->b.kind.name()),propertiesCodec()).apply(i,(s,p)->create(Kind.valueOf(s),p)));
 public static StorageBlock create(Kind k,Properties p){return k==Kind.BARREL?new Barrel(p):k==Kind.SACK?new Sack(p):k==Kind.CHEST?new Chest(p):k==Kind.HAY?new Hay(p):k==Kind.SHELF?new Vertical(k,p):k==Kind.DRY?new Multi(k,p):new StorageBlock(k,p);}
 public StorageBlock(Kind k){this(k,Properties.ofFullCopy(Blocks.OAK_PLANKS).strength(k==Kind.HAY?.5F:2).noOcclusion());}protected StorageBlock(Kind k,Properties p){super(p);kind=k;registerDefaultState(stateDefinition.any().setValue(FACING,Direction.NORTH));}
 protected MapCodec<? extends StorageBlock>codec(){return CODEC;}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){b.add(FACING);}
 public static class Barrel extends StorageBlock{private Barrel(Properties p){super(Kind.BARREL,p);registerDefaultState(defaultBlockState().setValue(BREWING,false));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(BREWING);}}
 public static class Sack extends StorageBlock{public Sack(){this(Properties.ofFullCopy(Blocks.OAK_PLANKS).strength(2).noOcclusion());}private Sack(Properties p){super(Kind.SACK,p);registerDefaultState(defaultBlockState().setValue(FILL,0));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(FILL);}}
 public static class Chest extends StorageBlock{public Chest(){this(Properties.ofFullCopy(Blocks.OAK_PLANKS).strength(2).noOcclusion());}private Chest(Properties p){super(Kind.CHEST,p);registerDefaultState(defaultBlockState().setValue(OPEN,false));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(OPEN);}}
 public static class Multi extends StorageBlock{public Multi(Kind k){this(k,Properties.ofFullCopy(Blocks.OAK_PLANKS).strength(2).noOcclusion());}protected Multi(Kind k,Properties p){super(k,p);registerDefaultState(defaultBlockState().setValue(PART,0));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(PART);}}
 public static class Vertical extends StorageBlock{public Vertical(Kind k){this(k,Properties.ofFullCopy(Blocks.OAK_PLANKS).strength(2).noOcclusion());}protected Vertical(Kind k,Properties p){super(k,p);registerDefaultState(defaultBlockState().setValue(HALF,DoubleBlockHalf.LOWER));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(HALF);}}
 public static class Hay extends Vertical{public Hay(){this(Properties.ofFullCopy(Blocks.HAY_BLOCK).strength(.5F).noOcclusion());}private Hay(Properties p){super(Kind.HAY,p);registerDefaultState(defaultBlockState().setValue(LEVEL,1));}protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){super.createBlockStateDefinition(b);b.add(LEVEL);}}
 public int part(BlockState s){return kind==Kind.DRY?s.getValue(PART):kind.multi()?s.getValue(HALF)==DoubleBlockHalf.LOWER?0:2:0;}
 public BlockPos master(BlockState s,BlockPos p){int part=part(s);return p.below(part/2).relative(s.getValue(FACING).getClockWise(),-(part%2));}
 public BlockState partState(BlockState s,int part){return kind==Kind.DRY?s.setValue(PART,part):s.setValue(HALF,part==0?DoubleBlockHalf.LOWER:DoubleBlockHalf.UPPER);}
 public int[] parts(){return kind==Kind.DRY?new int[]{0,1,2,3}:kind.multi()?new int[]{0,2}:new int[]{0};}
 public BlockPos position(BlockState s,BlockPos master,int part){return master.above(part/2).relative(s.getValue(FACING).getClockWise(),part%2);}
 public BlockState getStateForPlacement(BlockPlaceContext c){BlockState s=defaultBlockState().setValue(FACING,c.getHorizontalDirection().getOpposite());if(kind==Kind.WALL){if(c.getClickedFace().getAxis()==Direction.Axis.Y)return null;s=s.setValue(FACING,c.getClickedFace());if(!canSurvive(s,c.getLevel(),c.getClickedPos()))return null;}
  for(int part:parts()){BlockPos q=position(s,c.getClickedPos(),part);if(!c.getLevel().getWorldBorder().isWithinBounds(q)||q.getY()>=c.getLevel().getMaxBuildHeight()||part!=0&&!c.getLevel().getBlockState(q).canBeReplaced(c))return null;}return s;}
 public void setPlacedBy(Level w,BlockPos p,BlockState s,net.minecraft.world.entity.LivingEntity e,ItemStack stack){if(kind.multi()){for(int part:parts())if(part!=0)w.setBlock(position(s,p,part),partState(s,part),2);for(int part:parts())w.updateNeighborsAt(position(s,p,part),this);}}
 public boolean canSurvive(BlockState s,LevelReader w,BlockPos p){if(kind!=Kind.WALL)return true;BlockPos back=p.relative(s.getValue(FACING).getOpposite());return w.getBlockState(back).isFaceSturdy(w,back,s.getValue(FACING));}
 public BlockState updateShape(BlockState s,Direction d,BlockState other,LevelAccessor w,BlockPos p,BlockPos q){if(kind==Kind.WALL&&!canSurvive(s,w,p))return Blocks.AIR.defaultBlockState();if(kind.multi()){BlockPos master=master(s,p);if(part(s)!=0){BlockState m=w.getBlockState(master);if(!m.is(this)||part(m)!=0||m.getValue(FACING)!=s.getValue(FACING))return Blocks.AIR.defaultBlockState();}else for(int part:parts())if(part!=0&&q.equals(position(s,master,part))&&(!other.is(this)||part(other)!=part||other.getValue(FACING)!=s.getValue(FACING)))return Blocks.AIR.defaultBlockState();}return super.updateShape(s,d,other,w,p,q);}
 public BlockEntity newBlockEntity(BlockPos p,BlockState s){return part(s)==0?new StorageTile(p,s):null;}
 @SuppressWarnings("unchecked")public <T extends BlockEntity>BlockEntityTicker<T>getTicker(Level w,BlockState s,BlockEntityType<T>t){return !w.isClientSide&&(kind==Kind.DRY||kind==Kind.BARREL&&s.getValue(BREWING))&&part(s)==0&&t==Household.TYPE.get()?(l,p,st,tile)->StorageTile.tick(l,p,st,(StorageTile)tile):null;}
 public StorageTile tile(Level w,BlockPos p,BlockState s){return w.getBlockEntity(master(s,p))instanceof StorageTile t?t:null;}
 public InteractionResult useWithoutItem(BlockState s,Level w,BlockPos p,Player player,BlockHitResult hit){return useItemOn(player.getMainHandItem(),s,w,p,player,InteractionHand.MAIN_HAND,hit).result();}
 public ItemInteractionResult useItemOn(ItemStack held,BlockState s,Level w,BlockPos p,Player player,InteractionHand hand,BlockHitResult hit){if(player.isSpectator())return ItemInteractionResult.PASS_TO_DEFAULT_BLOCK_INTERACTION;StorageTile t=tile(w,p,s);if(t!=null){if(kind==Kind.BARREL&&t.fermentation.interact(t,player,hand))return ItemInteractionResult.sidedSuccess(w.isClientSide);if(kind==Kind.CHEST||kind==Kind.BARREL||kind==Kind.CRATE){if(!w.isClientSide)((net.minecraft.server.level.ServerPlayer)player).openMenu(t);}else t.interact(player,hand,hit);}return ItemInteractionResult.sidedSuccess(w.isClientSide);}
 public void onRemove(BlockState s,Level w,BlockPos p,BlockState next,boolean moving){if(!s.is(next.getBlock())&&!w.isClientSide){BlockPos master=master(s,p);if(part(s)==0&&w.getBlockEntity(p)instanceof StorageTile t){t.dropAll();if(kind.multi()&&kind!=Kind.HAY)popResource(w,p,new ItemStack(this));}if(kind.multi())for(int part:parts()){BlockPos q=position(s,master,part);if(q.equals(p))continue;BlockState old=w.getBlockState(q);if(old.is(this)&&part(old)==part&&old.getValue(FACING)==s.getValue(FACING))w.removeBlock(q,false);}}super.onRemove(s,w,p,next,moving);}
 public VoxelShape getShape(BlockState s,BlockGetter w,BlockPos p,CollisionContext c){VoxelShape sh=switch(kind){case SACK->box(3,0,3,13,7+s.getValue(FILL)*2,13);case BASKET->box(2,0,2,14,11,14);case LARGE,CRATE->box(1,0,1,15,11,15);case CHEST->box(1,0,1,15,11,15);case BARREL->box(1,0,1,15,16,15);case WALL->Shapes.or(box(0,7,10,16,9,16),box(2,2,13,4,7,16),box(12,2,13,14,7,16));case SHELF->Shapes.or(box(1,0,3,3,part(s)==0?16:13,14),box(13,0,3,15,part(s)==0?16:13,14),box(1,part(s)==0?5:7,3,15,part(s)==0?7:9,14));case DRY->Shapes.or(box(part(s)%2==0?1:13,0,6,part(s)%2==0?3:15,16,10),box(0,part(s)<2?2:12,6,16,part(s)<2?4:14,10));case HAY->{double height=s.getValue(LEVEL)==1?9:s.getValue(LEVEL)==2?14:s.getValue(LEVEL)==3?22:29;double top=Math.max(0,Math.min(16,height-part(s)/2*16));yield top==0?Shapes.empty():box(2,0,2,14,top,14);}};
  int turns=s.getValue(FACING)==Direction.NORTH?0:s.getValue(FACING)==Direction.EAST?1:s.getValue(FACING)==Direction.SOUTH?2:3;for(int i=0;i<turns;i++){final VoxelShape[]n={Shapes.empty()};sh.forAllBoxes((a,b,z,d,e,f)->n[0]=Shapes.or(n[0],Shapes.box(1-f,b,a,1-z,e,d)));sh=n[0];}return sh;}
 public BlockState rotate(BlockState s,Rotation r){return s.setValue(FACING,r.rotate(s.getValue(FACING)));}public BlockState mirror(BlockState s,Mirror m){return rotate(s,m.getRotation(s.getValue(FACING)));}
 public int getFlammability(BlockState s,BlockGetter w,BlockPos p,Direction d){return kind==Kind.HAY?60:kind==Kind.SACK?40:20;}public int getFireSpreadSpeed(BlockState s,BlockGetter w,BlockPos p,Direction d){return kind==Kind.HAY?60:5;}
}
