from pathlib import Path
p=Path('src/main/java/org/slavicmyths/hunt/HuntSpawns.java');s=p.read_text().replace('airVolume(w,p.below(2),2,5)','airVolume(w,p.getY()-ground.getY()>=4?p.below(2):p,2,5)');p.write_text(s,encoding='utf8')
p=Path('tools/verify_resources.py');s=p.read_text();s=s.replace("hunt=read(ROOT/'docs/verification/hunt-0.9.0.json')","hunt=read(ROOT/'docs/verification/hunt-0.9.0.json')\nhunt2=read(ROOT/'docs/verification/hunt-0.9.1.json')")
s=s.replace("            # Existing user-authored", "            if path.parent.name == 'item' and path.stem in hunt2['items']: expected=(256,256) if path.stem in hunt2['small_items'] else (512,512)\n            if path.parent.name == 'entity' and path.stem in hunt2['entities']: expected=(512,512)\n            # Existing user-authored")
s=s.replace("    if entity=='ember_clump':", "    if entity=='serpent_projection':\n        assert 'ModEntities.SERPENT_PROJECTION.get()' in (JAVA/'client/ClientSetup.java').read_text()\n        continue\n    if entity in hunt2['entities']:\n        assert (RES/f'assets/slavicmyths/textures/entity/{entity}.png').is_file()\n        assert (RES/f'data/slavicmyths/loot_tables/entities/{entity}.json').is_file()\n        assert (JAVA/'client/ElementModel.java').is_file() and (JAVA/'client/ElementRenderer.java').is_file()\n        assert 'ModEntities.'+entity.upper()+'.get()' in (JAVA/'client/ClientSetup.java').read_text()\n        continue\n    if entity=='ember_clump':")
p.write_text(s,encoding='utf8')
# Hunt I generation must not erase additive tags from a later extension.
p=Path('tools/hunt_090.py');s=p.read_text();s=s.replace('def generate():','''def tagwrite(path,obj):
 if path.exists():obj['values']=list(dict.fromkeys(json.loads(path.read_text(encoding='utf-8'))['values']+obj['values']))
 write(path,obj)

def generate():''');s=s.replace("write(D/'tags/items/hunt_trophies.json'","tagwrite(D/'tags/items/hunt_trophies.json'").replace("write(D/'tags/entity_types/hunt_targets.json'","tagwrite(D/'tags/entity_types/hunt_targets.json'");p.write_text(s,encoding='utf8')
p=Path('tools/verify_hunt_090.py');s=p.read_text().replace("set(read(D/'tags/items/hunt_trophies.json')['values'])==","set(read(D/'tags/items/hunt_trophies.json')['values'])>=").replace("set(read(D/'tags/entity_types/hunt_targets.json')['values'])==","set(read(D/'tags/entity_types/hunt_targets.json')['values'])>=");p.write_text(s,encoding='utf8')
p=Path('tools/create_resources.py');s=p.read_text();s+='\n# Hunt II extends Hunt I after its resource layer.\nfrom hunt_091 import generate as hunt_091_generate\nhunt_091_generate()\n';p.write_text(s,encoding='utf8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/HuntHeadless.java');s=p.read_text();s=s.replace('  HuntRecords legacy=new HuntRecords();','''  for(HuntTarget kind:HuntTarget.values()){HuntRecords all=new HuntRecords();all.hunts.put(player,new HuntRecords.Hunt(mob,new BlockPos(20,80,20),kind,6500));HuntRecords loaded=new HuntRecords();loaded.load(all.save(new CompoundNBT()));check(loaded.hunts.get(player).kind==kind&&loaded.active(player)&&loaded.hunts.get(player).ready==6500,"Hunt II save type/cooldown");}
  CompoundNBT old=saved.copy();old.getList("Hunts",10).getCompound(0).remove("Kind");HuntRecords migrated=new HuntRecords();migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.OVINNIK&&migrated.active(player),"legacy Ovinnik owner migration");old.getList("Hunts",10).getCompound(0).putBoolean("Ovinnik",false);migrated.load(old);check(migrated.hunts.get(player).kind==HuntTarget.VOLKOLAK,"legacy Volkolak migration");CompoundNBT horn=new CompoundNBT();horn.putBoolean("Volkolak",true);check(HuntTarget.read(horn,"HuntTarget")==HuntTarget.VOLKOLAK,"legacy horn");HuntTarget cycle=HuntTarget.OVINNIK;Set<HuntTarget> found=new HashSet<>();for(int i=0;i<4;i++){found.add(cycle);cycle=cycle.next();}check(found.size()==4&&cycle==HuntTarget.OVINNIK,"four target cycle");
  check(ElementRules.cooldown(ElementRules.State.ALIGN_DASH,false)==100&&ElementRules.cooldown(ElementRules.State.ALIGN_DASH,true)==120,"rain cooldown");check(ElementRules.fireDamage(10,true)==8&&ElementRules.ignite(60,true)==45,"rain damage and ignition");check(ElementRules.windup(ElementRules.State.ALIGN_DIVE)==24&&ElementRules.windup(ElementRules.State.VORTEX_CHARGE)==20,"Hunt II telegraphs");check(ElementRules.pull(6)<ElementRules.pull(4)&&ElementRules.pull(4)<ElementRules.pull(2),"gradual pull tiers");check(!ElementRules.dangerousFall(5.4F,-.5,false)&&!ElementRules.dangerousFall(6,-.1,false)&&!ElementRules.dangerousFall(6,-.5,true)&&ElementRules.dangerousFall(6,-.5,false),"fall protection guards");check(ElementRules.pushScale(20,false)==1&&ElementRules.pushScale(160,true)==.35&&ElementRules.pushScale(350,false)==.15,"wind pulse resistance");
  HuntRecords legacy=new HuntRecords();''');s=s.replace('PASS: HuntRecords owner/UUID','PASS: Hunt I+II four targets/legacy migration/rain/fall/push contracts; HuntRecords owner/UUID');p.write_text(s,encoding='utf8')
