from pathlib import Path
r=Path('src/main/java/org/slavicmyths')
p=r/'yaga/YagaLegBlock.java';s=p.read_text().replace('create("part",0,4)','create("part",0,6)').replace('if(part==2)return box(5,0,5,11,16,11);','if(part==2)return box(5,0,5,11,16,11);if(part==6)return box(3,0,0,13,16,16);if(part==5)return box(0,0,0,16,4,16);');p.write_text(s,'utf-8')
p=r/'yaga/YagaHutPlan.java';s=p.read_text().replace('b(x,0,0,"slavicmyths:yaga_chicken_leg[part=2]")','b(x,0,0,"slavicmyths:yaga_chicken_leg[part=6]")').replace('b(x+dx,0,-1,"slavicmyths:yaga_chicken_leg[part=3]")','b(x+dx,0,-1,"slavicmyths:yaga_chicken_leg[part=5]")');p.write_text(s,'utf-8')
p=Path('tools/yaga_093.py');s=p.read_text();s=s.replace("([6,0,0],[10,4,12])]", "([6,0,6],[10,4,16]),([6,0,0],[10,4,16]),([5,0,5],[11,16,11])]");s=s.replace("'scales' if part<4 else 'claw'", "'claw' if part==4 else 'scales'");s=s.replace("if part==4:elements.extend([cub([6,0,-0],[10,3,5],'claw'),cub([7,0,0],[9,2,3],'claw')])", "if part==4:elements.extend([cub([6.5,0,3],[9.5,3,9],'claw'),cub([7,0,0],[9,2,5],'claw')])\n if part==5:elements.append(cub([0,0,12],[16,4,16],'scales'))\n if part==6:elements.append(cub([3,0,0],[13,4,16],'scales'))")
s=s.replace('for part in range(5) for face','for part in range(7) for face').replace('8 items, 3 world-only blocks','8 items, 4 world-only blocks');p.write_text(s,'utf-8')
# Pure test export gives the visual review the real blueprint, not a separate mock house.
p=Path('tools/kurgan-tests/org/slavicmyths/verify/YagaHeadless.java');s=p.read_text();needle='  System.out.println("PASS:';idx=s.index(needle);s=s[:idx]+'''  if(args.length==1){try{java.nio.file.Path path=java.nio.file.Paths.get(args[0]);java.nio.file.Files.createDirectories(path.getParent());StringBuilder json=new StringBuilder("[\\n");boolean first=true;for(Map.Entry<BlockPos,String> e:plan.blocks.entrySet()){if(!first)json.append(",\\n");first=false;BlockPos b=e.getKey();json.append("{\\"x\\":").append(b.getX()).append(",\\"y\\":").append(b.getY()).append(",\\"z\\":").append(b.getZ()).append(",\\"block\\":\\"").append(e.getValue()).append("\\"}");}json.append("\\n]\\n");java.nio.file.Files.write(path,json.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(java.io.IOException ex){throw new IllegalStateException(ex);}}
'''+s[idx:];p.write_text(s,'utf-8')
p=Path('build.gradle');s=p.read_text().replace("mainClass = 'org.slavicmyths.verify.YagaHeadless'", "mainClass = 'org.slavicmyths.verify.YagaHeadless'\n    args file('docs/verification/yaga-0.9.3/hut-plan.json').absolutePath");p.write_text(s,'utf-8')
