from pathlib import Path
p=Path('src/main/java/org/slavicmyths/registry/ModEntities.java');s=p.read_text(encoding='utf-8').replace('.sized(1.5F,1.6F).clientTrackingRange(10).build("slavicmyths:ovinnik")','.sized(1.15F,2.45F).clientTrackingRange(12).fireImmune().build("slavicmyths:ovinnik")');a=s.index('    private ModEntities()');s=s[:a]+'''    public static final RegistryObject<EntityType<org.slavicmyths.entity.VolkolakEntity>> VOLKOLAK=ENTITIES.register("volkolak",()->EntityType.Builder.of(org.slavicmyths.entity.VolkolakEntity::new,EntityClassification.MONSTER).sized(1.05F,2.25F).clientTrackingRange(12).build("slavicmyths:volkolak"));
    public static final RegistryObject<EntityType<org.slavicmyths.hunt.EmberClump>> EMBER_CLUMP=ENTITIES.register("ember_clump",()->EntityType.Builder.of(org.slavicmyths.hunt.EmberClump::new,EntityClassification.MISC).sized(.3F,.3F).clientTrackingRange(8).updateInterval(2).build("slavicmyths:ember_clump"));
'''+s[a:];s=s.replace('        event.put(OVINNIK.get(),','        event.put(VOLKOLAK.get(),org.slavicmyths.entity.VolkolakEntity.attributes().build());\n        event.put(OVINNIK.get(),');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/registry/ModItems.java');s=p.read_text(encoding='utf-8').replace('ModEntities.OVINNIK, 0x494137, 0xbca981','ModEntities.OVINNIK, 0x2C2722, 0xE34A18');a=s.index('    private ModItems()');fields=''
for name,role,stack,rarity in [('ovinnaya_zola','ASH',64,''),('iskra_ovinnika','SPARK',16,'UNCOMMON'),('klyk_volkolaka','FANG',32,''),('nochnoy_kogot','CLAW',16,'UNCOMMON'),('obereg_ohotnika','DETECTOR',1,'RARE'),('ohotnichiy_rog','HORN',1,''),('meshochek_trofeev','POUCH',1,''),('pustoy_ritualny_sosud','VESSEL',16,'UNCOMMON')]:
 props=f'properties().stacksTo({stack})'+(f'.rarity(Rarity.{rarity})' if rarity else '')
 fields+=f'    public static final RegistryObject<Item> {name.upper()}=ITEMS.register("{name}",()->new org.slavicmyths.hunt.HuntItems({props},org.slavicmyths.hunt.HuntItems.Role.{role}));\n'
for name,slot in [('zolny_obereg','necklace'),('volchiy_poyas','belt')]:fields+=f'    public static final RegistryObject<Item> {name.upper()}=ITEMS.register("{name}",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"{slot}"));\n'
fields+='    public static final RegistryObject<Item> VOLKOLAK_SPAWN_EGG=egg("volkolak_spawn_egg",ModEntities.VOLKOLAK,0x3D3A38,0x9A1F27);\n';p.write_text(s[:a]+fields+s[a:],encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/SlavicMyths.java');s=p.read_text(encoding='utf-8').replace('        org.slavicmyths.flight.CargoMenu.register();','        org.slavicmyths.hunt.PouchMenu.register();\n        org.slavicmyths.flight.CargoMenu.register();').replace('        event.enqueueWork(SpiritSpawns::registerPlacements);','        event.enqueueWork(org.slavicmyths.hunt.HuntSpawns::placements);\n        event.enqueueWork(SpiritSpawns::registerPlacements);');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/client/ClientSetup.java');s=p.read_text(encoding='utf-8').replace('        RenderingRegistry.registerEntityRenderingHandler(ModEntities.OVINNIK.get(), OvinnikRenderer::new);','        RenderingRegistry.registerEntityRenderingHandler(ModEntities.OVINNIK.get(), m->new HuntRenderer<org.slavicmyths.entity.OvinnikEntity>(m,true));\n        RenderingRegistry.registerEntityRenderingHandler(ModEntities.VOLKOLAK.get(), m->new HuntRenderer<org.slavicmyths.entity.VolkolakEntity>(m,false));\n        RenderingRegistry.registerEntityRenderingHandler(ModEntities.EMBER_CLUMP.get(),m->new net.minecraft.client.renderer.entity.SpriteRenderer<>(m,net.minecraft.client.Minecraft.getInstance().getItemRenderer()));');s=s.replace('        event.enqueueWork(() -> {','        event.enqueueWork(() -> {\n            net.minecraft.client.gui.ScreenManager.register(org.slavicmyths.hunt.PouchMenu.TYPE.get(),PouchScreen::new);',1);p.write_text(s,encoding='utf-8')
p=Path('build.gradle');p.write_text(p.read_text(encoding='utf-8').replace("version = '0.8.6'","version = '0.9.0'"),encoding='utf-8')
