from pathlib import Path
r=Path('src/main/java/org/slavicmyths')
def edit(p,a,b):
 p=r/p;s=p.read_text(encoding='utf8');assert a in s,(p,a[:80]);p.write_text(s.replace(a,b),encoding='utf8')
(r/'hunt/HuntTarget.java').write_text('''package org.slavicmyths.hunt;
/** Stable save IDs; old boolean horn/encounter tags migrate without losing ownership. */
public enum HuntTarget {
 OVINNIK("ovinnik"), VOLKOLAK("volkolak"), FIRE_SERPENT("fire_serpent"), PODVEY("podvey");
 public final String id;HuntTarget(String id){this.id=id;}
 public HuntTarget next(){return values()[(ordinal()+1)%values().length];}
 public static HuntTarget read(net.minecraft.nbt.CompoundNBT n,String key){for(HuntTarget t:values())if(t.id.equals(n.getString(key)))return t;return n.getBoolean("Volkolak")||n.contains("Ovinnik")&&!n.getBoolean("Ovinnik")?VOLKOLAK:OVINNIK;}
}
''',encoding='utf8')
edit('hunt/HuntRecords.java','public boolean oven;','public boolean oven;public HuntTarget kind;')
edit('hunt/HuntRecords.java','this.oven=oven;this.ready=ready;','this.oven=oven;this.kind=oven?HuntTarget.OVINNIK:HuntTarget.VOLKOLAK;this.ready=ready;')
edit('hunt/HuntRecords.java',' }\n public final Map','  public Hunt(UUID target,BlockPos anchor,HuntTarget kind,long ready){this(target,anchor,kind==HuntTarget.OVINNIK,ready);this.kind=kind;}\n }\n public final Map')
edit('hunt/HuntRecords.java','t.putBoolean("Ovinnik",h.oven);','t.putBoolean("Ovinnik",h.oven);t.putString("Kind",h.kind.id);')
edit('hunt/HuntRecords.java','t.getBoolean("Ovinnik"),t.getLong("HornReady")','HuntTarget.read(t,"Kind"),t.getLong("HornReady")')
edit('hunt/HuntMob.java','public abstract boolean oven();','public abstract boolean oven();\n public HuntTarget huntTarget(){return oven()?HuntTarget.OVINNIK:HuntTarget.VOLKOLAK;}')
edit('hunt/HuntMob.java','if(isAlive()&&!rage()','if(!(this instanceof ElementHuntMob)&&isAlive()&&!rage()')
edit('hunt/HuntMob.java','if(source.getEntity() instanceof PlayerEntity&&(oven()||org.slavicmyths.item.SilverCombat.silverStrike(source)))','if(!(this instanceof ElementHuntMob)&&source.getEntity() instanceof PlayerEntity&&(oven()||org.slavicmyths.item.SilverCombat.silverStrike(source)))')
edit('hunt/HuntItems.java','+(stack.getOrCreateTag().getBoolean("Volkolak")?"volkolak":"ovinnik")','+HuntTarget.read(stack.getOrCreateTag(),"HuntTarget").id')
start=(r/'hunt/HuntItems.java').read_text(encoding='utf8')
a=start.index('boolean wolf=!stack');b=start.index('return ActionResult.consume(stack);}',a)
start=start[:a]+'''HuntTarget next=HuntTarget.read(stack.getOrCreateTag(),"HuntTarget").next();stack.getOrCreateTag().putString("HuntTarget",next.id);p.displayClientMessage(new TranslationTextComponent("hunt.target",new TranslationTextComponent("entity.slavicmyths."+next.id)),true);}else summon((ServerPlayerEntity)p,HuntTarget.read(stack.getOrCreateTag(),"HuntTarget"),false);'''+start[b:]
a=start.index('public static boolean summon(');b=start.index(' private void detect',a)
start=start[:a]+'''public static boolean summon(ServerPlayerEntity p,boolean oven,boolean debug){return summon(p,oven?HuntTarget.OVINNIK:HuntTarget.VOLKOLAK,debug);}
 public static boolean summon(ServerPlayerEntity p,HuntTarget kind,boolean debug){ServerWorld w=p.getLevel();if(w.dimension()!=World.OVERWORLD)return fail(p,"dimension");HuntRecords records=HuntRecords.get(w);if(records.active(p.getUUID()))return fail(p,"active");HuntRecords.Hunt previous=records.hunts.get(p.getUUID());if(!debug&&previous!=null&&previous.ready>w.getGameTime())return fail(p,"cooldown",(previous.ready-w.getGameTime()+19)/20);
  boolean elemental=kind==HuntTarget.FIRE_SERPENT||kind==HuntTarget.PODVEY;
  if(!debug){if(w.getDifficulty()==Difficulty.PEACEFUL)return fail(p,"peaceful");if(kind!=HuntTarget.PODVEY&&w.isDay())return failKey(p,kind==HuntTarget.FIRE_SERPENT?"hunt.fire_serpent.day":"hunt.fail.daytime");if(p.isInWater())return fail(p,"water");if(elemental&&!w.canSeeSky(p.blockPosition()))return failKey(p,"hunt."+kind.id+".no_open_sky");if(kind==HuntTarget.PODVEY&&(!HuntSpawns.openBiome(w,p.blockPosition())||!HuntSpawns.airVolume(w,p.blockPosition(),2,4)))return failKey(p,"hunt.podvey.biome");if(kind==HuntTarget.VOLKOLAK&&!HuntSpawns.forest(w,p.blockPosition()))return fail(p,"biome");if(kind==HuntTarget.OVINNIK&&!HuntSpawns.environment(w,p.blockPosition(),18))return fail(p,"environment");}
  if(!HuntSpawns.alone(w,p.blockPosition(),kind))return fail(p,"nearby");BlockPos spot=null;int min=kind==HuntTarget.FIRE_SERPENT?20:kind==HuntTarget.PODVEY?14:12,max=kind==HuntTarget.FIRE_SERPENT?36:kind==HuntTarget.PODVEY?26:24;
  for(int attempt=0;attempt<(elemental?40:32);attempt++){double angle=p.getRandom().nextDouble()*Math.PI*2,radius=min+p.getRandom().nextInt(max-min+1);BlockPos xz=p.blockPosition().offset((int)Math.round(Math.cos(angle)*radius),0,(int)Math.round(Math.sin(angle)*radius));if(!w.hasChunkAt(xz))continue;BlockPos ground=w.getHeightmapPos(net.minecraft.world.gen.Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,xz);BlockPos q=kind==HuntTarget.FIRE_SERPENT?ground.above(4+p.getRandom().nextInt(5)):ground;
   double dist=(q.getX()-p.getX())*(q.getX()-p.getX())+(q.getZ()-p.getZ())*(q.getZ()-p.getZ());if(dist<min*min||dist>max*max||!w.getWorldBorder().isWithinBounds(q.offset(-2,0,-2))||!w.getWorldBorder().isWithinBounds(q.offset(2,0,2))||!HuntSpawns.safe(w,q,ground,kind)||org.slavicmyths.kurgan.BurialRecords.get(w).at(ground)!=null||!HuntSpawns.alone(w,q,kind))continue;spot=q;break;}
  if(spot==null)return failKey(p,kind==HuntTarget.FIRE_SERPENT?"hunt.fire_serpent.no_air_space":kind==HuntTarget.PODVEY?"hunt.podvey.position":"hunt.fail.position");HuntMob mob=HuntSpawns.create(w,kind);if(mob==null)return fail(p,"position");mob.home=spot;mob.owner=p.getUUID();mob.moveTo(spot.getX()+.5,spot.getY(),spot.getZ()+.5,0,0);mob.setPersistenceRequired();mob.setTarget(p);
  if(!w.addFreshEntity(mob))return fail(p,"position");records.hunts.put(p.getUUID(),new HuntRecords.Hunt(mob.getUUID(),spot,kind,w.getGameTime()+6000));records.setDirty();w.playSound(null,p.blockPosition(),ModSounds.HUNT_HORN.get(),SoundCategory.PLAYERS,2.5F,.7F);if(elemental)w.sendParticles(kind==HuntTarget.FIRE_SERPENT?net.minecraft.particles.ParticleTypes.FLAME:net.minecraft.particles.ParticleTypes.CLOUD,mob.getX(),mob.getY()+1,mob.getZ(),12,.7,.5,.7,.02);FolkAccessoryItem.award(p,"hunt_begins");return true;
 }
 private static boolean failKey(ServerPlayerEntity p,String key){p.displayClientMessage(new TranslationTextComponent(key),true);p.level.playSound(null,p.blockPosition(),SoundEvents.BONE_BLOCK_HIT,SoundCategory.PLAYERS,.25F,.6F);return false;}
'''+start[b:]
(r/'hunt/HuntItems.java').write_text(start,encoding='utf8')
edit('hunt/HuntCommands.java','.then(Commands.literal("volkolak").executes(c->HuntItems.summon(c.getSource().getPlayerOrException(),false,true)?1:0))','.then(Commands.literal("volkolak").executes(c->HuntItems.summon(c.getSource().getPlayerOrException(),false,true)?1:0)).then(Commands.literal("fire_serpent").executes(c->HuntItems.summon(c.getSource().getPlayerOrException(),HuntTarget.FIRE_SERPENT,true)?1:0)).then(Commands.literal("podvey").executes(c->HuntItems.summon(c.getSource().getPlayerOrException(),HuntTarget.PODVEY,true)?1:0))')
edit('hunt/HuntSpawns.java','m->m.isAlive()&&m.oven()==oven','m->m.isAlive()&&m.huntTarget()==(oven?HuntTarget.OVINNIK:HuntTarget.VOLKOLAK)')
edit('hunt/HuntSpawns.java',' public static void placements(){',''' public static boolean openBiome(IWorld w,BlockPos p){Biome.Category c=w.getBiome(p).getBiomeCategory();return c==Biome.Category.PLAINS||c==Biome.Category.EXTREME_HILLS||c==Biome.Category.SAVANNA||c==Biome.Category.ICY;}
 public static boolean airVolume(IWorld w,BlockPos p,int radius,int height){for(int x=-radius;x<=radius;x++)for(int z=-radius;z<=radius;z++){BlockPos q=p.offset(x,0,z);if(!w.hasChunkAt(q))return false;for(int y=0;y<height;y++)if(!w.isEmptyBlock(q.above(y))||!w.getFluidState(q.above(y)).isEmpty())return false;}return true;}
 public static boolean safe(IWorld w,BlockPos p,BlockPos ground,HuntTarget k){if(k==HuntTarget.FIRE_SERPENT)return w.getBlockState(ground.below()).isFaceSturdy(w,ground.below(),Direction.UP)&&w.getFluidState(ground.below()).isEmpty()&&w.canSeeSky(p)&&airVolume(w,p.below(2),2,5);if(k==HuntTarget.PODVEY)return clearSpace(w,p,1.1F,2.55F)&&airVolume(w,p,1,4)&&w.canSeeSky(p);return clearSpace(w,p,k==HuntTarget.OVINNIK?1.15F:1.05F,k==HuntTarget.OVINNIK?2.45F:2.25F);}
 public static HuntMob create(World w,HuntTarget k){switch(k){case OVINNIK:return ModEntities.OVINNIK.get().create(w);case VOLKOLAK:return ModEntities.VOLKOLAK.get().create(w);case FIRE_SERPENT:return ModEntities.FIRE_SERPENT.get().create(w);default:return ModEntities.PODVEY.get().create(w);}}
 public static boolean alone(net.minecraft.world.server.ServerWorld w,BlockPos p,HuntTarget k){if(k==HuntTarget.OVINNIK||k==HuntTarget.VOLKOLAK)return alone(w,p,k==HuntTarget.OVINNIK);return w.getEntitiesOfClass(HuntMob.class,new AxisAlignedBB(p).inflate(96),m->m.isAlive()&&m.huntTarget()==k&&m.distanceToSqr(p.getX()+.5,p.getY(),p.getZ()+.5)<=96*96).isEmpty();}
 private static boolean elemental(IServerWorld w,BlockPos p,java.util.Random n,HuntTarget k){net.minecraft.world.server.ServerWorld s=w.getLevel();boolean fire=k==HuntTarget.FIRE_SERPENT;return n.nextInt(!fire&&(s.isRaining()||s.isThundering())?64:192)==0&&s.dimension()==World.OVERWORLD&&s.getDifficulty()!=Difficulty.PEACEFUL&&(!s.isDay()||!fire&&s.isRaining())&&w.canSeeSky(p)&&(openBiome(w,p)||fire&&forest(w,p))&&safe(w,p,p,k)&&alone(s,p,k);}
 public static void placements(){EntitySpawnPlacementRegistry.register(ModEntities.FIRE_SERPENT.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->elemental(w,p,n,HuntTarget.FIRE_SERPENT));EntitySpawnPlacementRegistry.register(ModEntities.PODVEY.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->elemental(w,p,n,HuntTarget.PODVEY));''')
edit('hunt/HuntSpawns.java','Biome.Category c=e.getCategory();','Biome.Category c=e.getCategory();if(c==Biome.Category.PLAINS||c==Biome.Category.EXTREME_HILLS||c==Biome.Category.SAVANNA||c==Biome.Category.ICY){e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.FIRE_SERPENT.get(),1,1,1));e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.PODVEY.get(),1,1,1));}else if(c==Biome.Category.FOREST)e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.FIRE_SERPENT.get(),1,1,1));')
p=Path('build.gradle');p.write_text(p.read_text().replace("version = '0.9.0'","version = '0.9.1'"))
