from pathlib import Path
kinds=[('UPYR','upyr',.65,1.9),('NAV','nav',.6,2.1),('DRUZHINNIK','kurgan_druzhinnik',.8,2),('VOEVODA','kurgan_voevoda',1,2.3),('VOLKHV','buried_volkhv',.7,2.1),('PRINCE','unresting_prince',1.1,2.6)]
p=Path('src/main/java/org/slavicmyths/registry/ModEntities.java');s=p.read_text(encoding='utf-8');idx=s.index('    private ModEntities()')
fields=''
for key,id,w,h in kinds:
 fields+=f'    public static final RegistryObject<EntityType<org.slavicmyths.kurgan.KurganCreature>> {key}=ENTITIES.register("{id}",()->EntityType.Builder.<org.slavicmyths.kurgan.KurganCreature>of((t,world)->new org.slavicmyths.kurgan.KurganCreature(t,world,org.slavicmyths.kurgan.KurganFighter.Kind.{key}),EntityClassification.MONSTER).sized({w}F,{h}F).clientTrackingRange(12).build("slavicmyths:{id}"));\n'
fields+='    public static final RegistryObject<EntityType<org.slavicmyths.kurgan.KurganBolt>> KURGAN_BOLT=ENTITIES.register("kurgan_bolt",()->EntityType.Builder.of(org.slavicmyths.kurgan.KurganBolt::new,EntityClassification.MISC).sized(.25F,.25F).clientTrackingRange(8).updateInterval(2).build("slavicmyths:kurgan_bolt"));\n'
s=s[:idx]+fields+s[idx:];idx=s.index('        event.put(DOMOVOY.get()');s=s[:idx]+''.join(f'        event.put({k}.get(),org.slavicmyths.kurgan.KurganCreature.attributes(org.slavicmyths.kurgan.KurganFighter.Kind.{k}).build());\n'for k,_,_,_ in kinds)+s[idx:];p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/registry/ModItems.java');s=p.read_text(encoding='utf-8');idx=s.index('    private ModItems()');colors=[('E4D8CE','8D1717'),('CDE7FF','5FA7FF'),('7B7A80','B22E2E'),('8A2327','D6A451'),('2F2D38','B39A63'),('9F1E28','D9B14E')];fields=''
for (k,id,_,_),(a,b) in zip(kinds,colors):fields+=f'    public static final RegistryObject<Item> {k}_SPAWN_EGG=egg("{id}_spawn_egg",ModEntities.{k},0x{a},0x{b});\n'
for id in ['upyr_fang','grave_cloth_scrap','nav_essence','torn_burial_ribbon','shield_boss_fragment','druzhinnik_blade_fragment','voevoda_insignia','volkhv_amulet','princely_seal']:fields+=f'    public static final RegistryObject<Item> {id.upper()}=ITEMS.register("{id}",()->new Item(properties()));\n'
s=s[:idx]+fields+s[idx:];p.write_text(s,encoding='utf-8')
cues={'upyr':['ambient','hurt','death','attack','leap','bite','step'],'nav':['ambient','hurt','death','attack','shift','spectral_appear','step'],'kurgan_druzhinnik':['ambient','hurt','death','sword_attack','shield_block','shield_bash','step'],'kurgan_voevoda':['ambient','hurt','death','axe_attack','shield_charge','shield_impact','phase_shift','step'],'buried_volkhv':['ambient','hurt','death','cast_basic','cast_clones','cast_ground_seal','summon','step'],'unresting_prince':['ambient','hurt','death','combo','summon','phase_shift','heavy_strike','grab','shield_block','step']}
p=Path('src/main/java/org/slavicmyths/registry/ModSounds.java');s=p.read_text(encoding='utf-8');idx=s.index('    private static');s=s[:idx]+''.join(f'    public static final RegistryObject<SoundEvent> {id.upper()}_{cue.upper()}=sound("{id}_{cue}");\n'for id,cs in cues.items()for cue in cs)+s[idx:];p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/client/ClientSetup.java');s=p.read_text(encoding='utf-8');idx=s.index('        RenderingRegistry.registerEntityRenderingHandler(');s=s[:idx]+''.join(f'        RenderingRegistry.registerEntityRenderingHandler(ModEntities.{k}.get(),m->new KurganCreatureRenderer(m,org.slavicmyths.kurgan.KurganFighter.Kind.{k}));\n'for k,_,_,_ in kinds)+'        RenderingRegistry.registerEntityRenderingHandler(ModEntities.KURGAN_BOLT.get(),m->new net.minecraft.client.renderer.entity.SpriteRenderer<>(m,net.minecraft.client.Minecraft.getInstance().getItemRenderer()));\n'+s[idx:];p.write_text(s,encoding='utf-8')
p=Path('build.gradle');p.write_text(p.read_text(encoding='utf-8').replace("version = '0.8.5'","version = '0.8.6'"),encoding='utf-8')
