from pathlib import Path
p=Path('src/main/java/org/slavicmyths/kurgan/KurganDisturbance.java');s=p.read_text(encoding='utf-8-sig');s=s.replace('    @SubscribeEvent public static void use(PlayerInteractEvent.RightClickBlock e){prop(e.getEntity(),e.getPos());}', '''    private static void cache(Player player,BlockPos pos){if(!(player instanceof ServerPlayer)||player.isSpectator())return;var tile=player.level().getBlockEntity(pos);if(tile instanceof net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity&&tile.getPersistentData().hasUUID("SlavicKurganContainer"))burial(player,tile.getPersistentData().getUUID("SlavicKurganContainer"),pos);}
    @SubscribeEvent public static void use(PlayerInteractEvent.RightClickBlock e){prop(e.getEntity(),e.getPos());cache(e.getEntity(),e.getPos());}''');s=s.replace('breakBlock(BlockEvent.BreakEvent e){prop(e.getPlayer(),e.getPos());','breakBlock(BlockEvent.BreakEvent e){prop(e.getPlayer(),e.getPos());cache(e.getPlayer(),e.getPos());');p.write_text(s,encoding='utf-8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/KurganReworkHeadless.java');s=p.read_text(encoding='utf-8-sig');old='if(sample<3){Path dir=Path.of("build/reports/slavicmyths/kurgan");Files.createDirectories(dir);Files.writeString(dir.resolve(seed+"-"+tier+".txt"),m+"\\n"+n);}'
new='''Path dir=Path.of("build/reports/slavicmyths/kurgan");Files.createDirectories(dir);
    Map<String,Object> report=new LinkedHashMap<>();report.put("version",p.formatVersion);report.put("tier",tier);report.put("seed",seed);report.put("metrics",m);report.put("bounds",p.bounds().array());report.put("validationErrors",p.validate());
    report.put("rooms",p.rooms.stream().map(r->{Map<String,Object> row=new LinkedHashMap<>();row.put("id",r.id);row.put("floor",r.floor);row.put("archetype",r.archetype);row.put("nodeType",r.nodeType);row.put("bounds",r.box().array());row.put("critical",r.critical);row.put("mandatory",r.mandatory);row.put("rewardPoints",KurganLayout.rewards(r));row.put("loot",r.loot);return row;}).toList());
    report.put("links",p.links.stream().map(l->Map.of("a",l.a,"b",l.b,"width",l.width,"height",l.secret?3:l.height,"secret",l.secret,"style",l.style,"transitionStyle",l.transitionStyle,"steps",l.steps.stream().map(s->new int[]{s.x,s.y,s.z}).toList())).toList());
    Files.writeString(dir.resolve(seed+"-"+tier+".json"),new com.google.gson.GsonBuilder().setPrettyPrinting().create().toJson(report));'''
assert old in s;s=s.replace(old,new);p.write_text(s,encoding='utf-8')
