from pathlib import Path
p=Path('src/main/java/org/slavicmyths/kurgan/KurganPlan.java');s=p.read_text(encoding='utf-8');s=s.replace('return rx==14||archetype==Archetype.DEEP;','return rx==14||archetype==Archetype.DEEP&&rx>=11;');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/kurgan/KurganArchitecture.java');s=p.read_text(encoding='utf-8');s=s.replace('outer=r.archetype==KurganPlan.Archetype.DEEP&&','outer=plan.tier==2&&r.archetype==KurganPlan.Archetype.DEEP&&')
s=s.replace('put(r.x+side,r.y+3,r.z-r.rz+1,Blocks.WALL_TORCH.defaultBlockState().setValue(WallTorchBlock.FACING,Direction.SOUTH));','put(r.x-r.rx+2,r.y+r.height,r.z,Blocks.LANTERN.defaultBlockState().setValue(LanternBlock.HANGING,true));')
s=s.replace('   if(r.height>=7)prop(r,-side,r.height,-back,"kurgan_hanging_brazier");','   if(r.height>=7){boolean round=r.archetype==KurganPlan.Archetype.DEEP||r.archetype==KurganPlan.Archetype.RITUAL;prop(r,round?4-r.rx:-side,r.height,round?4-r.rz:-back,"kurgan_hanging_brazier");}')
marker='   case BURIAL,DEEP->{';s=s.replace(marker,marker+'''\n    if(r.archetype==KurganPlan.Archetype.DEEP){int a=r.rx-4,b=r.rz-5;for(int[] pier:new int[][]{{-a,-b},{a,-b},{-a,b},{a,b},{-b,-a},{b,-a},{-b,a},{b,a}})for(int y=1;y<=r.height;y++)put(r.x+pier[0],r.y+y,r.z+pier[1],KurganBlocks.stone(0,y%4==0?1:0));}''')
# Cache immutable private material tables once rather than allocating an array per placed block.
a=s.index('  boolean floor=y<=r.y;int[] weights=');b=s.index('\n  int patch=',a);expression=s[a:b].split('int[] weights=',1)[1].replace('r.archetype','type');s=s[:a]+'  int[] weights=r.archetype==null?JUNCTION_MATERIALS:MATERIALS.get(r.archetype)[y<=r.y?0:1];'+s[b:]
helper=''' private static final int[] JUNCTION_MATERIALS=paletteWeights(null,true);
 private static final java.util.EnumMap<KurganPlan.Archetype,int[][]> MATERIALS=materialTables();
 private static java.util.EnumMap<KurganPlan.Archetype,int[][]> materialTables(){var map=new java.util.EnumMap<KurganPlan.Archetype,int[][]>(KurganPlan.Archetype.class);for(var type:KurganPlan.Archetype.values())map.put(type,new int[][]{paletteWeights(type,true),paletteWeights(type,false)});return map;}
 private static int[] paletteWeights(KurganPlan.Archetype type,boolean floor){return '''+expression+'\n }\n';s=s.replace(' private BlockState roomStone(',helper+' private BlockState roomStone(');p.write_text(s,encoding='utf-8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/KurganReworkHeadless.java');s=p.read_text(encoding='utf-8');needle='    for(var r:p.rooms)if(r.archetype!=null)types.add(r.archetype);';s=s.replace(needle,needle+'''\n    if(tier>0){var instance=new KurganInstance(java.util.UUID.randomUUID(),net.minecraft.core.BlockPos.ZERO,p);instance.disturbance=100;var roster=KurganRoster.roster(instance,p.rooms.get(p.finalRoom));check(!roster.isEmpty(),"Deep room lost its existing population policy");if(tier==2)check(roster.equals(List.of(KurganFighter.Kind.PRINCE)),"Great final population changed");}''');p.write_text(s,encoding='utf-8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/KurganReworkGameTests.java');s=p.read_text(encoding='utf-8');needle='   Map<BlockPos,RandomizableContainerBlockEntity> containers=new LinkedHashMap<>();';s=s.replace(needle,'''   for(var r:plan.rooms)if(r.roomNode){BlockPos lamp=origin.offset(r.x-r.rx+2,r.y+r.height,r.z);test.assertTrue(world.getBlockState(lamp).is(Blocks.LANTERN)&&world.getBlockState(lamp).canSurvive(world,lamp),"Warm fixture has no ceiling support");}
'''+needle);p.write_text(s,encoding='utf-8')
