from pathlib import Path
p=Path('src/main/java/org/slavicmyths/kurgan/KurganPlan.java');s=p.read_text().replace('public int formatVersion=1;','public int formatVersion=1,attemptsUsed=1;');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/kurgan/KurganLayout.java');s=p.read_text().replace('p.formatVersion=2;','p.formatVersion=2;p.attemptsUsed=attempt+1;')
s=s.replace('for(int i:new int[]{7,3})if(!bands[f][i].roomNode)', 'for(int i:new int[]{0,4})if(!bands[f+1][i].roomNode){bands[f+1][i].archetype=Archetype.DESCENT;bands[f+1][i].nodeType=NodeType.TRANSITION_UP;}\n            for(int i:new int[]{7,3})if(!bands[f][i].roomNode)')
needle='    public static int rewards(Room r)'
s=s.replace(needle,'''    public static Step rewardPoint(Room r,int index){boolean octagon=r.archetype==Archetype.DEEP||r.archetype==Archetype.RITUAL;int inset=octagon?3:2;return new Step(r.x+(index==0?-r.rx+inset:r.rx-inset),r.y+1,r.z+r.rz-(octagon?4:2));}
'''+needle)
s=s.replace('for(Room a:p.rooms){if(a.connectors.size()>5)', '''for(Room a:p.rooms){for(int point=0;point<rewards(a);point++){Step s=rewardPoint(a,point);if(!roomAir(a,s.x,s.y,s.z)||!roomAir(a,s.x,s.y+1,s.z))errors.add("blocked reward position "+a.id+"/"+point);if(point==0&&(a.archetype==Archetype.BURIAL||a.archetype==Archetype.WARRIOR||a.archetype==Archetype.DEEP)&&(!roomAir(a,s.x-1,s.y,s.z)||!roomAir(a,s.x+1,s.y,s.z)))errors.add("coffin head outside room "+a.id);}
            if(a.connectors.size()>5)''');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/kurgan/KurganPlanNbt.java');s=p.read_text(encoding='utf-8-sig');s=s.replace('n.putInt("Floors",p.floors);','if(p.formatVersion>=2)n.putInt("Attempts",p.attemptsUsed);n.putInt("Floors",p.floors);');s=s.replace('p.formatVersion=version;if(n.contains("Floors"))','p.formatVersion=version;p.attemptsUsed=n.contains("Attempts")?n.getInt("Attempts"):1;if(n.contains("Floors"))');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/kurgan/KurganArchitecture.java');s=p.read_text(encoding='utf-8-sig');old='private BlockPos cache(KurganPlan.Room r,int i){boolean octagon=r.archetype==KurganPlan.Archetype.DEEP||r.archetype==KurganPlan.Archetype.RITUAL;int inset=octagon?3:2;int dx=i==0?-r.rx+inset:r.rx-inset,dz=r.rz-(octagon?4:2);return pos(r.x+dx,r.y+1,r.z+dz);}';assert old in s;s=s.replace(old,'private BlockPos cache(KurganPlan.Room r,int i){var s=KurganLayout.rewardPoint(r,i);return pos(s.x,s.y,s.z);}');p.write_text(s,encoding='utf-8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/KurganReworkHeadless.java');s=p.read_text().replace('report.put("tier",tier);','report.put("tier",tier);report.put("attemptsUsed",p.attemptsUsed);').replace('row.put("loot",r.loot);','row.put("loot",r.loot);row.put("rewardCoordinates",java.util.stream.IntStream.range(0,KurganLayout.rewards(r)).mapToObj(i->{var s=KurganLayout.rewardPoint(r,i);return new int[]{s.x,s.y,s.z};}).toList());');p.write_text(s,encoding='utf-8')
p=Path('tools/kurgan-tests/org/slavicmyths/verify/KurganReworkGameTests.java');s=p.read_text(encoding='utf-8-sig');needle='  test.assertTrue(shapes==25,"Construction variants count "+shapes);';s=s.replace(needle,needle+'\n  long items=BuiltInRegistries.ITEM.keySet().stream().filter(i->i.getNamespace().equals("slavicmyths")).count(),blocks=BuiltInRegistries.BLOCK.keySet().stream().filter(i->i.getNamespace().equals("slavicmyths")).count();test.assertTrue(items==411&&blocks==179,"Registry totals drift items="+items+" blocks="+blocks);System.out.println("KURGAN_RUNTIME_REGISTRY_TOTALS items="+items+" blocks="+blocks);');p.write_text(s,encoding='utf-8')
