from pathlib import Path
import re
p=Path('src/main/java/org/slavicmyths/client/ClientSetup.java');s=p.read_text(encoding='utf-8');start=s.index('        RenderingRegistry.registerEntityRenderingHandler(');end=s.index('        event.enqueueWork(',start);render=s[start:end];render=render.replace('RenderingRegistry.registerEntityRenderingHandler','event.registerEntityRenderer');render=render.replace('new net.minecraft.client.renderer.entity.SpriteRenderer<>(m,net.minecraft.client.Minecraft.getInstance().getItemRenderer())','new net.minecraft.client.renderer.entity.ThrownItemRenderer<>(m)')
s=s[:start]+s[end:];s=s.replace('import net.minecraftforge.fml.client.registry.RenderingRegistry;','import net.neoforged.neoforge.client.event.EntityRenderersEvent;')
s=s.replace('    private ClientSetup()','    @SubscribeEvent public static void renderers(EntityRenderersEvent.RegisterRenderers event){\n'+render+'        event.registerBlockEntityRenderer(org.slavicmyths.registry.ModTiles.BURIAL_COFFIN.get(),BurialCoffinRenderer::new);\n    }\n    private ClientSetup()')
s=s.replace('            net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(org.slavicmyths.registry.ModTiles.BURIAL_COFFIN.get(),BurialCoffinRenderer::new);\n','').replace('net.minecraft.client.gui.ScreenManager','net.minecraft.client.gui.screens.MenuScreens').replace('net.minecraft.item.ItemModelsProperties','net.minecraft.client.renderer.item.ItemProperties').replace('(stack, world, entity) ->','(stack, world, entity, seed) ->');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/furniture/FurnitureClient.java');s=p.read_text(encoding='utf-8').replace('import net.minecraftforge.fml.client.registry.*;','import net.neoforged.neoforge.client.event.EntityRenderersEvent;').replace('setup(FMLClientSetupEvent e){e.enqueueWork(()->{','setup(EntityRenderersEvent.RegisterRenderers e){').replace('ClientRegistry.bindTileEntityRenderer','e.registerBlockEntityRenderer').replace('RenderingRegistry.registerEntityRenderingHandler','e.registerEntityRenderer').replace(' });}',' }').replace('extends BlockEntityRenderer<RackTile>','implements BlockEntityRenderer<RackTile>').replace('{super(d);}','{}').replace('light,overlay,p,b);','light,overlay,p,b,tile.getLevel(),0);');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/item/FolkEquipmentEffects.java');s=p.read_text(encoding='utf-8').replace('private static final UUID SPEED=UUID.fromString(','private static final net.minecraft.resources.ResourceLocation SPEED=net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("slavicmyths",').replace('new AttributeModifier(SPEED,"Seven league stride",.3*ramp/60,AttributeModifier.Operation.MULTIPLY_TOTAL)','new AttributeModifier(SPEED,.3*ramp/60,AttributeModifier.Operation.ADD_MULTIPLIED_TOTAL)');p.write_text(s,encoding='utf-8')
p=Path('src/main/java/org/slavicmyths/bandit/BanditEntity.java');s=p.read_text(encoding='utf-8').replace('new AttributeModifier(UUID.fromString("548bd780-d3a7-428d-8bb0-ecf053af0800"),"Ataman heavy strike",3,AttributeModifier.Operation.ADDITION)','new AttributeModifier(ResourceLocation.fromNamespaceAndPath("slavicmyths","548bd780-d3a7-428d-8bb0-ecf053af0800"),3,AttributeModifier.Operation.ADD_VALUE)').replace('power.getId()','power.id()');p.write_text(s,encoding='utf-8')
