from pathlib import Path
import zipfile,json,re
z=zipfile.ZipFile('build/moddev/artifacts/neoforge-21.1.255-sources.jar')
index={n[:-5].replace('/','.') for n in z.namelist() if n.endswith('.java')}
# Exact, checked type/package changes only. Strings/comments stay byte-for-byte unchanged.
classes={
'World':'net.minecraft.world.level.Level','ServerWorld':'net.minecraft.server.level.ServerLevel','PlayerEntity':'net.minecraft.world.entity.player.Player','ServerPlayerEntity':'net.minecraft.server.level.ServerPlayer','PlayerInventory':'net.minecraft.world.entity.player.Inventory','MobEntity':'net.minecraft.world.entity.Mob','CreatureEntity':'net.minecraft.world.entity.PathfinderMob','MonsterEntity':'net.minecraft.world.entity.monster.Monster','IMob':'net.minecraft.world.entity.monster.Enemy','AnimalEntity':'net.minecraft.world.entity.animal.Animal','TameableEntity':'net.minecraft.world.entity.TamableAnimal','AbstractFishEntity':'net.minecraft.world.entity.animal.AbstractFish','HorseEntity':'net.minecraft.world.entity.animal.horse.Horse','ArrowEntity':'net.minecraft.world.entity.projectile.Arrow','AbstractArrowEntity':'net.minecraft.world.entity.projectile.AbstractArrow','ProjectileItemEntity':'net.minecraft.world.entity.projectile.ThrowableItemProjectile','ItemEntity':'net.minecraft.world.entity.item.ItemEntity','EntityClassification':'net.minecraft.world.entity.MobCategory','SpawnReason':'net.minecraft.world.entity.MobSpawnType','EquipmentSlotType':'net.minecraft.world.entity.EquipmentSlot',
'CompoundNBT':'net.minecraft.nbt.CompoundTag','ListNBT':'net.minecraft.nbt.ListTag','StringNBT':'net.minecraft.nbt.StringTag','INBT':'net.minecraft.nbt.Tag','NBTUtil':'net.minecraft.nbt.NbtUtils','Vector3d':'net.minecraft.world.phys.Vec3','Vector3f':'org.joml.Vector3f','AxisAlignedBB':'net.minecraft.world.phys.AABB','MathHelper':'net.minecraft.util.Mth','BlockRayTraceResult':'net.minecraft.world.phys.BlockHitResult','EntityRayTraceResult':'net.minecraft.world.phys.EntityHitResult','RayTraceResult':'net.minecraft.world.phys.HitResult','RayTraceContext':'net.minecraft.world.level.ClipContext','ISelectionContext':'net.minecraft.world.phys.shapes.CollisionContext','VoxelShapes':'net.minecraft.world.phys.shapes.Shapes',
'ITextComponent':'net.minecraft.network.chat.Component','IFormattableTextComponent':'net.minecraft.network.chat.MutableComponent','TextFormatting':'net.minecraft.ChatFormatting','ITooltipFlag':'net.minecraft.world.item.TooltipFlag','IReorderingProcessor':'net.minecraft.util.FormattedCharSequence',
'IItemTier':'net.minecraft.world.item.Tier','ItemTier':'net.minecraft.world.item.Tiers','ItemUseContext':'net.minecraft.world.item.context.UseOnContext','UseAction':'net.minecraft.world.item.UseAnim','ActionResultType':'net.minecraft.world.InteractionResult','ActionResult':'net.minecraft.world.InteractionResultHolder','Hand':'net.minecraft.world.InteractionHand','SoundCategory':'net.minecraft.sounds.SoundSource',
'TileEntity':'net.minecraft.world.level.block.entity.BlockEntity','ChestTileEntity':'net.minecraft.world.level.block.entity.ChestBlockEntity','HorizontalBlock':'net.minecraft.world.level.block.HorizontalDirectionalBlock','StateContainer':'net.minecraft.world.level.block.state.StateDefinition','IBlockReader':'net.minecraft.world.level.BlockGetter','IWorldReader':'net.minecraft.world.level.LevelReader','IWorld':'net.minecraft.world.level.LevelAccessor','ISeedReader':'net.minecraft.world.level.WorldGenLevel','WorldSavedData':'net.minecraft.world.level.saveddata.SavedData','InventoryHelper':'net.minecraft.world.Containers','ItemStackHelper':'net.minecraft.world.ContainerHelper',
'AttributeModifierMap':'net.minecraft.world.entity.ai.attributes.AttributeSupplier','MovementController':'net.minecraft.world.entity.ai.control.MoveControl','PathNavigator':'net.minecraft.world.entity.ai.navigation.PathNavigation','GroundPathNavigator':'net.minecraft.world.entity.ai.navigation.GroundPathNavigation','SwimmerPathNavigator':'net.minecraft.world.entity.ai.navigation.WaterBoundPathNavigation','PathNodeType':'net.minecraft.world.level.pathfinder.PathType',
'Effect':'net.minecraft.world.effect.MobEffect','EffectInstance':'net.minecraft.world.effect.MobEffectInstance','Effects':'net.minecraft.world.effect.MobEffects','EffectType':'net.minecraft.world.effect.MobEffectCategory','CommandSource':'net.minecraft.commands.CommandSourceStack','Commands':'net.minecraft.commands.Commands','ServerBossInfo':'net.minecraft.server.level.ServerBossEvent','BossInfo':'net.minecraft.world.BossEvent','IParticleData':'net.minecraft.core.particles.ParticleOptions','ItemParticleData':'net.minecraft.core.particles.ItemParticleOption','BlockParticleData':'net.minecraft.core.particles.BlockParticleOption','DataParameter':'net.minecraft.network.syncher.EntityDataAccessor','DataSerializers':'net.minecraft.network.syncher.EntityDataSerializers','EntityDataManager':'net.minecraft.network.syncher.SynchedEntityData','PacketBuffer':'net.minecraft.network.FriendlyByteBuf','IPacket':'net.minecraft.network.protocol.Packet',
'SimpleNamedContainerProvider':'net.minecraft.world.SimpleMenuProvider','INamedContainerProvider':'net.minecraft.world.MenuProvider','IInventory':'net.minecraft.world.Container','Inventory':'net.minecraft.world.SimpleContainer',
'EntityRendererManager':'net.minecraft.client.renderer.entity.EntityRendererProvider.Context','EntityModel':'net.minecraft.client.model.EntityModel','BipedModel':'net.minecraft.client.model.HumanoidModel','PlayerModel':'net.minecraft.client.model.PlayerModel','AbstractClientPlayerEntity':'net.minecraft.client.player.AbstractClientPlayer','ModelRenderer':'net.minecraft.client.model.geom.ModelPart','LayerRenderer':'net.minecraft.client.renderer.entity.layers.RenderLayer','IRenderTypeBuffer':'net.minecraft.client.renderer.MultiBufferSource','ContainerScreen':'net.minecraft.client.gui.screens.inventory.AbstractContainerScreen','Screen':'net.minecraft.client.gui.screens.Screen','KeyBinding':'net.minecraft.client.KeyMapping','TickableSound':'net.minecraft.client.resources.sounds.AbstractTickableSoundInstance',
}
# Inventory is ambiguous in already-ported classes: never rename modern simple Inventory.
classes.pop('Inventory')
for old,target in classes.items():
 if target.startswith('net.') and target.split('.Context')[0] not in index:raise ValueError((old,target))
prefix={
'net.minecraft.entity':'net.minecraft.world.entity','net.minecraft.entity.player':'net.minecraft.world.entity.player','net.minecraft.entity.ai.goal':'net.minecraft.world.entity.ai.goal','net.minecraft.entity.ai.attributes':'net.minecraft.world.entity.ai.attributes','net.minecraft.entity.monster':'net.minecraft.world.entity.monster','net.minecraft.entity.projectile':'net.minecraft.world.entity.projectile','net.minecraft.entity.passive':'net.minecraft.world.entity.animal','net.minecraft.item':'net.minecraft.world.item','net.minecraft.item.crafting':'net.minecraft.world.item.crafting','net.minecraft.block':'net.minecraft.world.level.block','net.minecraft.block.material':'net.minecraft.world.level.material','net.minecraft.state':'net.minecraft.world.level.block.state.properties','net.minecraft.state.properties':'net.minecraft.world.level.block.state.properties','net.minecraft.util.math.shapes':'net.minecraft.world.phys.shapes','net.minecraft.particles':'net.minecraft.core.particles','net.minecraft.world.server':'net.minecraft.server.level','net.minecraft.world.biome':'net.minecraft.world.level.biome','net.minecraft.command':'net.minecraft.commands','net.minecraft.network.datasync':'net.minecraft.network.syncher','net.minecraft.potion':'net.minecraft.world.effect','net.minecraft.tileentity':'net.minecraft.world.level.block.entity','net.minecraft.fluid':'net.minecraft.world.level.material','net.minecraft.pathfinding':'net.minecraft.world.entity.ai.navigation',
'net.minecraftforge.eventbus.api':'net.neoforged.bus.api','net.minecraftforge.api.distmarker':'net.neoforged.api.distmarker','net.minecraftforge.fml.event.lifecycle':'net.neoforged.fml.event.lifecycle','net.minecraftforge.event.entity.player':'net.neoforged.neoforge.event.entity.player','net.minecraftforge.event.entity.living':'net.neoforged.neoforge.event.entity.living','net.minecraftforge.event.entity':'net.neoforged.neoforge.event.entity','net.minecraftforge.event.world':'net.neoforged.neoforge.event.level',
}
exact={'net.minecraftforge.fml.common.Mod':'net.neoforged.fml.common.Mod','net.minecraftforge.event.RegisterCommandsEvent':'net.neoforged.neoforge.event.RegisterCommandsEvent','net.minecraftforge.fml.DistExecutor':'net.neoforged.fml.DistExecutor','net.minecraftforge.registries.ForgeRegistries':'net.minecraft.core.registries.BuiltInRegistries','net.minecraft.util.ResourceLocation':'net.minecraft.resources.ResourceLocation','net.minecraft.util.Direction':'net.minecraft.core.Direction','net.minecraft.util.SoundEvent':'net.minecraft.sounds.SoundEvent','net.minecraft.util.SoundEvents':'net.minecraft.sounds.SoundEvents','net.minecraft.util.DamageSource':'net.minecraft.world.damagesource.DamageSource','net.minecraft.util.math.BlockPos':'net.minecraft.core.BlockPos','net.minecraft.util.GameRules':'net.minecraft.world.level.GameRules','net.minecraft.world.GameRules':'net.minecraft.world.level.GameRules','net.minecraft.world.gen.Heightmap':'net.minecraft.world.level.levelgen.Heightmap','net.minecraft.world.chunk.ChunkStatus':'net.minecraft.world.level.chunk.status.ChunkStatus'}
wild={'net.minecraft.util.*':['net.minecraft.world.*','net.minecraft.sounds.*','net.minecraft.resources.ResourceLocation','net.minecraft.core.Direction','net.minecraft.world.damagesource.DamageSource'],'net.minecraft.util.math.*':['net.minecraft.core.BlockPos','net.minecraft.world.phys.*','net.minecraft.util.Mth','net.minecraft.world.level.ClipContext'],'net.minecraft.util.text.*':['net.minecraft.network.chat.*','net.minecraft.ChatFormatting'],'net.minecraft.world.*':['net.minecraft.world.level.*','net.minecraft.world.MenuProvider','net.minecraft.world.SimpleMenuProvider','net.minecraft.world.Difficulty','net.minecraft.world.BossEvent'],'net.minecraft.inventory.*':['net.minecraft.world.Container','net.minecraft.world.ContainerHelper','net.minecraft.world.Containers','net.minecraft.world.entity.EquipmentSlot','net.minecraft.world.SimpleContainer']}
lex=re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|//[^\n]*|/\*[\s\S]*?\*/|\b[A-Za-z_$][\w$]*\b')
renames={k:v.rsplit('.',1)[-1] for k,v in classes.items()}
changed=[]
for p in Path('src/main/java').rglob('*.java'):
 original=s=p.read_text(encoding='utf-8')
 # Imports are handled independently; protect all gameplay strings and NBT keys.
 def imp(m):
  name=m.group(1)
  if name in wild:return '\n'.join('import '+t+';' for t in wild[name])
  if name in exact:return 'import '+exact[name]+';'
  simple=name.rsplit('.',1)[-1]
  if simple in classes and name.startswith('net.minecraft.') and name not in index:return 'import '+classes[simple]+';'
  pre=name.rsplit('.',1)[0]
  if pre in prefix:
   mapped=prefix[pre]+'.'+simple
   if simple=='*' or mapped in index:return 'import '+mapped+';'
  return m.group(0)
 s=re.sub(r'^import (net\.[^;]+);',imp,s,flags=re.M)
 # Only legacy type identifiers are changed; mapped names never occur as literals.
 s=lex.sub(lambda m:renames.get(m.group(),m.group()),s)
 # Known fully qualified references without imports.
 for old,new in sorted(exact.items(),key=lambda kv:-len(kv[0])):s=s.replace(old,new)
 # New annotation has its own top-level EventBusSubscriber.
 if '@Mod.EventBusSubscriber' in s:
  s=s.replace('@Mod.EventBusSubscriber','@net.neoforged.fml.common.EventBusSubscriber').replace('Mod.EventBusSubscriber.Bus.','net.neoforged.fml.common.EventBusSubscriber.Bus.')
 if s!=original:
  p.write_text(s,encoding='utf-8');changed.append(str(p))
Path('docs/port/finalize-type-migration.json').write_text(json.dumps({'scope':'Exact type/import changes; semantic migration still required','files':changed},indent=2),encoding='utf-8')
print('Updated',len(changed),'source files; target classes verified against installed sources')
