from pathlib import Path
r=Path('src/main/java/org/slavicmyths')
def edit(p,a,b):
 p=r/p;s=p.read_text(encoding='utf-8-sig');assert a in s,(p,a[:80]);p.write_text(s.replace(a,b),encoding='utf8')
edit('registry/ModEntities.java','    public static final RegistryObject<EntityType<org.slavicmyths.entity.VolkolakEntity>> VOLKOLAK=', '''    public static final RegistryObject<EntityType<org.slavicmyths.hunt.ElementHuntMob>> FIRE_SERPENT=ENTITIES.register("fire_serpent",()->EntityType.Builder.of(org.slavicmyths.hunt.ElementHuntMob::new,EntityClassification.MONSTER).sized(1.25F,1.55F).clientTrackingRange(12).fireImmune().build("slavicmyths:fire_serpent"));
    public static final RegistryObject<EntityType<org.slavicmyths.hunt.ElementHuntMob>> PODVEY=ENTITIES.register("podvey",()->EntityType.Builder.of(org.slavicmyths.hunt.ElementHuntMob::new,EntityClassification.MONSTER).sized(1.1F,2.55F).clientTrackingRange(12).build("slavicmyths:podvey"));
    public static final RegistryObject<EntityType<org.slavicmyths.hunt.SerpentProjection>> SERPENT_PROJECTION=ENTITIES.register("serpent_projection",()->EntityType.Builder.of(org.slavicmyths.hunt.SerpentProjection::new,EntityClassification.MISC).sized(1.25F,1.55F).clientTrackingRange(12).updateInterval(2).fireImmune().build("slavicmyths:serpent_projection"));
    public static final RegistryObject<EntityType<org.slavicmyths.entity.VolkolakEntity>> VOLKOLAK=''')
edit('registry/ModEntities.java','        event.put(VOLKOLAK.get(),','        event.put(FIRE_SERPENT.get(),org.slavicmyths.hunt.ElementHuntMob.attributes(true).build());\n        event.put(PODVEY.get(),org.slavicmyths.hunt.ElementHuntMob.attributes(false).build());\n        event.put(SERPENT_PROJECTION.get(),org.slavicmyths.hunt.SerpentProjection.attributes().build());\n        event.put(VOLKOLAK.get(),')
edit('registry/ModItems.java','    public static final RegistryObject<Item> VOLKOLAK_SPAWN_EGG=', '''    public static final RegistryObject<Item> PYLAYUSCHAYA_CHESHUYA=ITEMS.register("pylayuschaya_cheshuya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32),org.slavicmyths.hunt.HuntItems.Role.ASH));
    public static final RegistryObject<Item> OGNENNOE_PERO=ITEMS.register("ognennoe_pero",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.SPARK));
    public static final RegistryObject<Item> OBEREG_PADAYUSCHEY_ZVEZDY=ITEMS.register("obereg_padayuschey_zvezdy",()->new org.slavicmyths.item.FolkAccessoryItem(properties().rarity(Rarity.RARE),"necklace"));
    public static final RegistryObject<Item> UZEL_PODVEYA=ITEMS.register("uzel_podveya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(16).rarity(Rarity.UNCOMMON),org.slavicmyths.hunt.HuntItems.Role.FANG));
    public static final RegistryObject<Item> VIHREVAYA_NIT=ITEMS.register("vihrevaya_nit",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(32),org.slavicmyths.hunt.HuntItems.Role.CLAW));
    public static final RegistryObject<Item> VETROVOY_UZEL=ITEMS.register("vetrovoy_uzel",()->new org.slavicmyths.hunt.WindKnotItem(properties().stacksTo(1).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> SOSUD_OGNENNOGO_DYHANIYA=ITEMS.register("sosud_ognennogo_dyhaniya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.VESSEL));
    public static final RegistryObject<Item> SOSUD_PODVEYA=ITEMS.register("sosud_podveya",()->new org.slavicmyths.hunt.HuntItems(properties().stacksTo(8).rarity(Rarity.RARE),org.slavicmyths.hunt.HuntItems.Role.VESSEL));
    public static final RegistryObject<Item> FIRE_SERPENT_SPAWN_EGG=egg("fire_serpent_spawn_egg",ModEntities.FIRE_SERPENT,0x29191A,0xF04B16);
    public static final RegistryObject<Item> PODVEY_SPAWN_EGG=egg("podvey_spawn_egg",ModEntities.PODVEY,0x56626F,0xC5E4F1);
    public static final RegistryObject<Item> VOLKOLAK_SPAWN_EGG=''')
edit('client/ClientSetup.java','        RenderingRegistry.registerEntityRenderingHandler(ModEntities.VOLKOLAK.get(),','        RenderingRegistry.registerEntityRenderingHandler(ModEntities.FIRE_SERPENT.get(),m->new ElementRenderer<org.slavicmyths.hunt.ElementHuntMob>(m,true));\n        RenderingRegistry.registerEntityRenderingHandler(ModEntities.PODVEY.get(),m->new ElementRenderer<org.slavicmyths.hunt.ElementHuntMob>(m,false));\n        RenderingRegistry.registerEntityRenderingHandler(ModEntities.SERPENT_PROJECTION.get(),m->new ElementRenderer<org.slavicmyths.hunt.SerpentProjection>(m,true));\n        RenderingRegistry.registerEntityRenderingHandler(ModEntities.VOLKOLAK.get(),')
edit('hunt/EmberClump.java','((HuntMob)getOwner()).wetRain()?4.25F:5','damage((HuntMob)getOwner())')
edit('hunt/EmberClump.java','((HuntMob)owner).wetRain()?4.25F:5','damage((HuntMob)owner)')
edit('hunt/EmberClump.java',' @Override public net.minecraft.network.IPacket<?>',' private float damage(HuntMob owner){return owner instanceof ElementHuntMob?ElementRules.fireDamage(4,owner.wetRain()):owner.wetRain()?4.25F:5;}\n @Override public net.minecraft.network.IPacket<?>')
edit('hunt/ElementHuntMob.java','ready.put(s,level.getGameTime()+ElementRules.cooldown(s,wetRain()));','ready.put(s,level.getGameTime()+(s==State.MELEE_SNAP&&!serpent()?20:ElementRules.cooldown(s,wetRain())));')
edit('hunt/ElementHuntMob.java','ticks==ElementRules.windup(s)','ticks==(serpent()?7:8)')
edit('item/FolkAccessoryItem.java','return this==org.slavicmyths.registry.ModItems.ZOLNY_OBEREG.get()||','return this==org.slavicmyths.registry.ModItems.OBEREG_PADAYUSCHEY_ZVEZDY.get()||this==org.slavicmyths.registry.ModItems.ZOLNY_OBEREG.get()||')
for p in (r/'hunt').glob('*.java'):p.write_text(p.read_text(encoding='utf-8-sig'),encoding='utf8')
