from pathlib import Path
import json,shutil
from PIL import Image
R=Path('.');p=R/'src/main/java/org/slavicmyths/registry/ModEntities.java';s=p.read_text(encoding='utf-8');s=s.replace('    @SubscribeEvent\n    public static void attributes','    public static final DeferredHolder<EntityType<?>,EntityType<org.slavicmyths.swamp.BolotnikEntity>> BOLOTNIK=ENTITIES.register("bolotnik",()->EntityType.Builder.of(org.slavicmyths.swamp.BolotnikEntity::new,MobCategory.MONSTER).sized(1.15F,2.0F).clientTrackingRange(10).build("slavicmyths:bolotnik"));\n\n    @SubscribeEvent\n    public static void attributes');s=s.replace('        event.put(KIKIMORA.get(),','        event.put(BOLOTNIK.get(),org.slavicmyths.swamp.BolotnikEntity.attributes().build());\n        event.put(KIKIMORA.get(),');p.write_text(s,encoding='utf-8')
p=R/'src/main/java/org/slavicmyths/registry/ModItems.java';s=p.read_text(encoding='utf-8').replace('    public static final DeferredHolder<Item, Item> VODYANOY_SPAWN_EGG','    public static final DeferredHolder<Item,Item> BOLOTNIK_SPAWN_EGG=egg("bolotnik_spawn_egg",ModEntities.BOLOTNIK,0x343529,0x657144);\n    public static final DeferredHolder<Item, Item> VODYANOY_SPAWN_EGG');p.write_text(s,encoding='utf-8')
p=R/'src/main/java/org/slavicmyths/client/ClientSetup.java';s=p.read_text(encoding='utf-8').replace('        event.registerEntityRenderer(ModEntities.VODYANOY','        event.registerEntityRenderer(ModEntities.BOLOTNIK.get(),BolotnikRenderer::new);\n        event.registerEntityRenderer(ModEntities.VODYANOY');p.write_text(s,encoding='utf-8')
p=R/'src/main/java/org/slavicmyths/water/WaterSpawns.java';s=p.read_text(encoding='utf-8').replace('  event.register(ModEntities.VODYANOY', '  event.register(ModEntities.BOLOTNIK.get(),net.minecraft.world.entity.SpawnPlacementTypes.ON_GROUND,Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,(t,w,s,p,r)->w.getBiome(p).is(Biomes.SWAMP)&&w.getDifficulty()!=net.minecraft.world.Difficulty.PEACEFUL&&!w.getLevel().isDay()&&net.minecraft.world.entity.Mob.checkMobSpawnRules(t,w,s,p,r)&&r.nextInt(4)==0,net.neoforged.neoforge.event.entity.RegisterSpawnPlacementsEvent.Operation.REPLACE);\n  event.register(ModEntities.VODYANOY');p.write_text(s,encoding='utf-8')
# Only newly spawned vanilla-swamp water spirits receive revised stats; saved/outside-swamp balance stays intact.
p=R/'src/main/java/org/slavicmyths/water/WaterSpirit.java';s=p.read_text(encoding='utf-8');a=s.index(' public void travel');s=s[:a]+''' @Override public net.minecraft.world.entity.SpawnGroupData finalizeSpawn(net.minecraft.world.level.ServerLevelAccessor world,net.minecraft.world.DifficultyInstance difficulty,net.minecraft.world.entity.MobSpawnType reason,net.minecraft.world.entity.SpawnGroupData data){
  var result=super.finalizeSpawn(world,difficulty,reason,data);
  if(world.getBiome(blockPosition()).is(net.minecraft.world.level.biome.Biomes.SWAMP)){
   double hp=this instanceof RusalkaEntity?36:this instanceof VodyanoyEntity?72:getMaxHealth();
   getAttribute(net.minecraft.world.entity.ai.attributes.Attributes.MAX_HEALTH).setBaseValue(hp);setHealth((float)hp);
  }return result;
 }
'''+s[a:];p.write_text(s,encoding='utf-8')
res=R/'src/main/resources';js=lambda p,d:p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
js(res/'assets/slavicmyths/models/item/bolotnik_spawn_egg.json',{'parent':'minecraft:item/template_spawn_egg'})
for language,values in [('en_us',{'entity.slavicmyths.bolotnik':'Bolotnik','item.slavicmyths.bolotnik_spawn_egg':'Bolotnik Spawn Egg','entity.slavicmyths.bolotnik_elite':'Shrine Bog Guardian'}),('ru_ru',{'entity.slavicmyths.bolotnik':'Болотник','item.slavicmyths.bolotnik_spawn_egg':'Яйцо призыва болотника','entity.slavicmyths.bolotnik_elite':'Болотный страж святилища'})]:
 p=res/('assets/slavicmyths/lang/'+language+'.json');d=json.loads(p.read_text(encoding='utf-8'));d.update(values);js(p,d)
p=res/'data/slavicmyths/neoforge/biome_modifier/swamp_encounters.json';js(p,{'type':'neoforge:add_spawns','biomes':['minecraft:swamp'],'spawners':[{'type':'slavicmyths:bolotnik','weight':3,'minCount':1,'maxCount':1}]})
p=res/'data/slavicmyths/loot_table/entities/bolotnik.json';js(p,{'type':'minecraft:entity','pools':[{'rolls':1,'entries':[{'type':'minecraft:item','name':'minecraft:moss_block','functions':[{'function':'minecraft:set_count','count':{'type':'minecraft:uniform','min':1,'max':3}}]}]},{'rolls':1,'conditions':[{'condition':'minecraft:random_chance','chance':.3}],'entries':[{'type':'minecraft:item','name':'slavicmyths:pearl_fragment'}]}]})
art=R/'art/swamp-0.9.7';art.mkdir(exist_ok=True);src=Path('C:/Users/pavel/.codex/generated_images/01a0edaf-309b-7b13-a7db-1c5911645c83/exec-3e521bde-be9c-473f-a6ba-8f01e4cd214f.png');shutil.copy2(src,art/'bolotnik-source.png');Image.open(src).convert('RGBA').resize((256,256),Image.Resampling.NEAREST).save(res/'assets/slavicmyths/textures/entity/bolotnik.png');js(art/'provenance.json',{'mode':'builtin imagegen','authorSource':'art/swamp-0.9.7/bolotnik-source.png','runtimeSize':[256,256],'purpose':'Wet bark, roots and muted moss UV material for separate stocky Bolotnik geometry','originalSource':str(src)})
entries=[{'kind':kind,'target_id':'slavicmyths:'+name} for kind,name in [('entity_type','bolotnik'),('item','bolotnik_spawn_egg'),('feature','swamp_nature'),('structure','swamp_watchtower')]];js(R/'docs/swamp/registry-additions-0.9.7.json',{'entries':entries})
print('New Bolotnik and biome-scoped stats registered')
