from pathlib import Path
p=Path('src/main/java/org/slavicmyths/client/YagaScreen.java');s=p.read_text().replace('if(menu.tab()==0)font.draw(m,tr("favor."+(menu.stage()>=3?"trusted":menu.stage()>=1?"guest":"stranger")),112,25,0xffefd5a0);','if(menu.tab()==0)text(m,tr("favor."+(menu.stage()>=3?"trusted":menu.stage()>=1?"guest":"stranger")),112,25,166,2,0xffefd5a0);');p.write_text(s,'utf-8')
# Test the bounded graph-independent building and saved contract pool with no game runtime.
p=Path('tools/kurgan-tests/org/slavicmyths/verify/YagaHeadless.java');s=p.read_text().replace('import org.slavicmyths.yaga.YagaData;','import org.slavicmyths.yaga.*;\nimport java.util.*;')
s=s.replace('System.out.println("PASS:', '''
  for(int stage=1;stage<=3;stage++){int index=0;Set<Integer> seen=new HashSet<>();for(int i=0;i<28;i++){index=YagaServices.nextContract(stage,index);check(index>=0&&index<14,"pool index escaped bounds");check(stage==3||YagaServices.POOL[index]<4,"early player offered rare boss contract");seen.add(YagaServices.POOL[index]);}check(seen.size()==(stage==3?6:4),"finite contract pool misses target");}
  CompoundNBT malformed=new CompoundNBT();malformed.putLong("Anchor",BlockPos.ZERO.asLong());malformed.putBoolean("Placed",true);net.minecraft.nbt.ListNBT plist=new net.minecraft.nbt.ListNBT();CompoundNBT bad=new CompoundNBT();bad.putUUID("Player",player);bad.putInt("Stage",1);bad.putInt("Contract",8);bad.putString("Active","contract:8");plist.add(bad);malformed.put("Players",plist);YagaData repaired=new YagaData();repaired.load(malformed);check(YagaServices.POOL[repaired.progress(player).contract]<4&&repaired.progress(player).active.isEmpty(),"old/malformed rare contract strands guest");
  YagaHutPlan plan=new YagaHutPlan();check(plan.blocks.size()<5000,"unbounded hut blueprint");check(plan.blocks.get(YagaHutPlan.HOME).equals("minecraft:air")&&plan.blocks.get(YagaHutPlan.HOME.above()).equals("minecraft:air"),"NPC obstructed by furnishings");check(plan.blocks.get(YagaHutPlan.HOME.offset(-2,0,1)).equals("slavicmyths:yaga_cauldron"),"service anchor and hut disagree");
  for(int x=-5;x<=5;x++)for(int z=-6;z<=6;z++)check(plan.blocks.containsKey(new BlockPos(x,3,z)),"floor hole");for(int x:new int[]{-3,3}){for(int dx=-1;dx<=1;dx++)check(plan.blocks.get(new BlockPos(x+dx,0,-3)).equals("minecraft:polished_blackstone_slab"),"missing front claw");check(plan.blocks.get(new BlockPos(x,0,2)).equals("minecraft:polished_blackstone_slab"),"missing rear claw");check(plan.blocks.get(new BlockPos(x,2,0)).contains("stairs"),"straight pillar leg");}
  check(plan.blocks.get(new BlockPos(0,4,-6)).contains("half=lower")&&plan.blocks.get(new BlockPos(0,5,-6)).contains("half=upper"),"incomplete entrance");for(int z=-5;z<=1;z++)for(int y=4;y<=5;y++)check(plan.blocks.get(new BlockPos(0,y,z)).equals("minecraft:air"),"entry route obstructed");
  for(BlockPos pos:plan.blocks.keySet())check(Math.abs(pos.getX())<=9&&pos.getZ()>=-16&&pos.getZ()<=9&&pos.getY()>=-1&&pos.getY()<=13,"blueprint outside loading/rollback box");
  for(long seed:new long[]{0,-1,Long.MIN_VALUE,42,2026}){BlockPos spawn=new BlockPos(-1500,70,1900);List<BlockPos> sites=YagaHutPlan.candidates(seed,spawn);check(sites.size()==64&&sites.equals(YagaHutPlan.candidates(seed,spawn)),"unstable/unbounded candidates");for(BlockPos site:sites){double dx=site.getX()-spawn.getX(),dz=site.getZ()-spawn.getZ(),radius=Math.sqrt(dx*dx+dz*dz);check(radius>=800&&radius<=2500,"hut outside requested spawn radius");}}
  System.out.println("PASS:''')
s=s.replace('independent player NBT and unloaded NPC UUID.','independent player NBT, unloaded NPC UUID, malformed contract repair, bounded seeded hut placement, floor, entrance, service anchor and articulated 3+1 claw geometry.')
p.write_text(s,'utf-8')
