from pathlib import Path
p=Path('tools/kurgan-tests/org/slavicmyths/verify/YagaPlacementHeadless.java');s=p.read_text();at=s.index(' public static void main(')
s=s[:at]+''' private static net.minecraft.tags.ITagCollection<Block> vanillaTags(String archive)throws java.io.IOException{Map<net.minecraft.util.ResourceLocation,com.google.gson.JsonArray> definitions=new HashMap<>();try(java.util.zip.ZipFile zip=new java.util.zip.ZipFile(archive)){java.util.Enumeration<? extends java.util.zip.ZipEntry> entries=zip.entries();while(entries.hasMoreElements()){java.util.zip.ZipEntry e=entries.nextElement();String name=e.getName();if(name.startsWith("data/minecraft/tags/blocks/")&&name.endsWith(".json")){try(java.io.Reader reader=new java.io.InputStreamReader(zip.getInputStream(e),java.nio.charset.StandardCharsets.UTF_8)){definitions.put(new net.minecraft.util.ResourceLocation("minecraft",name.substring(27,name.length()-5)),new com.google.gson.JsonParser().parse(reader).getAsJsonObject().getAsJsonArray("values"));}}}}
  check(definitions.size()>50,"Vanilla tag resource archive missing");Map<net.minecraft.util.ResourceLocation,net.minecraft.tags.ITag<Block>> tags=new HashMap<>();for(net.minecraft.util.ResourceLocation id:definitions.keySet())resolveTag(id,definitions,tags,new HashSet<>());return net.minecraft.tags.ITagCollection.of(tags);
 }
 private static net.minecraft.tags.ITag<Block> resolveTag(net.minecraft.util.ResourceLocation id,Map<net.minecraft.util.ResourceLocation,com.google.gson.JsonArray> definitions,Map<net.minecraft.util.ResourceLocation,net.minecraft.tags.ITag<Block>> tags,Set<net.minecraft.util.ResourceLocation> path){if(tags.containsKey(id))return tags.get(id);check(path.add(id),"Vanilla tag cycle");Set<Block> values=new HashSet<>();com.google.gson.JsonArray list=definitions.get(id);if(list!=null)for(com.google.gson.JsonElement element:list){String name=element.isJsonPrimitive()?element.getAsString():element.getAsJsonObject().get("id").getAsString();if(name.startsWith("#"))values.addAll(resolveTag(new net.minecraft.util.ResourceLocation(name.substring(1)),definitions,tags,path).getValues());else values.add(net.minecraft.util.registry.Registry.BLOCK.get(new net.minecraft.util.ResourceLocation(name)));}path.remove(id);net.minecraft.tags.ITag<Block> tag=net.minecraft.tags.Tag.create(values);tags.put(id,tag);return tag;}
'''+s[at:];s=s.replace('public static void main(String[] args){net.minecraft.util.registry.Bootstrap.bootStrap();','''public static void main(String[] args)throws Exception{net.minecraft.util.registry.Bootstrap.bootStrap();
  net.minecraft.tags.ITagCollectionSupplier supplier=net.minecraft.tags.ITagCollectionSupplier.of(vanillaTags(args[0]),net.minecraft.tags.ITagCollection.empty(),net.minecraft.tags.ITagCollection.empty(),net.minecraft.tags.ITagCollection.empty());supplier.bindToGlobal();''');s=s.replace('case "getRawBrightness":return 0;','case "getRawBrightness":return 15;');p.write_text(s,'utf-8')
p=Path('build.gradle');s=p.read_text().replace("mainClass = 'org.slavicmyths.verify.YagaPlacementHeadless'", "mainClass = 'org.slavicmyths.verify.YagaPlacementHeadless'\n    args new File(gradle.gradleUserHomeDir, 'caches/forge_gradle/minecraft_repo/versions/1.16.5/client.jar').absolutePath");p.write_text(s,'utf-8')
