package org.slavicmyths.hunt;
import net.minecraft.block.Blocks;
import net.minecraft.entity.*;
import net.minecraft.util.Direction;
import net.minecraft.util.math.*;
import net.minecraft.world.*;
import net.minecraft.world.biome.*;
import net.minecraft.world.gen.Heightmap;
import net.minecraftforge.event.world.BiomeLoadingEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.slavicmyths.registry.ModEntities;
@Mod.EventBusSubscriber(modid="slavicmyths")
public final class HuntSpawns {
 public static boolean forest(IWorld w,BlockPos p){Biome.Category c=w.getBiome(p).getBiomeCategory();return c==Biome.Category.FOREST||c==Biome.Category.TAIGA;}
 public static boolean environment(IWorld w,BlockPos p,int radius){BlockPos.Mutable q=new BlockPos.Mutable();for(int y=-radius;y<=radius;y++)for(int x=-radius;x<=radius;x++)for(int z=-radius;z<=radius;z++){if(x*x+y*y+z*z>radius*radius)continue;q.set(p.getX()+x,p.getY()+y,p.getZ()+z);if(!w.hasChunkAt(q))continue;net.minecraft.block.BlockState b=w.getBlockState(q);if(b.is(Blocks.HAY_BLOCK)||b.is(Blocks.CAMPFIRE)||b.is(Blocks.SMOKER))return true;}return false;}
 public static boolean clearSpace(IWorld w,BlockPos p,float width,float height){if(!w.hasChunkAt(p.offset(-1,0,-1))||!w.hasChunkAt(p.offset(1,0,1))||!w.hasChunkAt(p.offset(-1,0,1))||!w.hasChunkAt(p.offset(1,0,-1)))return false;
  if(!w.getBlockState(p.below()).isFaceSturdy(w,p.below(),Direction.UP)||!w.getFluidState(p.below()).isEmpty())return false;for(int y=0;y<3;y++)if(!w.getFluidState(p.above(y)).isEmpty()||!w.isEmptyBlock(p.above(y)))return false;
  return w.noCollision(new AxisAlignedBB(p.getX()+.5-width/2,p.getY(),p.getZ()+.5-width/2,p.getX()+.5+width/2,p.getY()+height,p.getZ()+.5+width/2));
 }
 public static boolean alone(net.minecraft.world.server.ServerWorld w,BlockPos p,boolean oven){return w.getEntitiesOfClass(HuntMob.class,new AxisAlignedBB(p).inflate(oven?64:72),m->m.isAlive()&&m.huntTarget()==(oven?HuntTarget.OVINNIK:HuntTarget.VOLKOLAK)).isEmpty();}
 public static boolean openBiome(IWorld w,BlockPos p){Biome.Category c=w.getBiome(p).getBiomeCategory();return c==Biome.Category.PLAINS||c==Biome.Category.EXTREME_HILLS||c==Biome.Category.SAVANNA||c==Biome.Category.ICY;}
 public static boolean airVolume(IWorld w,BlockPos p,int radius,int height){for(int x=-radius;x<=radius;x++)for(int z=-radius;z<=radius;z++){BlockPos q=p.offset(x,0,z);if(!w.hasChunkAt(q))return false;for(int y=0;y<height;y++)if(!w.isEmptyBlock(q.above(y))||!w.getFluidState(q.above(y)).isEmpty())return false;}return true;}
 public static boolean safe(IWorld w,BlockPos p,BlockPos ground,HuntTarget k){if(k==HuntTarget.FIRE_SERPENT)return w.getBlockState(ground.below()).isFaceSturdy(w,ground.below(),Direction.UP)&&w.getFluidState(ground.below()).isEmpty()&&w.canSeeSky(p)&&airVolume(w,p.getY()-ground.getY()>=4?p.below(2):p,2,5);if(k==HuntTarget.PODVEY)return clearSpace(w,p,1.1F,2.55F)&&airVolume(w,p,1,4)&&w.canSeeSky(p);return clearSpace(w,p,k==HuntTarget.OVINNIK?1.15F:1.05F,k==HuntTarget.OVINNIK?2.45F:2.25F);}
 public static HuntMob create(World w,HuntTarget k){switch(k){case OVINNIK:return ModEntities.OVINNIK.get().create(w);case VOLKOLAK:return ModEntities.VOLKOLAK.get().create(w);case FIRE_SERPENT:return ModEntities.FIRE_SERPENT.get().create(w);default:return ModEntities.PODVEY.get().create(w);}}
 public static boolean alone(net.minecraft.world.server.ServerWorld w,BlockPos p,HuntTarget k){if(k==HuntTarget.OVINNIK||k==HuntTarget.VOLKOLAK)return alone(w,p,k==HuntTarget.OVINNIK);return w.getEntitiesOfClass(HuntMob.class,new AxisAlignedBB(p).inflate(96),m->m.isAlive()&&m.huntTarget()==k&&m.distanceToSqr(p.getX()+.5,p.getY(),p.getZ()+.5)<=96*96).isEmpty();}
 private static boolean elemental(IServerWorld w,BlockPos p,java.util.Random n,HuntTarget k){net.minecraft.world.server.ServerWorld s=w.getLevel();boolean fire=k==HuntTarget.FIRE_SERPENT;return n.nextInt(!fire&&(s.isRaining()||s.isThundering())?64:192)==0&&s.dimension()==World.OVERWORLD&&s.getDifficulty()!=Difficulty.PEACEFUL&&(!s.isDay()||!fire&&s.isRaining())&&w.canSeeSky(p)&&(openBiome(w,p)||fire&&forest(w,p))&&safe(w,p,p,k)&&alone(s,p,k);}
 public static void placements(){EntitySpawnPlacementRegistry.register(ModEntities.FIRE_SERPENT.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->elemental(w,p,n,HuntTarget.FIRE_SERPENT));EntitySpawnPlacementRegistry.register(ModEntities.PODVEY.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->elemental(w,p,n,HuntTarget.PODVEY));EntitySpawnPlacementRegistry.register(ModEntities.OVINNIK.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->natural(w,p,n,true));EntitySpawnPlacementRegistry.register(ModEntities.VOLKOLAK.get(),EntitySpawnPlacementRegistry.PlacementType.ON_GROUND,Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,(t,w,r,p,n)->natural(w,p,n,false));}
 private static boolean natural(IServerWorld w,BlockPos p,java.util.Random n,boolean oven){return n.nextInt(96)==0&&w.getLevel().dimension()==World.OVERWORLD&&!w.getLevel().isDay()&&w.getDifficulty()!=Difficulty.PEACEFUL&&clearSpace(w,p,oven?1.15F:1.05F,oven?2.45F:2.25F)&&alone(w.getLevel(),p,oven)&&(oven?environment(w,p,16):forest(w,p));}
 @SubscribeEvent public static void biomes(BiomeLoadingEvent e){if(e.getName()==null||!e.getName().getNamespace().equals("minecraft"))return;Biome.Category c=e.getCategory();if(c==Biome.Category.PLAINS||c==Biome.Category.EXTREME_HILLS||c==Biome.Category.SAVANNA||c==Biome.Category.ICY){e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.FIRE_SERPENT.get(),1,1,1));e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.PODVEY.get(),1,1,1));}else if(c==Biome.Category.FOREST)e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.FIRE_SERPENT.get(),1,1,1));if(c==Biome.Category.PLAINS||c==Biome.Category.SAVANNA||c==Biome.Category.FOREST||c==Biome.Category.TAIGA)e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.OVINNIK.get(),1,1,1));if(c==Biome.Category.FOREST||c==Biome.Category.TAIGA)e.getSpawns().addSpawn(EntityClassification.MONSTER,new MobSpawnInfo.Spawners(ModEntities.VOLKOLAK.get(),1,1,1));}
}
