"""Record completed evidence without altering historical acceptance reports."""
from pathlib import Path
import hashlib,json,re
ROOT=Path(__file__).resolve().parents[1]
attempts=[]
for i in range(1,11):
 p=ROOT/f'.tools/rare-runtime-{i:02}.log';text=p.read_text(encoding='utf-8',errors='replace')
 total=re.search(r'(\d+) GAME TESTS COMPLETE',text);passed=re.search(r'All (\d+) required tests passed',text)
 failures=re.findall(r'LogTestReporter\]: (.+? failed at .+)',text)
 attempts.append({'run':i,'log':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'actual_server_launch':'Launching target' in text,'total_tests':int(total[1]) if total else None,'passed':bool(passed),'failures':failures,'native_new_process_storage':'RARE_NATIVE_STORAGE_NEW_PROCESS_PASS' in text})
p=ROOT/'.tools/rare-weapon-regression.log';text=p.read_text(encoding='utf-8',errors='replace');passed=re.search(r'All (\d+) required tests passed',text)
regression={'log':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'actual_server_launch':'Launching target' in text,'passed_tests':int(passed[1]) if passed else 0,'build_pass':'BUILD SUCCESSFUL' in text}
build=ROOT/'.tools/rare-clean-build.log';build_text=build.read_text(encoding='utf-8',errors='replace')
resources=json.loads((ROOT/'docs/verification/rare-weapons-1.3.2.2-resources.json').read_text())
assert attempts[-1]['passed'] and attempts[-1]['total_tests']==16 and regression['passed_tests']==16 and 'BUILD SUCCESSFUL' in build_text
count=sum(a['actual_server_launch'] for a in attempts)+regression['actual_server_launch']
report={'version':'1.3.2.2','date':'2026-10-08','platform':{'minecraft':'1.21.1','neoforge':'21.1.255','java':'21.0.12'},'actual_headless_server_launches':count,'client_launches':0,'final_rare_tests':'16/16 PASS','final_weapon_regression':'16/16 PASS','rare_attempts':attempts,'regression':regression,'clean_build':{'passed':True,'log':str(build),'sha256':hashlib.sha256(build.read_bytes()).hexdigest(),'gradle_test_task':'NO-SOURCE'},'resources':resources,'intermediate_failures_explanation':['Initial bleed fixture used an undead immune target; subsequent direct pulse assertion retained native hurt immunity instead of advancing time.','Native ServerPlayer equipment requires doTick; second attack fixture originally used tick.','Combined dimension/death fixture needed the native hasChangedDimension acknowledgement before kill.','PvP defaults to false in GameTestServer; shield fixture explicitly enables it and advances spawn immunity.','Mob shield fixture needed head yaw as well as body yaw after native ticks.'],'verified':['Single blade versus pair, capped bleed, real native melee, main-hand-only rune application','Staff held/offhand healing, cap, directed cast, cooldown, stun ending, morok expiring, alternate hostile target, owner/NPC damage rejection','Three Swing stacks, fourth empowered hit, pause reset, player and mob shield disable','Far hit window, fast native second attack, no self-chain, near rejection, swap cooldown','Four native bench recipes, distinct donor data for both blades, no repeated output','Actual native boss deaths and themed drops','Four marked weapons through native anvil and item pickup','Four weapons through two native dimension transitions and native death drops','Player .dat loaded by a new server process: four marked weapons and two persisted cooldowns; login clears short attack window'],'manual_pending':['Client hand rendering and animations, GUI/tooltip appearance','Two real clients and interactive PvP','Actual client logout/menu/relogin; native player .dat restart is not that test','Visual stun and control of every custom boss AI, especially scripted special moves','Measured FPS/MSPT'],'polymc_installed':False,'worlds_overwritten':False,'commit_created':False}
(ROOT/'docs/verification/rare-weapons-1.3.2.2-acceptance.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
summary=f'''## 1.3.2.2 — Редкое оружие (2026-10-08)

Реализованы парные мечи Тугарина, посох Лихо, кистень атамана и копьё победителя: разные силуэты, серверные механики, максимальная ёмкость 3 руны, 4 рецепта оружейного верстака, RU/EN. Существующие дропы Тугарина/Лихо и курганные трофеи переиспользованы; добавлен только гарантированный знак атамана дополнительным pool. Два меча крафтятся одновременно и сохраняют данные каждого донора отдельно; второй остаётся в ячейке верстака. Броня/новые руны/боссы не добавлены.

`gradlew.bat clean build` PASS; {resources['checks']:,} ресурсных/JAR-проверок PASS, {resources['preserved_old_resources']:,} прежних ресурсов побайтно сохранены, остальные изменения старых ресурсов только добавочные. Финальные headless suites: новые 16/16 + прежнее оружие 16/16. {count} реальных серверных запусков, ноль клиентов; промежуточные failures сохранены в отчёте. Проверены нативные крафт/ремонт/подбор, смерть, два dimension transitions, реальные boss drops и player .dat новым серверным процессом (4 оружия + 2 КД). Это не реальный клиентский relog; внешняя ручная приёмка остаётся открытой, FPS/MSPT не измерялись.

[Параметры, рецепты, файлы и краткая ручная приёмка](RARE_WEAPONS_1.3.2.2.md), [acceptance](verification/rare-weapons-1.3.2.2-acceptance.json), [ресурсы/JAR](verification/rare-weapons-1.3.2.2-resources.json). Production: `build/libs/slavicmyths-1.3.2.2.jar`. PolyMC остаётся на установленной 1.3.2.1; клиент/установка не запускались. Пользовательские изменения и игровые миры сохранены, commit/push не выполнялись.

'''
architecture='''Архитектура патча: `RareWeapons` регистрирует 4 оружия/1 материал; `RareCombat` использует AttackEntityEvent и damage/target/player events. `RareBleedEffect` имеет отдельную нативную cadence, `DisorientationEffect` — только effect-local bounded target search и стандартный блокирующий AI goal. Нет нового глобального world/player tick polling. Второй выпад расходует UUID/dimension-bound окно до штатного Player.attack; только его attackStrengthTicker открыт access transformer. Долгие КД сохраняются в существующем PathData по overworld clock, transient окна очищаются при login/respawn/dimension. ArmorerRecipe возвращает второй нестакающийся клинок в input remainder со своими donor components; RuneRepair и существующий main-hand RuneEffects переиспользованы. `-PrareRuntimeCheck` подключает изолированные fixtures, не входящие в production JAR. Генераторы сохраняют текущий rare overlay.

'''
for name in ('PROJECT_STATUS.md','ROADMAP.md','ARCHITECTURE.md'):
 p=ROOT/'docs'/name;old=p.read_text(encoding='utf-8');header=summary+(architecture if name=='ARCHITECTURE.md' else 'Следующий шаг — ручная приёмка текущего оружия; будущие milestone автоматически не реализуются.\n\n' if name=='ROADMAP.md' else '')
 if not old.startswith('## 1.3.2.2 — Редкое оружие'):p.write_text(header+old,encoding='utf-8')
print(json.dumps({'clean_build':'PASS','resources':resources['checks'],'final_tests':'16 + 16 PASS','server_launches':count,'client_launches':0,'jar':resources['jar'],'sha256':resources['sha256']},ensure_ascii=False))
