"""0.6.0 code-native voxel models, recipes, tags and bilingual UI text."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];A=R/'src/main/resources/assets/slavicmyths';D=R/'src/main/resources/data/slavicmyths'
def write(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def box(a,b,texture='stone'):
 return {'from':a,'to':b,'faces':{f:{'texture':'#'+texture} for f in ['north','south','east','west','up','down']}}
def model(elements,textures,item=False):
 m={'parent':'minecraft:block/block','textures':textures,'elements':elements,'ambientocclusion':True}
 if item:m['display']={'gui':{'rotation':[15,0,0],'translation':[0,0,0],'scale':[1.1,1.1,1.1]},'ground':{'rotation':[90,0,0],'translation':[0,2,0],'scale':[.5,.5,.5]},'fixed':{'rotation':[0,180,0],'translation':[0,0,0],'scale':[.7,.7,.7]},'thirdperson_righthand':{'rotation':[0,0,0],'translation':[0,2,0],'scale':[.45,.45,.45]},'firstperson_righthand':{'rotation':[0,-25,0],'translation':[1,2,0],'scale':[.6,.6,.6]}}
 return m
runes=['thunder','heat','forest','midday','shadow','protection','life','wind']
# Small, invented geometric cuts. Each stone has its own physical outline and carving.
signs=[[(7,11),(8,11),(8,10),(7,9),(6,8),(7,8),(8,8),(8,7),(7,6),(6,5)],[(6,5),(5,6),(5,7),(6,8),(7,9),(7,11),(8,10),(9,8),(10,7),(10,6),(9,5),(8,5)],[(7,5),(7,6),(7,7),(7,8),(7,9),(7,10),(6,8),(5,9),(8,7),(9,8)],[(6,6),(7,5),(8,5),(9,6),(10,7),(10,8),(9,9),(8,10),(7,10),(6,9),(5,8),(5,7),(7,12),(3,7),(12,7),(7,3)],[(5,9),(6,8),(7,7),(8,7),(9,8),(10,9),(6,6),(7,5),(8,6)],[(5,10),(6,10),(7,10),(8,10),(9,10),(10,10),(5,9),(5,8),(5,7),(6,6),(7,5),(8,5),(9,6),(10,7),(10,8),(10,9)],[(7,5),(7,6),(7,7),(6,8),(5,9),(4,9),(8,8),(9,9),(10,9)],[(4,5),(5,6),(6,6),(7,6),(8,5),(9,5),(10,6),(4,8),(5,9),(6,9),(7,9),(8,8),(9,8),(10,9),(4,11),(5,12),(6,12),(7,12),(8,11),(9,11),(10,12)]]
materials=['gray_concrete','blackstone','mossy_cobblestone','sandstone_top','purple_terracotta','stone','brown_terracotta','light_gray_concrete']
inks=['cyan_terracotta','orange_terracotta','green_terracotta','yellow_terracotta','black_terracotta','gray_terracotta','green_terracotta','light_blue_terracotta']
for i,name in enumerate(runes):
 narrow=1 if name=='shadow' else 0;thick=.5 if name=='protection' else 0
 elems=[box([4+narrow,3,7],[11-narrow,12,9+thick]),box([3+narrow,5,7.1],[12-narrow,10,9+thick]),box([5,2,7.2],[9,13,9+thick])]
 for x,y in signs[i]:
  if name=="midday" and x==12:x=11
  if name=="wind" and y>=11:y-=1
  if name=="shadow" and x>=10:x=9
  elems.append(box([x,y,9+thick],[x+.8,y+.8,9.08+thick],'cut'));elems.append(box([x+.65,y+.15,9.08+thick],[x+.85,y+.85,9.12+thick],'edge'))
 write(A/f'models/item/rune_{name}.json',model(elems,{'stone':'minecraft:block/'+materials[i],'cut':'minecraft:block/'+inks[i],'edge':'minecraft:block/stone','particle':'minecraft:block/'+materials[i]},True))
# Stone: raised rough base, stepped taper, four different carved faces.
e=[box([1,0,1],[15,3,15]),box([3,3,3],[13,5,13]),box([4,5,4],[12,20,12]),box([4.5,20,4.5],[11.5,24,11.5]),box([3.5,6,5],[4.2,16,10],'moss'),box([11.8,5,6],[12.4,10,9],'moss')]
pathsigns=[[(6,17),(7,17),(8,17),(9,17),(6,16),(9,16),(6,15),(9,15),(7,14),(8,14),(10,15),(10,18)],[(7,14),(7,15),(7,16),(7,17),(6,16),(8,17),(5,15),(9,15),(5,17),(9,17)],[(6,14),(7,15),(8,16),(9,17),(7,17),(9,15)],[(6,14),(7,15),(8,16),(9,17),(6,17),(7,16),(8,15),(9,14),(5,15),(10,15)]]
for face,pts in enumerate(pathsigns):
 for x,y in pts:
  a,b=([x,y,3.94],[x+.65,y+.65,4.01]) if face==0 else ([x,y,11.99],[x+.65,y+.65,12.06]) if face==1 else ([3.94,y,x],[4.01,y+.65,x+.65]) if face==2 else ([11.99,y,x],[12.06,y+.65,x+.65])
  e.append(box(a,b,'cut'))
write(A/'models/block/path_stone.json',model(e,{'stone':'minecraft:block/stone','moss':'minecraft:block/mossy_cobblestone','cut':'minecraft:block/gray_concrete','particle':'minecraft:block/stone'}))
e=[box([1,0,2],[15,3,14]),box([5,3,5],[11,10,11]),box([0,10,2],[16,13,14]),box([1,13,3],[6,15,13],'top'),box([10,13,3],[15,15,13],'top'),box([6,13,3],[10,15,6],'top'),box([6,13,10],[10,15,13],'top'),box([6,13,6],[10,13.6,10],'cut')]
for x in [4,7,10]:e.append(box([x,11,1.94],[x+1,12,2.01],'cut'))
write(A/'models/block/runic_anvil.json',model(e,{'stone':'minecraft:block/anvil','top':'minecraft:block/smooth_stone','cut':'minecraft:block/gray_concrete','particle':'minecraft:block/anvil'}))
for name in ['path_stone','runic_anvil']:
 write(A/f'blockstates/{name}.json',{'variants':{'':{'model':'slavicmyths:block/'+name}}});write(A/f'models/item/{name}.json',{'parent':'slavicmyths:block/'+name})
 write(D/f'loot_tables/blocks/{name}.json',{'type':'minecraft:block','pools':[{'rolls':1,'entries':[{'type':'minecraft:item','name':'slavicmyths:'+name}],'conditions':[{'condition':'minecraft:survives_explosion'}]}]})
def recipe(name,pattern,keys):write(D/f'recipes/{name}.json',{'type':'minecraft:crafting_shaped','pattern':pattern,'key':{k:{'item':v if ':' in v else 'slavicmyths:'+v} for k,v in keys.items()},'result':{'item':'slavicmyths:'+name}})
recipe('path_stone',[' S ','CAC','CCC'],{'S':'ancient_sign','C':'minecraft:cobblestone','A':'amber'})
recipe('runic_anvil',['III',' P ','SSS'],{'I':'minecraft:iron_ingot','P':'perunite','S':'minecraft:stone'})
tags={'rune_staff':['carved_staff','storm_staff'],'rune_dagger':['silver_dagger','bone_knife','ritual_knife'],'rune_spear':['spear','silver_spear','thunder_spear','berdysh'],'rune_heavy':['mace','perunite_mace','battle_axe','thunder_axe','berdysh'],'rune_capacity_1':['club','carved_staff','bone_knife','spear'],'rune_capacity_3':['perunite_sword','perunite_axe','perunite_mace','perunite_shield','thunder_spear','thunder_axe','storm_staff'],'no_reforging':[]}
for tag,vals in tags.items():write(D/f'tags/items/{tag}.json',{'replace':False,'values':['slavicmyths:'+s for s in vals]})
adv=[('own_path','path_stone','Свой путь','Your Own Path','Выберите основной путь.','Choose your main path.'),('rune_installed','rune_thunder','Знак на стали','Sign on Steel','Установите первую руну.','Install your first rune.'),('reforged','runic_anvil','Перекованный','Reforged','Откройте второе гнездо.','Open a second rune socket.'),('three_signs','rune_protection','Три знака','Three Signs','Заполните три гнезда.','Fill three rune sockets.')]
for name,icon,*_ in adv:write(D/f'advancements/{name}.json',{'parent':'slavicmyths:root','display':{'icon':{'item':'slavicmyths:'+icon},'title':{'translate':f'advancements.slavicmyths.{name}.title'},'description':{'translate':f'advancements.slavicmyths.{name}.description'},'frame':'task','show_toast':True,'announce_to_chat':False,'hidden':False},'criteria':{'done':{'trigger':'minecraft:impossible'}}})
paths=['druzhinnik','vedun','razboinik','koldun'];pathru=['Дружинник','Ведун','Разбойник','Колдун'];pathen=['Retainer','Seer','Outlaw','Sorcerer']
skills=['drill','heavy_hand','riposte','shield_bash','stance','sweep','herbs','spirit_sense','charm_power','offering','healing_brew','quiet_step','light_step','ambush','aim','dodge','hunter','precision','sign_sense','rune_knowledge','spark','staff_power','resonance','storm_sign']
skillru=['Строевая выучка','Крепкая рука','Ответный удар','Удар щитом','Стойка','Размашистый удар','Знание трав','Чутьё духов','Сила оберега','Дар духам','Целебный отвар','Тихий шаг','Лёгкий шаг','Удар исподтишка','Меткий выстрел','Уклонение','Охотничий инстинкт','Смертельная точность','Чутьё знаков','Руническое знание','Искра','Сила посоха','Рунический отклик','Грозовой знак']
skillen=['Shield Drill','Heavy Hand','Riposte','Shield Bash','Stance','Sweeping Blow','Herbal Lore','Spirit Sense','Charm Power','Spirit Offering','Healing Brew','Quiet Step','Light Step','Ambush','True Shot','Dodge','Hunter Instinct','Deadly Precision','Sign Sense','Rune Knowledge','Spark','Staff Power','Rune Resonance','Storm Sign']
descru=['На 15% слабее отбрасывание с оружием или щитом.','+0,75 урона тяжёлым оружием.','После блока следующий удар за 1,75 с получает +1,5 урона.','G: удар щитом на 3 блока, 2 урона и толчок. Откат 10 с.','G: стойкость и замедление на 5 с. Откат 35 с.','G: следующий тяжёлый удар за 5 с задевает до 3 соседей. Откат 35 с.','Лесная смесь и ягодный морс дают краткую регенерацию.','ПКМ по духу показывает его настроение или благосклонность.','Известные обереги в левой руке защищают немного сильнее.','Дары Домовому дают +20% дружбы; мир Полевика и Банника длится на 15% дольше.','Ягодный морс лечит 1 сердце дополнительно. Откат 10 с.','Банник и Кикимора накапливают настороженность на 25% медленнее.','Скорость крадущегося шага +12%.','Первый скрытый удар по не нападающей цели: +2 кинжалом, +1 другим оружием.','Полностью натянутый лук: +10% базового урона стрелы.','G: короткий рывок по направлению взгляда. Откат 10 с.','+1 урона в ближнем бою против обычных животных.','Раз в 20 с: +20% полного выстрела или +2 урона первого скрытого удара кинжалом.','Дополнительные подсказки о рунах и ритуальных предметах.','Рунические операции дешевле до 15%, округление вверх.','G с посохом: направленный импульс на 8 блоков, 3 урона. Откат 5 с.','Существующая сила грозового посоха и импульсы усилены на 12%.','Откат рунических срабатываний короче на 10%.','G с посохом: направленный разряд, 5 урона, без огня. Откат 25 с.']
descen=['15% less knockback while holding a weapon or shield.','+0.75 damage with heavy weapons.','After a block, your next melee hit within 1.75 seconds gains 1.5 damage.','G: shield strike within 3 blocks, 2 damage and a push. 10s cooldown.','G: resistance and slowness for 5s. 35s cooldown.','G: next heavy hit within 5s strikes up to 3 neighbours. 35s cooldown.','Forest mix and berry mors grant brief regeneration.','Interact with a spirit to read its mood or approximate favour.','Known charms in your offhand provide slightly stronger protection.','Domovoy gifts give 20% more favour; Polevik and Bannik peace lasts 15% longer.','Berry mors additionally heals one heart. 10s cooldown.','Bannik and Kikimora become suspicious 25% more slowly.','12% faster sneaking.','First sneaking hit against an unaware target: +2 dagger damage, +1 otherwise.','Fully drawn bow: 10% more base arrow damage.','G: a short dash in your facing direction. 10s cooldown.','+1 melee damage against ordinary animals.','Every 20s: +20% full bow shot or +2 on a first sneaking dagger hit.','Additional hints for runes and ritual items.','Rune operations cost up to 15% less XP, rounded up.','G with staff: an aimed 8-block pulse for 3 damage. 5s cooldown.','Storm staff and path pulses gain 12% damage.','Rune proc cooldowns are 10% shorter.','G with staff: an aimed discharge for 5 damage, no fire. 25s cooldown.']
ui={
'need_xp':('Нужно уровней XP: %s','XP levels required: %s'),
'secondary_locked':('Побочный путь: нужны 3 навыка основного, выбрать можно только один другой путь.','Secondary path needs 3 main skills; choose one different path only.'),
'init_druzhinnik':('Стоимость: 10 уровней, железный меч и щит. Предметы расходуются.','Cost: 10 levels, iron sword and shield. Items are consumed.'),
'init_vedun':('Стоимость: 10 уровней, простой оберег и 4 полыни.','Cost: 10 levels, warding charm and 4 wormwood.'),
'init_razboinik':('Стоимость: 10 уровней, лук и серебряный кинжал.','Cost: 10 levels, bow and silver dagger.'),
'init_koldun':('Стоимость: 10 уровней, резной посох и древний знак.','Cost: 10 levels, carved staff and ancient sign.'),
'chosen':('Выбран путь: %s','Path chosen: %s'),'skill_locked':('Навык недоступен: выберите путь; побочный ограничен первыми 3 навыками.','Skill locked: choose a path; secondary only grants the first 3 skills.'),
'prerequisite':('Нужен навык: %s','Requires skill: %s'),'knowledge':('Нужно знание: %s','Requires discovery: %s'),'learned':('Изучено: %s','Learned: %s'),
'unsupported':('Положите один совместимый предмет в первый слот.','Place one compatible item in the first slot.'),'capacity':('Достигнут предел гнёзд этого предмета.','This item has reached its socket limit.'),
'forge_materials_0':('0 → 1: 3 железных слитка, 6 уровней XP.','0 → 1: 3 iron ingots, 6 XP levels.'),
'forge_materials_1':('1 → 2: 2 серебряных слитка, древний знак, 15 уровней XP.','1 → 2: 2 silver ingots, ancient sign, 15 XP levels.'),
'forge_materials_2':('2 → 3: 3 перунита, коготь Овинника, 28 уровней XP.','2 → 3: 3 perunite, Ovinnik claw, 28 XP levels.'),
'forge_materials_3':('Предельная перековка завершена.','Maximum reforging reached.'),
'need_rune':('Положите руну во второй слот.','Place a rune in the second slot.'),'socket_full':('Нет свободного гнезда или такая руна уже установлена.','No free socket, or that rune is already installed.'),'no_rune':('Это гнездо пусто.','This socket is empty.'),'operation_done':('Операция завершена. Заберите предмет из первого слота.','Done. Take your item from the first slot.'),
'select_ability':('Выберите изученную активную способность у Камня Пути кнопкой G.','Select a learned active ability using G at the Path Stone.'),'ability_equipment':('Нужен щит, тяжёлое оружие или посох для выбранной способности.','Equip the shield, heavy weapon or staff required by your ability.'),'cooldown':('%s: %s с','%s: %ss'),'no_target':('Нет видимой цели перед вами.','No visible target ahead.'),'activated':('Применено: %s','Activated: %s'),
'sockets':('Рунические гнёзда: %s / %s','Rune sockets: %s / %s'),'free_slots':('Свободных гнёзд: %s','Free sockets: %s'),
'ritual_hint':('Ритуальный компонент: предложите алтарю в нужной последовательности.','Ritual component: offer to the altar in the correct order.'),
'favor_low':('Благосклонность: низкая','Favour: low'),'favor_medium':('Благосклонность: средняя','Favour: medium'),'favor_high':('Благосклонность: высокая','Favour: high'),'hostile':('Дух враждебен','Spirit: hostile'),'wary':('Дух насторожен','Spirit: wary'),'calm':('Дух спокоен','Spirit: calm'),
'forge':('Перековка','Reforge'),'install':('Установка','Install'),'remove':('Удалить %s','Remove %s'),'confirm_path':('Подтвердить: выбор постоянный','Confirm permanent choice'),'choose_path':('Выбрать показанный путь','Choose displayed path'),
'item':('Предмет','Item'),'material':('Материал','Material'),'catalyst':('Катализатор','Catalyst'),'remove_warning':('Удаление: 2 XP, руна уничтожается.','Removal: 2 XP; the rune is destroyed.'),'paths_info':('Основной: %s / Побочный: %s','Main: %s / Secondary: %s'),'xp':('Доступно уровней XP: %s','Available XP levels: %s'),'none':('нет','none'),'main_only':('Только основной путь.','Main path only.'),'install_help':('Установка: 7 XP и руна; нужен свободный слот.','Installation: 7 XP and a rune; needs a free socket.')}
runeru=['Грома','Жара','Леса','Полудня','Тени','Защиты','Жизни','Ветра']
runeen=['Thunder','Heat','Forest','Midday','Shadow','Protection','Life','Wind']
rhint_ru=['Периодический разряд; клинок, лук, щит и посох действуют по-разному.','Короткое воспламенение цели с откатом; блоки не горят.','Сила в лесу: удар, скорость стрелы, краткая защита или регенерация.','Слабое усиление под открытым дневным небом.','Скрытый удар и лук в темноте; ускорение мечника ночью.','Краткая стойкость после удара или блока с откатом.','Малое лечение после убийства, помощь посоху или щиту. Большой откат.','Толчок оружием или щитом, ускорение стрелы, порыв посоха.']
rhint_en=['Periodic discharge; blades, bows, shields and staves behave differently.','Brief ignition with a cooldown; never places fire blocks.','Forest bonuses: hit damage, arrow speed, brief resistance or regeneration.','A small bonus under open daylight.','Ambush and bow bonuses in darkness; night sword hits grant speed.','Brief resistance after a hit or block, with a cooldown.','Small healing on kills, staff use or low-health blocks. Long cooldown.','Weapon or shield push, faster arrows, and a staff gust.']
for lang,l in [('ru_ru',0),('en_us',1)]:
 p=A/f'lang/{lang}.json';o=json.loads(p.read_text(encoding='utf-8'))
 for id,ru,en in zip(paths,pathru,pathen):o['path.slavicmyths.'+id]=[ru,en][l]
 for i,id in enumerate(skills):o['skill.slavicmyths.'+id]=[skillru,skillen][l][i];o['skill.slavicmyths.'+id+'.desc']=[descru,descen][l][i]
 for k,v in ui.items():o['rpg.slavicmyths.'+k]=v[l]
 for i,id in enumerate(runes):o['item.slavicmyths.rune_'+id]=('Руна '+runeru[i]) if l==0 else ('Rune of '+runeen[i]);o['rpg.slavicmyths.rune_'+id]=[rhint_ru,rhint_en][l][i]
 o['block.slavicmyths.path_stone']=['Камень Пути','Path Stone'][l];o['block.slavicmyths.runic_anvil']=['Рунная наковальня','Runic Anvil'][l]
 o['key.slavicmyths.path_ability']=['Способность Пути','Path Ability'][l];o['key.categories.slavicmyths']='Slavic Myths'
 for id,icon,ru,en,rd,ed in adv:o[f'advancements.slavicmyths.{id}.title']=[ru,en][l];o[f'advancements.slavicmyths.{id}.description']=[rd,ed][l]
 o['book.slavicmyths.paths.title']=['Пути','Paths'][l]
 o['book.slavicmyths.paths.text']=['Пути — игровая система, а не историческая классификация. Найдите малое святилище в новых равнинных или лесных чанках либо создайте Камень Пути. Инициация стоит 10 уровней и два дара; выбор постоянный. Навыки покупаются за обычные уровни XP, старшие требуют открытий. После трёх навыков можно выбрать один побочный путь с доступом лишь к первым трём навыкам. У Камня выберите активный навык кнопкой G, затем нажмите G в мире. Прогресс сохраняется после смерти.','Paths are a game system, not a historical classification. Find a small shrine in new plains or forest chunks, or craft a Path Stone. Initiation costs 10 levels and two offerings; the choice is permanent. Buy skills with vanilla levels; later skills need discoveries. After three skills choose one secondary path, limited to its first three skills. Select an active ability with G at the stone, then press G in the world. Progress survives death.'][l]
 o['book.slavicmyths.runes.title']=['Руны','Runes'][l]
 o['book.slavicmyths.runes.text']=['Руны — вымышленные знаки Slavic Myths, не исторический канон. Получайте их обрядами на алтаре: Гром — громовой камень, перунит, древний знак; Жар — ритуальный уголь, угольное сердце, знак; Лес — сердце Лешего, полынь, знак; Полдень — сухой колос, серебро, знак; Тень — прядь Кикиморы, серебро, знак; Защита — серебро, простой оберег, знак; Жизнь — цветок папоротника, бутылочка мёда, знак; Ветер — перо, кипрей, знак. Порядок важен; рецепты также видны в JEI. Класс для рун не нужен.','Runes are fictional Slavic Myths signs, not historical canon. Offer in order at the altar: Thunder — thunder stone, perunite, ancient sign; Heat — ritual charcoal, ember heart, sign; Forest — Leshy heart, wormwood, sign; Midday — noon ear, silver, sign; Shadow — Kikimora lock, silver, sign; Protection — silver, warding charm, sign; Life — fern flower, honey bottle, sign; Wind — feather, fireweed, sign. Recipes are also visible in JEI. Runes require no class.'][l]
 o['book.slavicmyths.reforging.title']=['Перековка','Reforging'][l]
 o['book.slavicmyths.reforging.text']=['У Рунной наковальни положите оружие в первый слот, материал во второй, катализатор в третий. Первая перековка: 3 железа и 6 уровней. Вторая: 2 серебра, древний знак, 15 уровней. Третья: 3 перунита, коготь Овинника, 28 уровней. Предел зависит от предмета: дерево и камень — 1, железо и серебро — 2, перунит и алмаз — 3. Установка стоит 7 уровней и руну, удаление — 2 уровня и уничтожает руну. Повторы запрещены. Забирайте предмет из первого слота; при закрытии всё возвращается. Ванильные чары, имя и прочность сохраняются.','At a Runic Anvil put the weapon in slot one, material in slot two, catalyst in slot three. First socket: 3 iron and 6 levels. Second: 2 silver, an ancient sign, 15 levels. Third: 3 perunite, an Ovinnik claw, 28 levels. Caps: wood and stone 1; iron and silver 2; perunite and diamond 3. Installing costs 7 levels and a rune; removal costs 2 levels and destroys the rune. No duplicate runes. Take the result from slot one; closing returns all items. Vanilla enchantments, name and durability are preserved.'][l]
 write(p,o)
print('0.6.0 resources generated')
