"""Editable pixel masters and cuboid profiles for the final 0.4.6 art pass."""
import json
from generate_045 import Art, C, encode

# One character is one deliberately placed texel; no smoothing or resampling.
SPRITES = {
'thunder_axe': '''
................
....SDN.....N...
...SWADNN..NAN..
..SWADDDN.NAcN..
.SWADNccNNADAN..
.SADNNcADNAADN..
.DNNNAccDNAAN...
..NNADDDNDTN....
...NDDNNSTUN....
....NN..DBU.....
.......DTU......
......DUB.......
.....DTU........
....UBU.........
...DTU..........
...NU...........
''',
'carved_staff': '''
.........uUU....
........uTBuU...
........TB.uTu..
........UBUTBu..
.........UTBu...
.........TBuu...
........uTU.....
........TB......
.......UTu......
......uWU.......
......WBu.......
.....uTU........
.....TB.........
....UTu.........
...uTU..........
...UBu..........
''',
'storm_staff': '''
..........N.....
.........AcN....
........AcWAN...
........NAcAN...
.......STNAAS...
........ySTDN...
........UTBU....
........TBU.....
.......UTu......
......uSU.......
......ABu.......
.....uTU........
.....TB.........
....UTu.........
...uSU..........
...NAu..........
''',
'retainer_shield': '''
................
......DDDD......
....DSSSAsDD....
...DSTBtUBUsD...
..DSBTBuUBUBsD..
..DSTBUDDUBUsD..
..DSTUDWSDBUsD..
..DSBDSWASDUsD..
..DSBDSADNDUsD..
..DSBUDAADBUsD..
..DABTBuuBUBDD..
...DABBuUBBDD...
....DABBUBDD....
.....DADDDD.....
......DDD.......
................
''',
'perunite_shield': '''
................
.....NSSADN.....
...NSAAAADDNN...
..NSADNDNDDADN..
..NAyNNANNNyDN..
..NADNAcADNDDN..
..NANDcWNDNDDN..
..NANAcADNNDDN..
..NANDAccDNDDN..
..NADNNcADNDDN..
...NADNANDDDN...
...NAyNNNNyDN...
....NADNDDDN....
.....NADDDN.....
......NDDN......
.......NN.......
''',
'lore_book': '''
................
.....uuuuuuu....
...uUTTTTTTUu...
..uTUUNNNNUUeu..
..uTUNADNNUWeu..
..uTUNNBNNUetu..
..uTUNBTBNUWeu..
..uTUNUBUNUetu..
..uTUNNUNSSWeu..
..uTUNNNNSySeu..
..uTUUNNNNUWeu..
..uUTTTTTTUetu..
...uWeeeeeeeeu..
...ueetttttttu..
....uuuuuuuuu...
................
''',
'ancient_sign': '''
................
.......UU.......
......TByU......
.....TBUUu......
....TyBUBTU.....
...TBUqyUBTU....
...TBqUUBBTU....
...UBBUyUBBU....
....TBUyBUU.....
....TBqyBTU.....
...TByUqyBTU....
...UBUBUBBUU....
....UBqyBUU.....
.....UBBUU......
......UU........
................
''',
'idol_fragment': '''
................
.......UTU......
....UTTBUBU.....
...UTTBUUBU.....
...TBUuUBTU.....
...TBUuUTBu.....
...TBUUTTBu.....
....UBUTUBU.....
....TBuuUBU.....
...UTBUuTBU.....
...TBUUTBU......
....UUTBU.......
.....UBU........
......U.........
................
................
''',
'ancient_coin': '''
................
................
.....UTTTUU.....
....TyTByBUU....
...TyBqUBqBUU...
...TTqUyUBBUU...
...TBUTTUUBUU...
...TBUUTTUBUU...
...UBqUyUqBUU...
...UTBBUBBBUU...
....UTBqBBUU....
.....UUUUUU.....
.......UU.......
................
................
................
''',
'amber': '''
................
................
.......OOO......
.....OYyyoO.....
....OYWyyyoO....
...OYyyyyooO....
...OyyoyyoooO...
...OyyoUoyooO...
...OyooUByooO...
...OoyoBoyooO...
....OoyyyooO....
....OoyyoOO.....
.....OOOO.......
................
................
................
''',
'warding_charm': '''
................
.....UUUUU......
....UT...BU.....
....TU...UB.....
.....TU.UB......
......TBU.......
.....UTBTU......
....TBBeBBU.....
....TBeTeBU.....
....TBTeTBU.....
....UBBeBBU.....
.....UBBBU......
......UBU.......
......BeU.......
.....BU.eU......
................
''',
'perun_charm': '''
................
.....UUUUUU.....
....UB....BU....
....TU....UB....
.....TU..UB.....
......TyyU......
.......SD.......
....NSAADDN.....
....NAccDNN.....
.....NAcAN......
......ScN.......
......SAD.......
.......N........
................
................
................
''',
'amber_charm': '''
................
.....UUUUU......
....TU...BU.....
....TU...UB.....
.....TU.UB......
......SyD.......
.....DOOAD......
....SOYyoAD.....
....SYWyooD.....
....SyyUyOD.....
....DOoUyOD.....
.....DOyoD......
......DDD.......
................
................
................
''',
'forest_charm': '''
................
.....UUUUU......
....TU...BU.....
....TU...UB.....
.....TU.UB......
......TBU.......
.......GU.......
.....gLGu.......
....gLGLgu......
....LGGLGgu.....
....GgGGLGu.....
.....gLGGgu.....
......gGgu......
.......Bu.......
.......U........
................
''',
'hunter_charm': '''
................
.....UUUUU......
....TU...BU.....
....TU...UB.....
.....TU.UB......
......TBU.......
.....UrrBU......
.....WeeeU......
.....WeetU......
.....WeetU......
.....WetU.......
.....WetU.......
.....WtU........
.....tU.........
.....U..........
................
''',
'traveler_charm': '''
................
.....UUUUU......
....TU...BU.....
....TU...UB.....
.....TU.UB......
......TBU.......
.....UTTU.......
....TWetTU......
....TUTBUU......
.....TTBU.......
....TWeetU......
.....UtBU.......
......UU........
................
................
................
''',
}

def finish(res):
    def tex(name,a,folder='block'):
        (res/f'textures/{folder}/{name}.png').write_bytes(encode(a.rows() if isinstance(a,Art) else a))
    for name,master in SPRITES.items():
        rows=master.strip().splitlines()
        assert len(rows)==16 and all(len(r)==16 for r in rows),name
        tex(name,rows,'item')

    # Related weapons share construction, while materials and proportions differ.
    for name in ('silver_sword','perunite_sword','silver_dagger','bone_knife','ritual_knife',
                 'perunite_axe','battle_axe','club','spear','silver_spear','ritual_bowl'):
        a=Art()
        if name in ('silver_sword','perunite_sword','silver_dagger','ritual_knife','bone_knife'):
            per=name=='perunite_sword';bone=name=='bone_knife'
            edge='N' if per else ('U' if bone else 'D')
            mid='A' if per else ('e' if bone else 'S');lit='s' if per else 'W'
            short=name in ('silver_dagger','ritual_knife','bone_knife')
            # A closed, tapered blade with one bright bevel and one shaded bevel.
            for x,y,w in ((13,2,1),(12,3,2),(11,4,3),(10,5,3),(9,6,3),(8,7,3),(7,8,3)):
                if short and y<4:continue
                a.line(x,y,x+w-1,y,edge);a.dot(x,y,lit)
                if w>1:a.dot(x+1,y,mid)
            a.line(6,9,9,12,'U');a.line(5,9,8,12,'y' if per or name=='ritual_knife' else 'A')
            a.dot(5,9,'T' if per else 'W');a.dot(9,12,edge)
            a.line(2,13,5,10,'u');a.line(3,14,6,11,'B');a.dot(4,12,'T');a.dot(3,13,'U')
            a.line(1,14,2,15,'S' if not per else 'A');a.dot(2,14,'y' if per else 'W')
            if per:a.dot(11,4,'c');a.dot(10,5,'a');a.dot(9,6,'c')
            if bone:a.dot(12,4,'.');a.dot(11,5,'t');a.dot(8,8,'t');a.dot(6,10,'e')
            if name=='ritual_knife':a.dot(6,11,'r');a.dot(4,13,'r');a.dot(10,6,'y')
        elif name in ('perunite_axe','battle_axe'):
            a.line(4,14,11,4,'u');a.line(5,14,12,4,'B');a.line(6,12,9,8,'T');a.dot(5,13,'U')
            per=name=='perunite_axe'
            rows=['....DSSDD.......','...DSAAADD......','..DSADDNDD......','..SADNNNDD......','..SADNNNDD......','...DNN.DDD......']
            for yy,row in enumerate(rows):
                for xx,c in enumerate(row):
                    if c!='.':a.dot(xx,yy+2,c if per else {'N':'D','D':'s','A':'S','S':'W'}.get(c,c))
            a.box(10,4,11,6,'A');a.dot(10,4,'S');a.dot(12,5,'D')
            if per:a.line(5,4,7,5,'a');a.dot(6,4,'c');a.dot(7,6,'c')
        elif name=='club':
            a.line(3,14,9,6,'u');a.line(4,14,10,6,'B');a.line(5,12,8,8,'t')
            for x,y,w in ((9,1,3),(7,2,6),(6,3,7),(6,4,6),(7,5,5),(7,6,4),(8,7,2)):
                a.line(x,y,x+w-1,y,'u');a.line(x+1,y,x+w-2,y,'B')
                a.dot(x+1,y,'T' if y<5 else 't')
            a.line(9,2,9,4,'U');a.dot(11,3,'t');a.line(7,5,10,6,'D');a.dot(7,5,'S')
            a.line(3,13,5,14,'e');a.dot(3,15,'u')
        elif name in ('spear','silver_spear'):
            a.line(2,15,10,6,'u');a.line(3,15,11,6,'B');a.line(4,13,9,8,'t')
            a.line(9,7,11,8,'D');a.dot(9,7,'e');a.dot(10,8,'S')
            a.line(10,6,13,1,'D');a.line(11,6,13,2,'S');a.line(12,5,13,2,'W')
            a.dot(10,5,'W');a.dot(12,6,'A');a.dot(13,4,'D')
            if name=='silver_spear':a.dot(13,1,'W');a.dot(11,4,'W');a.dot(11,6,'S');a.dot(9,8,'y')
            else:a.dot(11,4,'s');a.dot(12,3,'S');a.dot(13,1,'S')
        else:
            a.line(3,5,12,5,'Q');a.line(2,6,13,6,'S');a.line(3,7,12,7,'N')
            a.line(3,8,12,8,'D');a.line(4,9,11,9,'s');a.line(5,10,10,10,'D')
            a.line(4,8,6,9,'S');a.box(7,11,8,12,'D');a.dot(7,11,'S')
            a.line(5,13,10,13,'S');a.line(4,14,11,14,'D');a.dot(5,13,'W')
        tex(name,a,'item')

    # Clustered stone, with cracks following material rather than a repeated grid.
    stone=['ssssssssssssssss','ssqqqssssDDsssss','sqQQqqsssDDDssss','ssqqqsssssDsssss',
           'sssssssqqsssssss','sDDsssqqQQqsssss','ssDDssqqqQqsssDs','sssDssssqqssssDD',
           'ssssssssssssssDs','ssqqqssssssqqsss','sqQQqqsssqqQQqss','ssqqqssssqqqqsss',
           'sssssssDDsssssss','sssssssDDDssssss','ssqqssssDDsssqqs','ssqqqssssssssqqs']
    def rock():
        a=Art();a.a=[list(r) for r in stone];return a
    for name in ('silver_ore','perunite_ore'):
        a=rock()
        for x,y,w in ((2,2,3),(11,3,2),(6,7,3),(1,11,2),(11,12,3)):
            a.line(x,y,x+w,y,'D');a.line(x,y+1,x+w,y+1,'N')
            a.line(x,y,x+w-1,y,'S' if name=='silver_ore' else 'A')
            a.line(x+1,y+1,x+w,y+1,'Q' if name=='silver_ore' else 'n')
            a.dot(x,y,'W' if name=='silver_ore' else 'c')
            a.dot(x+w,y+2,'D');a.dot(x+1,y+2,'s')
        tex(name,a)
    for name in ('altar','altar_rim','altar_top'):
        a=rock()
        if name=='altar':
            a.line(0,4,15,4,'D');a.line(0,5,15,5,'q');a.line(5,0,5,3,'D');a.line(11,6,11,15,'D')
            a.line(0,12,10,12,'D');a.line(0,13,10,13,'q');a.dot(5,3,'N')
        elif name=='altar_rim':
            a.line(0,1,15,1,'Q');a.line(0,3,15,3,'D');a.line(0,12,15,12,'D');a.line(0,14,15,14,'N')
            for x in (2,8,13):a.line(x,6,x+1,7,'D');a.line(x+1,7,x,9,'D');a.dot(x+1,6,'Q')
        else:
            a.line(2,3,6,2,'D');a.line(6,2,12,3,'D');a.line(12,3,13,11,'D');a.line(13,11,9,13,'D');a.line(9,13,3,12,'D')
            a.line(3,12,2,6,'D');a.line(8,5,6,8,'N');a.line(6,8,9,8,'N');a.line(9,8,7,11,'N');a.dot(8,5,'Q')
            a.line(0,0,2,1,'D');a.line(2,1,2,4,'D');a.line(15,13,12,14,'D')
        tex(name,a)

    def wood(pale=False):
        a=Art();a.box(0,0,15,15,'e' if pale else 'B')
        for x,y,l in ((1,0,6),(5,2,5),(10,0,3),(14,3,8),(3,9,6),(8,10,5),(11,7,6)):
            a.line(x,y,x,y+l,'t' if pale else 'U');a.line(x+1,y,x+1,y+max(1,l-2),'W' if pale else 't')
        a.line(7,4,6,6,'t' if pale else 'U');a.line(6,6,7,8,'t' if pale else 'U')
        return a
    for name in ('carved_oak_pillar','carved_oak_block','carved_birch_planks','wall_carving','hearth','hearth_top','ancient_idol'):
        pale=name=='carved_birch_planks';a=wood(pale)
        if name.startswith('carved') or name=='wall_carving':
            for y in (1,14):a.line(0,y,15,y,'U' if pale else 'u');a.line(0,y+1,15,y+1,'W' if pale else 't')
            strokes=([(5,3,9,6),(9,6,5,10),(5,10,9,13)] if name=='carved_oak_pillar' else
                     [(3,5,6,3),(6,3,11,7),(11,7,7,11),(7,11,3,7),(3,7,6,5)] if name=='carved_oak_block' else
                     [(3,4,7,7),(11,4,7,7),(7,7,7,12),(3,9,7,12),(11,9,7,12)] if name=='wall_carving' else
                     [(2,5,5,8),(5,8,8,5),(8,5,11,8),(11,8,14,5)])
            for x,y,xx,yy in strokes:
                a.line(x,y+1,xx,yy+1,'W' if pale else 't');a.line(x,y,xx,yy,'U' if pale else 'u')
        elif name=='hearth_top':
            a.line(0,0,15,0,'T');a.line(0,15,15,15,'u');a.line(0,5,15,5,'U');a.line(0,11,15,11,'U')
        elif name=='ancient_idol':
            a.line(3,2,6,6,'u');a.line(6,6,3,10,'u');a.line(4,3,7,6,'t');a.line(11,8,11,14,'u')
        tex(name,a)
    a=wood();a.line(2,3,6,4,'u');a.line(9,4,13,3,'u');a.line(3,5,6,5,'u');a.line(10,5,12,5,'u')
    a.line(7,4,7,10,'T');a.line(8,5,9,10,'U');a.line(5,12,10,12,'u');a.line(5,13,10,13,'t');tex('idol_front',a)
    a=wood();a.box(0,0,15,15,'u');a.line(2,0,2,15,'U');a.line(12,0,12,15,'U');tex('hearth_dark',a)
    a=Art();a.box(0,0,15,15,'e')
    for x in range(16):
        a.line(x,0,x,15,'W' if x<3 else ('t' if x>12 else 'e'))
    a.line(5,0,5,6,'W');a.line(6,2,6,7,'t');a.dot(5,7,'W');a.line(10,0,10,3,'W');tex('candle_wax',a)
    a=Art();a.box(0,0,15,15,'D');a.line(0,0,15,0,'S');a.line(0,1,15,1,'A');a.line(0,13,15,13,'N');tex('candle_holder',a)
    a=Art();a.line(7,2,7,4,'o');a.line(8,3,9,6,'o');a.box(6,5,9,10,'o');a.box(7,6,8,10,'y');a.dot(7,8,'W');a.line(7,11,7,13,'u');tex('candle_flame',a)
    a=Art();a.box(0,0,15,15,'t')
    for x,y,xx,yy,c in ((0,1,7,3,'e'),(9,0,15,2,'y'),(1,5,10,7,'B'),(0,8,6,9,'y'),(8,8,15,10,'e'),(0,12,9,14,'e'),(10,12,15,13,'B'),(1,3,5,5,'y'),(11,4,15,5,'e'),(3,10,8,12,'B'),(10,14,14,15,'y')):
        a.line(x,y,xx,yy,c)
    for y in (4,11):a.line(0,y,15,y,'U');a.line(0,y+1,15,y+1,'B')
    tex('straw_block',a)
    a=Art();a.box(0,0,15,15,'o');a.line(0,0,15,0,'y');a.line(0,0,0,15,'y');a.line(15,1,15,15,'O');a.line(1,15,15,15,'O')
    for x,y,xx,yy,c in ((2,2,6,1,'Y'),(2,3,1,7,'y'),(4,5,10,2,'y'),(5,7,12,4,'O'),(5,8,12,5,'y'),(3,12,8,9,'y'),(8,13,13,9,'O'),(10,13,13,10,'y')):a.line(x,y,xx,yy,c)
    a.dot(8,7,'U');a.dot(9,8,'B');a.dot(3,3,'W');tex('amber_block',a)

    def cube(lo,hi,t,overrides=None,rotation=None):
        el={'from':lo,'to':hi,'faces':{s:{'texture':'#'+(overrides or {}).get(s,t)} for s in ('up','down','north','south','east','west')}}
        if rotation:el['rotation']=rotation
        return el
    def model(name,ts,els):
        data={'parent':'minecraft:block/block','textures':{**{k:'slavicmyths:block/'+v for k,v in ts.items()},'particle':'slavicmyths:block/'+ts[next(iter(ts))]},'elements':els}
        (res/f'models/block/{name}.json').write_text(json.dumps(data,indent=2)+'\n')
    model('altar',{'stone':'altar','rim':'altar_rim','top':'altar_top'},[
        cube([2,0,2],[14,2,14],'stone'),cube([3,2,3],[13,3,13],'rim'),
        cube([4,3,4],[12,9,12],'stone'),cube([2,9,2],[14,10,14],'rim'),
        cube([1,10,1],[15,12,15],'rim',{'up':'top'}),
        cube([3,3,3],[5,9,5],'stone'),cube([11,3,11],[13,9,13],'stone')])
    model('hearth',{'wood':'hearth','top':'hearth_top','dark':'hearth_dark','wax':'candle_wax','fire':'candle_flame'},[
        cube([1,0,2],[15,2,15],'wood',{'up':'top'}),cube([3,2,12],[13,12,14],'dark'),
        cube([2,2,3],[4,12,14],'wood'),cube([12,2,3],[14,12,14],'wood'),
        cube([1,12,2],[15,14,15],'wood',{'up':'top'}),cube([0,4,1],[16,5,14],'top'),
        cube([7,5,7],[9,8,9],'wax')])
    model('ancient_idol',{'wood':'ancient_idol','face':'idol_front','end':'hearth_top'},[
        cube([3,0,3],[13,2,13],'wood',{'up':'end'}),cube([5,2,5],[11,11,11],'wood'),
        cube([4,10,4],[12,15,12],'wood',{'north':'face','up':'end'}),
        cube([3,7,5],[5,10,10],'wood'),cube([11,7,5],[13,10,10],'wood'),
        cube([4,15,4],[12,16,12],'end')])
    flame1=cube([5,9,8],[11,15,8],'flame');flame1['faces']={s:{'texture':'#flame','uv':[0,0,16,16],'tintindex':-1} for s in ('north','south')}
    flame2=cube([8,9,5],[8,15,11],'flame');flame2['faces']={s:{'texture':'#flame','uv':[0,0,16,16]} for s in ('east','west')}
    model('ritual_candle',{'holder':'candle_holder','wax':'candle_wax','flame':'candle_flame'},[
        cube([5,0,5],[11,1,11],'holder'),cube([6,1,6],[10,2,10],'holder'),cube([6.5,2,6.5],[9.5,10,9.5],'wax'),flame1,flame2])

    # Armor face boundaries follow vanilla 64x32 biped UVs; trim each plate separately.
    for layer in (1,2):
        a=Art(64,32)
        def boxuv(u,v,w,h,d):
            faces=[(u+d,v,w,d),(u+d+w,v,w,d),(u,v+d,d,h),(u+d,v+d,w,h),(u+d+w,v+d,d,h),(u+2*d+w,v+d,w,h)]
            for x,y,fw,fh in faces:
                a.box(x,y,x+fw-1,y+fh-1,'N');a.box(x+1,y+1,x+fw-2,y+fh-2,'D')
                a.line(x,y,x+fw-1,y,'A');a.line(x,y,x,y+fh-1,'A')
                if fw>4:a.line(x+1,y+2,x+fw-2,y+2,'s')
        boxuv(0,0,8,8,8);boxuv(16,16,8,12,4);boxuv(0,16,4,12,4)
        if layer==1:
            boxuv(40,16,4,12,4)
            a.line(9,11,14,11,'N');a.dot(10,10,'c');a.dot(13,10,'a')
            a.line(21,23,23,25,'S');a.line(26,23,24,25,'A');a.dot(23,24,'c')
            a.line(21,28,26,28,'U');a.box(23,28,24,29,'y')
            a.line(4,29,7,29,'S');a.line(44,23,47,23,'A')
        else:
            a.line(20,20,27,20,'U');a.box(23,20,24,21,'y')
            a.line(4,24,7,24,'S');a.line(4,26,7,26,'A');a.dot(5,25,'a')
        tex(f'perunite_layer_{layer}',a,'models/armor')
