"""Bounded resource/JAR preservation gates; no runtime or game-world claims."""
from pathlib import Path
import json,re,zipfile,hashlib,importlib
from PIL import Image,ImageDraw
import rune_foundation_resources_1341 as overlay
ROOT=Path(__file__).resolve().parents[1];RES=ROOT/'src/main/resources';OUT=ROOT/'docs/media/rune-foundation-1341'
checks=0
def check(value,message):
 global checks
 checks+=1
 if not value:raise AssertionError(message)
def main():
 global checks
 OUT.mkdir(parents=True,exist_ok=True)
 build=(ROOT/'.tools/rune-1341/build.log').read_text(encoding='utf-8',errors='replace')
 check('BUILD SUCCESSFUL' in build,'clean build');check('ARMOR_OFFLINE_CHECKS=147' in build,'Old sockets/codecs regression')
 offline=re.search(r'RUNE_OFFLINE_CHECKS=(\d+) PLANS=(\d+) UPYR_MIN=([^\n]+)',build);check(offline is not None,'Rune codec and bounded roster checks')
 jar=ROOT/'build/libs/slavicmyths-1.3.4.1.jar';baseline=ROOT/'.tools/rune-1341/baseline.jar'
 allowed_resources={'assets/slavicmyths/lang/'+l+'.json' for l in ['ru_ru','en_us']}|{'data/slavicmyths/loot_table/entities/'+i+'.json' for i in ['kurgan_voevoda','buried_volkhv','unresting_prince']}
 changed=[];preserved=0
 with zipfile.ZipFile(baseline) as old,zipfile.ZipFile(jar) as new:
  before=set(old.namelist());after=set(new.namelist())
  check(not any('/verify/' in n or '/smoke/' in n for n in after),'No test classes in production')
  check('1.3.4.1' in new.read('META-INF/neoforge.mods.toml').decode(),'Production version')
  for name in before:
   check(name in after,'Old entry missing: '+name)
   if name.startswith(('assets/','data/')):
    if name in allowed_resources:
     original=json.loads(old.read(name));current=json.loads(new.read(name))
     if '/lang/' in name:check(all(current.get(k)==v for k,v in original.items()),'Old translation '+name)
     else:check(current['pools'][:-1]==original['pools'],'Old drops '+name)
    else:check(old.read(name)==new.read(name),'Unrelated resource changed '+name);preserved+=1
   elif name.endswith('.class') and old.read(name)!=new.read(name):changed.append(name)
  allowed_classes={'org/slavicmyths/SlavicMyths.class','org/slavicmyths/item/ItemState.class','org/slavicmyths/client/ClientSetup.class','org/slavicmyths/registry/ModItemGroup.class','org/slavicmyths/kurgan/KurganRoster.class','org/slavicmyths/kurgan/KurganInstance.class','org/slavicmyths/kurgan/KurganEncounters.class'}
  check(all(n in allowed_classes or n.startswith('org/slavicmyths/rpg/RpgMenu') for n in changed),'Unexpected old code changes '+str(changed))
  for n in after-before:
   if n.endswith('.class'):check(n.startswith(('org/slavicmyths/rpg/Rune','org/slavicmyths/client/RuneAnvilScreen','org/slavicmyths/compat/JeiRunes','org/slavicmyths/rpg/RpgMenu')),'Unexpected new class '+n)
   if n.startswith(('assets/','data/')):check(new.read(n)==(RES/n).read_bytes(),'Stale new resource '+n)
  for n in after:
   if n.endswith('.json'):json.loads(new.read(n));checks+=1
  # Common new classes may not resolve GUI/JEI; the optional plugin stays isolated.
  for n in after:
   if n.startswith('org/slavicmyths/rpg/Rune') and n.endswith('.class'):
    b=new.read(n);check(b'net/minecraft/client' not in b and b'mezz/jei' not in b,'Common loads client '+n)
 recipes=sorted((RES/'data/slavicmyths/recipe').glob('rune_foundation_*.json'));check(len(recipes)==15,'15 JSON anvil recipes')
 for p in recipes:
  r=json.loads(p.read_text());check(r['type']=='slavicmyths:rune_crafting','Recipe type');check(1<=len(r['inputs'])<=3,'Input slots')
  for c in r['inputs']:check(1<=c['count']<=64,'Count bounds')
  if 'dust_' in p.stem:check(r['chisel'] and r['inputs'][0]['count']==1 and r['result']['count']==4,'Grinding cost/output')
  if 'blank_' in p.stem:
   b=r['result']['components']['slavicmyths:rune_base'];allowed={1:['iron','gold'],2:['diamond','perunite'],3:['perunite']}
   check(b['material'] in allowed[b['tier']],'Tier/base');check(r['result']['id']==f"slavicmyths:blank_rune_{b['tier']}",'Blank ID/tier');check([c['count'] for c in r['inputs']]==[1,4,4],'Blank recipe quantities')
 for lang in ['ru_ru','en_us']:
  data=json.loads((RES/f'assets/slavicmyths/lang/{lang}.json').read_text(encoding='utf-8'))
  for id in overlay.NAMES:check(bool(data.get('item.slavicmyths.'+id)),'Item localization')
  for key in overlay.TEXT:check(bool(data.get('rune_foundation.slavicmyths.'+key)),'GUI localization')
 for id in overlay.NAMES:
  m=json.loads((RES/f'assets/slavicmyths/models/item/{id}.json').read_text());check(m['textures']['layer0']=='slavicmyths:item/'+id,'Model texture')
  im=Image.open(RES/f'assets/slavicmyths/textures/item/{id}.png');check(im.size==(32,32) and im.mode=='RGBA','Native pixel RGBA');check(im.getchannel('A').getextrema()==(0,255),'Transparency/content')
 # Reproduction must retain all generated bytes, including additive loot pools.
 generated=[RES/f'assets/slavicmyths/{kind}/{id}.{suffix}' for id in overlay.NAMES for kind,suffix in [('textures/item','png'),('models/item','json')]]+recipes+[RES/f'assets/slavicmyths/lang/{lang}.json' for lang in ['ru_ru','en_us']]+[RES/f'data/slavicmyths/loot_table/entities/{id}.json' for id in ['kurgan_voevoda','buried_volkhv','unresting_prince']]
 hashes={p:hashlib.sha256(p.read_bytes()).hexdigest() for p in generated};overlay.main()
 for p,digest in hashes.items():check(hashlib.sha256(p.read_bytes()).hexdigest()==digest,'Generator reproduction '+p.name)
 contact=Image.new('RGB',(1000,4*190),'#211912');d=ImageDraw.Draw(contact)
 for n,(id,names) in enumerate(overlay.NAMES.items()):
  x=(n%4)*250;y=(n//4)*190;im=Image.open(RES/f'assets/slavicmyths/textures/item/{id}.png').resize((128,128),Image.Resampling.NEAREST);contact.paste(im,(x+60,y+10),im);d.text((x+10,y+150),names[1],fill='#f2e8d8')
 contact.save(OUT/'items.png')
 # Layout checks for all requested physical-resolution/GUI-scale pairs, pure rectangles.
 layout=[]
 for w,h,requested in [(1649,928,2),(1649,928,3),(1649,928,4),(1920,1080,2),(1920,1080,3),(1920,1080,4),(2560,1440,3),(2560,1440,4)]:
  scale=1
  while scale<requested and w//(scale+1)>=320 and h//(scale+1)>=240:scale+=1
  gw=(w+scale-1)//scale;gh=(h+scale-1)//scale;check(202<=gw and 214<=gh,'Compact GUI bounds');layout.append({'physical':[w,h],'requestedScale':requested,'actualScale':scale,'gui':[gw,gh],'container':[202,214]})
 report={'version':'1.3.4.1','offlineJvmChecks':int(offline.group(1)),'rosterPlans':int(offline.group(2)),'observedUpyrs':offline.group(3).strip(),'resourceJarChecks':checks,'oldResourcesPreserved':preserved,'changedOldClasses':changed,'jar':str(jar),'sha256':hashlib.sha256(jar.read_bytes()).hexdigest(),'clientRuns':0,'serverRuns':0,'runtimeMenuCraftPersistenceTested':False,'guiLayout':layout,'jei':'Compilation against pinned 19.51.0.418 + isolated class audit; runtime untested'}
 path=ROOT/'docs/verification/rune-foundation-1.3.4.1.json';path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'resourceJarChecks':checks,'preserved':preserved,'sha256':report['sha256']},ensure_ascii=False))
if __name__=='__main__':main()
