"""Execute the production Xaero adapter against session-lifecycle test doubles.
No Minecraft client is started. This exercises teardown contracts, not Xaero UI rendering.
"""
from pathlib import Path
import subprocess,json
R=Path(__file__).resolve().parents[1];OUT=R/'work/xaero-lifecycle-097';OUT.mkdir(exist_ok=True);src=OUT/'src';classes=OUT/'classes';classes.mkdir(exist_ok=True)
files={
'net/minecraft/resources/ResourceLocation.java':'''package net.minecraft.resources; public record ResourceLocation(String namespace,String path){public static ResourceLocation fromNamespaceAndPath(String n,String p){return new ResourceLocation(n,p);}}''',
'net/minecraft/network/chat/Component.java':'''package net.minecraft.network.chat; public record Component(String text){public static Component translatable(String s,Object...args){return new Component(s);}public String getString(){return text;}}''',
'com/mojang/logging/LogUtils.java':'''package com.mojang.logging;public class LogUtils{public static LogUtils getLogger(){return new LogUtils();}public void debug(String s,Throwable e){}}''',
'org/slavicmyths/navigation/MarkerCategory.java':'''package org.slavicmyths.navigation;public enum MarkerCategory{YAGA,WAYSTONE,KURGAN,BANDIT,BOSS,QUEST,SPECIAL_LOCATION,EVENT;public String symbol="X";}''',
'org/slavicmyths/navigation/SearchArea.java':'''package org.slavicmyths.navigation;public record SearchArea(int radius){public enum State{INSIDE_SEARCH_AREA,OUTSIDE}public State state(){return State.OUTSIDE;}}''',
'org/slavicmyths/navigation/NavigationState.java':'''package org.slavicmyths.navigation;import java.util.*;import net.minecraft.resources.ResourceLocation;public class NavigationState{public enum Preference{XAERO}public Set<Preference> preferences=new HashSet<>();public Map<UUID,Marker> markers=new HashMap<>();public UUID tracked;public boolean visible(Marker m){return true;}public record Marker(UUID id,ResourceLocation dimension,String name,MarkerCategory category,int x,int y,int z,SearchArea area){}}''',
'xaero/hud/minimap/waypoint/WaypointColor.java':'''package xaero.hud.minimap.waypoint;public enum WaypointColor{DARK_PURPLE,AQUA,GRAY,DARK_RED,RED,GOLD,GREEN,YELLOW}''',
'xaero/common/minimap/waypoints/WaypointVisibilityType.java':'''package xaero.common.minimap.waypoints;public enum WaypointVisibilityType{GLOBAL}''',
'xaero/common/minimap/waypoints/Waypoint.java':'''package xaero.common.minimap.waypoints;import xaero.hud.minimap.waypoint.WaypointColor;import net.minecraft.resources.ResourceLocation;public class Waypoint{public Waypoint(int x,int y,int z,String name,String symbol,WaypointColor color){}public void setTemporary(boolean b){}public void setThirdPartyOrigin(ResourceLocation r){}public void setName(String n){}public void setX(int i){}public void setY(int i){}public void setZ(int i){}public void setColor(int i){}public void setSymbol(String s){}public void setYIncluded(boolean b){}public void setVisibility(WaypointVisibilityType v){}}''',
'xaero/common/minimap/waypoints/WaypointSet.java':'''package xaero.common.minimap.waypoints;import java.util.*;public class WaypointSet{public List<Waypoint> points=new ArrayList<>();public Runnable onRemove=()->{};public void add(Waypoint p){points.add(p);}public void remove(Waypoint p){onRemove.run();points.remove(p);}}''',
'xaero/common/minimap/waypoints/WaypointWorld.java':'''package xaero.common.minimap.waypoints;import java.util.*;import net.minecraft.resources.ResourceLocation;public class WaypointWorld{public record Dimension(ResourceLocation location){}public Dimension getDimId(){return new Dimension(ResourceLocation.fromNamespaceAndPath("minecraft","overworld"));}public Map<String,WaypointSet> sets=new HashMap<>();public Map<String,WaypointSet> getSets(){return sets;}public void addSet(String n){sets.put(n,new WaypointSet());}public WaypointSet getCurrentSet(){return null;}}''',
'xaero/common/minimap/waypoints/WaypointsManager.java':'''package xaero.common.minimap.waypoints;public class WaypointsManager{public int updates;public boolean throwOnUpdate;public WaypointWorld world=new WaypointWorld();public WaypointWorld getCurrentWorld(){return world;}public void updateWaypoints(){updates++;if(throwOnUpdate)throw new NullPointerException("Closed session");}}''',
'xaero/common/XaeroMinimapSession.java':'''package xaero.common;import xaero.common.minimap.waypoints.*;public class XaeroMinimapSession{public static XaeroMinimapSession current;public WaypointsManager manager;public static XaeroMinimapSession getCurrentSession(){return current;}public WaypointsManager getWaypointsManager(){return manager;}}''',
'LifecycleCheck.java':'''import java.util.*;import java.lang.reflect.*;import xaero.common.*;import xaero.common.minimap.waypoints.*;import xaero.hud.minimap.waypoint.*;import org.slavicmyths.compat.xaero.XaeroNavigationBridge;import org.slavicmyths.navigation.*;import net.minecraft.resources.ResourceLocation;
public class LifecycleCheck{
 static Object get(Object b,String name)throws Exception{var f=b.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(b);}static void set(Object b,String name,Object value)throws Exception{var f=b.getClass().getDeclaredField(name);f.setAccessible(true);f.set(b,value);}static void check(boolean p){if(!p)throw new AssertionError();}
 public static void main(String[] args)throws Exception{
  int cases=0;for(int mode=0;mode<5;mode++){
   var bridge=new XaeroNavigationBridge();var session=new XaeroMinimapSession();var manager=new WaypointsManager();session.manager=mode==0?null:manager;XaeroMinimapSession.current=mode==2?null:session;if(mode==3)XaeroMinimapSession.current=new XaeroMinimapSession();manager.throwOnUpdate=mode==4;
   var group=new WaypointSet();var user=new Waypoint(0,0,0,"User","U",WaypointColor.GRAY);var own=new Waypoint(1,1,1,"Mod","M",WaypointColor.GRAY);group.add(user);group.add(own);set(bridge,"session",session);set(bridge,"set",group);((Map)get(bridge,"owned")).put(UUID.randomUUID(),own);
   group.onRemove=()->{try{check(get(bridge,"session")==null&&get(bridge,"set")==null&&((Map)get(bridge,"owned")).isEmpty());}catch(Exception e){throw new RuntimeException(e);}};
   bridge.clear();check(group.points.equals(List.of(user)));check(manager.updates==((mode==1||mode==4)?1:0));check(get(bridge,"publishedState")==null);bridge.clear();check(group.points.equals(List.of(user)));cases++;
  }
  var b=new XaeroNavigationBridge();XaeroMinimapSession.current=null;check(!b.publish(new NavigationState(),ResourceLocation.fromNamespaceAndPath("minecraft","overworld")));cases++;
  XaeroMinimapSession.current=new XaeroMinimapSession();check(!b.publish(new NavigationState(),ResourceLocation.fromNamespaceAndPath("minecraft","overworld")));cases++;
  XaeroMinimapSession.current.manager=new WaypointsManager();XaeroMinimapSession.current.manager.world=null;check(!b.publish(new NavigationState(),ResourceLocation.fromNamespaceAndPath("minecraft","overworld")));cases++;
  check(!b.publish(null,ResourceLocation.fromNamespaceAndPath("minecraft","overworld")));cases++;check(!b.publish(new NavigationState(),null));cases++;
  System.out.println("XAERO_LIFECYCLE_PASS cases="+cases+" userWaypointPreserved=true internalStateClearedFirst=true");
 }}'''}
for file,text in files.items():p=src/file;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')
java=Path('C:/Program Files/Java/jdk-21.0.12/bin');actual=[R/'src/main/java/org/slavicmyths/compat/xaero/XaeroNavigationBridge.java',R/'src/main/java/org/slavicmyths/navigation/client/MapIntegrationBridge.java'];subprocess.run([str(java/'javac.exe'),'-encoding','UTF-8','-d',str(classes),*[str(p) for p in src.rglob('*.java')],*map(str,actual)],check=True);result=subprocess.run([str(java/'java.exe'),'-cp',str(classes),'LifecycleCheck'],check=True,capture_output=True,text=True);print(result.stdout.strip());out=R/'docs/verification/swamp-0.9.7';out.mkdir(exist_ok=True);(out/'xaero-lifecycle.json').write_text(json.dumps({'status':'PASS','cases':10,'productionAdapterExecuted':True,'usesSessionLifecycleTestDoubles':True,'clientLaunched':False,'output':result.stdout.strip()},indent=2)+'\n',encoding='utf-8')
